### PR TITLE
Move the first part of the WORKSPACE to bzl

### PR DESCRIPTION
**Pull request by enfreck**
Move the first part of the WORKSPACE to dep.bzl files and move
http_archives to repo.bzl files

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/20)

### CODE REVIEW

**Review by efoxepstein — APPROVED** [review]
> Reviewed 22 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/20)* status: all files reviewed, 2 unresolved discussions (waiting on @enfreck)

___
*[build/com_google_absl/repo.bzl, line 21 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/20#-MfoFbGk2JEXTpov3qhQ:-MfoFbGk2JEXTpov3qhR:bfy44d7) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/7e9132f850bf7ceb2c29fedb3cfea2f8ac9149ba/build/com_google_absl/repo.bzl#L21)):*
> ```Starlark
> load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
> 
> def com_google_absl_repo():
> ```

Out of curiosity, why does this repo need abseil? Does anything break if you remove it?
___
*[build/googletest/repo.bzl, line 21 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/20#-MfoGaYyAAMjLpok-yvn:-MfoGaYzDN4-5S3xJHRk:bv4keyu) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/7e9132f850bf7ceb2c29fedb3cfea2f8ac9149ba/build/googletest/repo.bzl#L21)):*
> ```Starlark
> load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
> 
> def googletest_repo():
> ```

Out of curiosity, why does this repo need googletest? Does anything break if you remove it?

**Review by enfreck — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/20)* status: 17 of 22 files reviewed, 2 unresolved discussions (waiting on @efoxepstein, @oliver-amzn, @SanjayVas, and @stevenwarejones)

___
*[build/com_google_absl/repo.bzl, line 21 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/20#-MfoFbGk2JEXTpov3qhQ:-MfoK2h9DThfM5Uwsy4W:bwhqlqp) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/7e9132f850bf7ceb2c29fedb3cfea2f8ac9149ba/build/com_google_absl/repo.bzl#L21)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Out of curiosity, why does this repo need abseil? Does anything break if you remove it?
</blockquote></details>

It didn't.  Should be deleted now.
___
*[build/googletest/repo.bzl, line 21 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/20#-MfoGaYyAAMjLpok-yvn:-MfoK6wSCtBWMacdYmof:b-89a4l7) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/7e9132f850bf7ceb2c29fedb3cfea2f8ac9149ba/build/googletest/repo.bzl#L21)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Out of curiosity, why does this repo need googletest? Does anything break if you remove it?
</blockquote></details>

Ditto

**Review by enfreck — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/20)* status: 17 of 22 files reviewed, 2 unresolved discussions (waiting on @efoxepstein, @oliver-amzn, @SanjayVas, and @stevenwarejones)

___
*[build/com_google_absl/repo.bzl, line 21 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/20#-MfoFbGk2JEXTpov3qhQ:-MfoK9QLBzS5GwBDyixC:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/7e9132f850bf7ceb2c29fedb3cfea2f8ac9149ba/build/com_google_absl/repo.bzl#L21)):*
<details><summary><i>Previously, enfreck wrote…</i></summary><blockquote>

It didn't.  Should be deleted now.
</blockquote></details>

Done.
___
*[build/googletest/repo.bzl, line 21 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/20#-MfoGaYyAAMjLpok-yvn:-MfoK94V8JMvmdrDCDQB:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/7e9132f850bf7ceb2c29fedb3cfea2f8ac9149ba/build/googletest/repo.bzl#L21)):*
<details><summary><i>Previously, enfreck wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/20)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliver-amzn, @SanjayVas, and @stevenwarejones)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/20)* status: 20 of 23 files reviewed, 2 unresolved discussions (waiting on @efoxepstein, @enfreck, @oliver-amzn, and @stevenwarejones)

___
*[build/deps_step1.bzl, line 26 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/20#-MfsWzaQ8kfpEOmRmauk:-MfsWzaQ8kfpEOmRmaul:b-nsrplr) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/7ce388c2b36e11da0bdbc99fd8f5f0e0fb8763f3/build/deps_step1.bzl#L26)):*
> ```
> common-cpp
> ```
common-jvm
___
*[build/deps_step1.bzl, line 31 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/20#-MfsX-WLBMDwcypZPYUb:-MfsX-WLBMDwcypZPYUc:b-yq89t2) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/7ce388c2b36e11da0bdbc99fd8f5f0e0fb8763f3/build/deps_step1.bzl#L31)):*
> ```Starlark
>     platforms_repo()
>     com_google_protobuf_repo()
>     rules_kotlin_repo()
> ```

You can technically put anything that just downloads in the first step, since order doesn't matter until you actually start loading any defs. Anything that evaluates to an `http_archive` or `http_file` target can go in here. This way, we also avoid issues with existing_rules checks, as in some cases the order meant that we were intentionally overriding something.

**Review by enfreck — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/20)* status: 16 of 23 files reviewed, 2 unresolved discussions (waiting on @efoxepstein, @oliver-amzn, @SanjayVas, and @stevenwarejones)

___
*[build/deps_step1.bzl, line 26 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/20#-MfsWzaQ8kfpEOmRmauk:-Mfsk8RK64QlY97opChU:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/7ce388c2b36e11da0bdbc99fd8f5f0e0fb8763f3/build/deps_step1.bzl#L26)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> common-cpp
> ```
common-jvm
</blockquote></details>

Done.
___
*[build/deps_step1.bzl, line 31 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/20#-MfsX-WLBMDwcypZPYUb:-MfskCBC8OYE33V7W9lB:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/7ce388c2b36e11da0bdbc99fd8f5f0e0fb8763f3/build/deps_step1.bzl#L31)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You can technically put anything that just downloads in the first step, since order doesn't matter until you actually start loading any defs. Anything that evaluates to an `http_archive` or `http_file` target can go in here. This way, we also avoid issues with existing_rules checks, as in some cases the order meant that we were intentionally overriding something.
</blockquote></details>

Done.

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 1 of 3 files at r3, 4 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/20)* status: 21 of 23 files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @enfreck, @oliver-amzn, and @stevenwarejones)

___
*[build/deps_step1.bzl, line 31 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/20#-MfssCiFC-lo7256Ikwq:-MfssCiG0Ew8-z0K_BE5:bm8358b) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/bf5df11c3d553c171892904cae0a06ebac9f709b/build/deps_step1.bzl#L31)):*
> ```Starlark
> load("//build/io_bazel_rules_docker:repo.bzl", "rules_docker_repo")
> 
> def common_jvm_deps_step1():
> ```

I personally would rather these be descriptive rather than numbered. Most other repos do this rather than numbered steps as well. We can show how to depend on this from other Bazel workspaces in the README.

Perhaps also name this first file `repositories.bzl` to mirror the [pattern used when deploying Bazel rules](https://docs.bazel.build/versions/4.1.0/skylark/deploying.html#dependencies).

@efoxepstein WDYT?

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/20)* status: 21 of 23 files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @oliver-amzn, @SanjayVas, and @stevenwarejones)

___
*[build/deps_step1.bzl, line 31 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/20#-MfssCiFC-lo7256Ikwq:-MfsvFdc6cjfr1LOE4ed:b-hejzxy) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/bf5df11c3d553c171892904cae0a06ebac9f709b/build/deps_step1.bzl#L31)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I personally would rather these be descriptive rather than numbered. Most other repos do this rather than numbered steps as well. We can show how to depend on this from other Bazel workspaces in the README.

Perhaps also name this first file `repositories.bzl` to mirror the [pattern used when deploying Bazel rules](https://docs.bazel.build/versions/4.1.0/skylark/deploying.html#dependencies).

@efoxepstein WDYT?
</blockquote></details>

Precedent for steps comes from ZetaSQL. I think we'll need at least 3 steps so what would you recommend naming them all?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/20)* status: 21 of 23 files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @oliver-amzn, and @stevenwarejones)

___
*[build/deps_step1.bzl, line 31 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/20#-MfssCiFC-lo7256Ikwq:-Mfsvf3fAikpAfP-4lBo:bxx2xdd) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/bf5df11c3d553c171892904cae0a06ebac9f709b/build/deps_step1.bzl#L31)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Precedent for steps comes from ZetaSQL. I think we'll need at least 3 steps so what would you recommend naming them all?
</blockquote></details>

ZetaSQL is a bit of an outlier IMO.

gRPC uses `_deps` and `_extra_deps` for it's two subsequent steps. Perhaps `_repositories`, `_deps`, `_extra_deps`, `_maven_deps` (if we end up needing an additional step for Maven)?

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/20)* status: 21 of 23 files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @oliver-amzn, @SanjayVas, and @stevenwarejones)

___
*[build/deps_step1.bzl, line 31 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/20#-MfssCiFC-lo7256Ikwq:-MfsxwHU2HT6U1jcsqpA:bb7422a) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/bf5df11c3d553c171892904cae0a06ebac9f709b/build/deps_step1.bzl#L31)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

ZetaSQL is a bit of an outlier IMO.

gRPC uses `_deps` and `_extra_deps` for it's two subsequent steps. Perhaps `_repositories`, `_deps`, `_extra_deps`, `_maven_deps` (if we end up needing an additional step for Maven)?
</blockquote></details>

Sgtm

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r3, 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/20)* status: all files reviewed, 1 unresolved discussion (waiting on @enfreck, @oliver-amzn, and @stevenwarejones)

___
*[build/common_jvm_deps.bzl, line 32 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/20#-Mg623bZ2zKKeiu5oghC:-Mg623bZ2zKKeiu5oghD:b1pzvhn) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/4ebef279362f7f8db4325d3d4435f196f6f25dd9/build/common_jvm_deps.bzl#L32)):*
> ```Starlark
>     base_java_images(
>         # gcr.io/distroless/java:11-debug
>         debug_digest = "sha256:c3fe781de55d375de2675c3f23beb3e76f007e53fed9366ba931cc6d1df4b457",
> ```

Hardcore these values inside the Bazel file it's loaded from? For consistency with everything else

**Review by enfreck — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/20)* status: 21 of 27 files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @oliver-amzn, @SanjayVas, and @stevenwarejones)

___
*[build/common_jvm_deps.bzl, line 32 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/20#-Mg623bZ2zKKeiu5oghC:-Mg6Ao9E2VLfajr9vDw6:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/4ebef279362f7f8db4325d3d4435f196f6f25dd9/build/common_jvm_deps.bzl#L32)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Hardcore these values inside the Bazel file it's loaded from? For consistency with everything else
</blockquote></details>

Done.

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r6.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/20)* status: all files reviewed, 4 unresolved discussions (waiting on @enfreck, @oliver-amzn, and @stevenwarejones)

___
*[build/cloud_spanner_emulator/defs.bzl, line 18 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/20#-Mg6Gv1z67KBiSoLrM3O:-Mg6Gv1z67KBiSoLrM3P:b-ynr56r) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/8d74c16662d97f31e86601c4ab7ad2db3f4c45a6/build/cloud_spanner_emulator/defs.bzl#L18)):*
> ```Starlark
> 
> def _cloud_spanner_emulator_impl(rctx):
>     version = "1.1.1"
> ```

I think you can undo this change because of the macro below (like, we should only have the version hardcoded in one place
___
*[build/cloud_spanner_emulator/defs.bzl, line 41 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/20#-Mg6H5ng0TBUEigXwEqC:-Mg6H5ng0TBUEigXwEqD:btekj03) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/8d74c16662d97f31e86601c4ab7ad2db3f4c45a6/build/cloud_spanner_emulator/defs.bzl#L41)):*
> ```Starlark
> )
> 
> def cloud_spanner_emulator():
> ```

@sanjayvas should this one be named c_s_e_binaries and then the rule be named c_s_e_binaries_internal or something?
___
*[build/cue/repo.bzl, line 38 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/20#-Mg6HSga8R1yZmg4bw7K:-Mg6HSga8R1yZmg4bw7L:b7bucr9) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/8d74c16662d97f31e86601c4ab7ad2db3f4c45a6/build/cue/repo.bzl#L38)):*
> ```Starlark
> )
> 
> def cue():
> ```

@sanjayvas ditto
___
*[build/io_bazel_rules_docker/repo.bzl, line 47 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/20#-Mg6HiNu-yjJefzJYg47:-Mg6HiNu-yjJefzJYg48:b7bucr9) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/8d74c16662d97f31e86601c4ab7ad2db3f4c45a6/build/io_bazel_rules_docker/repo.bzl#L47)):*
> ```Starlark
>     )
> 
> def rules_docker():
> ```

@sanjayvas ditto

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/20)* status: all files reviewed, 4 unresolved discussions (waiting on @efoxepstein, @enfreck, @oliver-amzn, @SanjayVas, and @stevenwarejones)

___
*[build/cloud_spanner_emulator/defs.bzl, line 41 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/20#-Mg6H5ng0TBUEigXwEqC:-Mg6oR1g16Iv9_NQi2wY:b-o91tx5) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/8d74c16662d97f31e86601c4ab7ad2db3f4c45a6/build/cloud_spanner_emulator/defs.bzl#L41)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I would name the macro `cloud_spanner_emulator_binaries` and just import the internal one with a leading `_`. That's a common enough convention I've seen in other repos.
</blockquote></details>

So change `cloud_spanner_emulator_binaries = repository_rule(` to `_cloud_spanner_emulator_binaries = repository_rule(` and then change `def cloud_spanner_emulator()` to `def cloud_spanner_emulator_binaries(): _cloud_spanner_emulator_binaries(name = ..., sha256 = ..., version = ...)`?

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/20)* status: all files reviewed, 4 unresolved discussions (waiting on @enfreck, @oliver-amzn, @SanjayVas, and @stevenwarejones)

___
*[build/cue/repo.bzl, line 38 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/20#-Mg6HSga8R1yZmg4bw7K:-Mg6pRvCEDjLFJNd9Fuz:bwuddx7) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/8d74c16662d97f31e86601c4ab7ad2db3f4c45a6/build/cue/repo.bzl#L38)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Same recommendation here.
</blockquote></details>

Thanks -- @enfreck, do you understand what we want here?
___
*[build/io_bazel_rules_docker/repo.bzl, line 47 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/20#-Mg6HiNu-yjJefzJYg47:-Mg6p_hlBlOr5tfYK_4H:bwuddx7) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/8d74c16662d97f31e86601c4ab7ad2db3f4c45a6/build/io_bazel_rules_docker/repo.bzl#L47)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Same recommendation.
</blockquote></details>

Thanks -- @enfreck, do you understand what we want here?

**Review by SanjayVas — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/20)* status: all files reviewed, 4 unresolved discussions (waiting on @efoxepstein, @enfreck, @oliver-amzn, and @stevenwarejones)

___
*[build/cloud_spanner_emulator/defs.bzl, line 41 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/20#-Mg6H5ng0TBUEigXwEqC:-Mg6qGKyBIeG2YacDKN5:bxhac1h) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/8d74c16662d97f31e86601c4ab7ad2db3f4c45a6/build/cloud_spanner_emulator/defs.bzl#L41)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

So change `cloud_spanner_emulator_binaries = repository_rule(` to `_cloud_spanner_emulator_binaries = repository_rule(` and then change `def cloud_spanner_emulator()` to `def cloud_spanner_emulator_binaries(): _cloud_spanner_emulator_binaries(name = ..., sha256 = ..., version = ...)`?
</blockquote></details>

Yes.

Sorry, I originally thought this macro was defined in a separate file, in which case you could just import it prefixed in the `load` statement. If in the same file like in this case, just prefix the underlying rule with `_` to mark it as the private/internal one.

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/20)* status: all files reviewed, 4 unresolved discussions (waiting on @enfreck, @oliver-amzn, and @stevenwarejones)

___
*[build/cloud_spanner_emulator/defs.bzl, line 41 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/20#-Mg6H5ng0TBUEigXwEqC:-Mg6uRQSEn61JgaBrCoi:bmw4ddi) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/8d74c16662d97f31e86601c4ab7ad2db3f4c45a6/build/cloud_spanner_emulator/defs.bzl#L41)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Yes.

Sorry, I originally thought this macro was defined in a separate file, in which case you could just import it prefixed in the `load` statement. If in the same file like in this case, just prefix the underlying rule with `_` to mark it as the private/internal one.
</blockquote></details>

Great. @enfreck -- does this make sense?

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 12 of 22 files at r1, 1 of 3 files at r3, 2 of 4 files at r5, 6 of 6 files at r6.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/20)* status: all files reviewed, 4 unresolved discussions (waiting on @enfreck and @oliver-amzn)

**Review by enfreck — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/20)* status: 23 of 27 files reviewed, 4 unresolved discussions (waiting on @efoxepstein, @oliver-amzn, @SanjayVas, and @stevenwarejones)

___
*[build/cloud_spanner_emulator/defs.bzl, line 18 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/20#-Mg6Gv1z67KBiSoLrM3O:-Mg78Lzk2Ga9FXFO-FQq:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/8d74c16662d97f31e86601c4ab7ad2db3f4c45a6/build/cloud_spanner_emulator/defs.bzl#L18)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I think you can undo this change because of the macro below (like, we should only have the version hardcoded in one place
</blockquote></details>

Done.
___
*[build/cloud_spanner_emulator/defs.bzl, line 41 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/20#-Mg6H5ng0TBUEigXwEqC:-Mg78Mhl9sZPv3G4ERNs:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/8d74c16662d97f31e86601c4ab7ad2db3f4c45a6/build/cloud_spanner_emulator/defs.bzl#L41)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Great. @enfreck -- does this make sense?
</blockquote></details>

Done.
___
*[build/cue/repo.bzl, line 38 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/20#-Mg6HSga8R1yZmg4bw7K:-Mg78OhF-_SbauyaRVGQ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/8d74c16662d97f31e86601c4ab7ad2db3f4c45a6/build/cue/repo.bzl#L38)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Thanks -- @enfreck, do you understand what we want here?
</blockquote></details>

Done.
___
*[build/io_bazel_rules_docker/repo.bzl, line 47 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/20#-Mg6HiNu-yjJefzJYg47:-Mg78PIx9wvvUE6tqgXw:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/8d74c16662d97f31e86601c4ab7ad2db3f4c45a6/build/io_bazel_rules_docker/repo.bzl#L47)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Thanks -- @enfreck, do you understand what we want here?
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 4 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/20)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliver-amzn)

**Review by efoxepstein — APPROVED** [review]
> Reviewed 4 of 4 files at r8.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/20)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliver-amzn)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 3 of 4 files at r7, 4 of 4 files at r8.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/20)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliver-amzn)

**Pull request merged**
