### PR TITLE
Add a method to build a channel with client certs.

### PR DESCRIPTION
**Pull request by wangyaopw**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/16)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/16)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones, @wangyaopw, and @zachcwc)

___
*[src/test/kotlin/org/wfanet/measurement/common/grpc/TransportSecurityTest.kt, line 136 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/16#-MfJXeAr2_vI47ASqI98:-MfJXeAr2_vI47ASqI99:blm5n1d) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/51be90e3a5af04e6a0d00308a72ea4b4426f15c4/src/test/kotlin/org/wfanet/measurement/common/grpc/TransportSecurityTest.kt#L136)):*
> ```
> clientCerts
> ```
This should only be passed in the mTLS test method. This test method is specifically testing server TLS only.

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/16)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas, @stevenwarejones, and @zachcwc)

___
*[src/test/kotlin/org/wfanet/measurement/common/grpc/TransportSecurityTest.kt, line 136 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/16#-MfJXeAr2_vI47ASqI98:-MfJYz9j3uPbUn8SOZNw:b3okhbq) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/51be90e3a5af04e6a0d00308a72ea4b4426f15c4/src/test/kotlin/org/wfanet/measurement/common/grpc/TransportSecurityTest.kt#L136)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> clientCerts
> ```
This should only be passed in the mTLS test method. This test method is specifically testing server TLS only.
</blockquote></details>

oops, didn't notice that.

Then, something is wrong, since removing the cert will fail the test. Let me take a look.

**Review by SanjayVas — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/16)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones, @wangyaopw, and @zachcwc)

___
*[src/test/kotlin/org/wfanet/measurement/common/grpc/TransportSecurityTest.kt, line 136 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/16#-MfJXeAr2_vI47ASqI98:-MfJeGVuDyihPwCDlzNX:b-o9xrlq) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/51be90e3a5af04e6a0d00308a72ea4b4426f15c4/src/test/kotlin/org/wfanet/measurement/common/grpc/TransportSecurityTest.kt#L136)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

oops, didn't notice that.

Then, something is wrong, since removing the cert will fail the test. Let me take a look.
</blockquote></details>

Sorry, I made a mistake. Setting up the SSL context in the channel does multiple things:

1. Sets up the channel to use TLS as opposed to plaintext.
2. Specifies the server root certs that the client trusts.
3. Specifies a cert and private key for client auth (mTLS).

It's this third piece that we don't need, as the server will ignore it with `ClientAuth.NONE`. The proper thing to do would be to have a way to omit (3) from the TLS contexts (e.g. by not having it included in SigningCerts), but that can be in another PR if it needs a little more work to get right. Just adding a TODO is fine in that case.

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/16)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @SanjayVas, @stevenwarejones, and @zachcwc)

___
*[src/test/kotlin/org/wfanet/measurement/common/grpc/TransportSecurityTest.kt, line 136 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/16#-MfJXeAr2_vI47ASqI98:-MfJkv1a77M0XR9hwUo7:b-atko1a) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/51be90e3a5af04e6a0d00308a72ea4b4426f15c4/src/test/kotlin/org/wfanet/measurement/common/grpc/TransportSecurityTest.kt#L136)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Sorry, I made a mistake. Setting up the SSL context in the channel does multiple things:

1. Sets up the channel to use TLS as opposed to plaintext.
2. Specifies the server root certs that the client trusts.
3. Specified a cert and private key for client auth (mTLS).

It's this third piece that we don't need, as the server will ignore it with `ClientAuth.NONE`. The proper thing to do would be to have a way to omit #3 from the TLS contexts (e.g. by not having it included in SigningCerts), but that can be in another PR if it needs a little more work to get right. Just adding a TODO is fine in that case.
</blockquote></details>

how about now?

since there is already a buildPlaintextChannel(), I added buildMTlsChannel() and buildTlsChannel.  Do you prefer mutilple overloading of buildChannel or different names?

**Review by SanjayVas — APPROVED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/16)* status: all files reviewed, 3 unresolved discussions (waiting on @stevenwarejones, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/common/grpc/Channel.kt, line 43 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/16#-MfJpj92-Sxh65jwUJra:-MfJpj92-Sxh65jwUJrb:bfq30b9) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/7eeb2dafa847a3cbe42775568ab63811ab70d828/src/main/kotlin/org/wfanet/measurement/common/grpc/Channel.kt#L43)):*
> ```
> buildMTlsChannel
> ```
Maybe use `buildClientAuthTlsChannel` or `buildMutualTlsChannel` to avoid having to contend with casing of abbreviation vs. naming style?
___
*[src/test/kotlin/org/wfanet/measurement/common/grpc/TransportSecurityTest.kt, line 136 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/16#-MfJXeAr2_vI47ASqI98:-MfJqFOmCGs3omKHiflD:b-6etvx8) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/51be90e3a5af04e6a0d00308a72ea4b4426f15c4/src/test/kotlin/org/wfanet/measurement/common/grpc/TransportSecurityTest.kt#L136)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

how about now?

since there is already a buildPlaintextChannel(), I added buildMTlsChannel() and buildTlsChannel.  Do you prefer mutilple overloading of buildChannel or different names?
</blockquote></details>

Separate methods rather than overloads, since they do distinctly different things.
___
*[src/test/kotlin/org/wfanet/measurement/common/grpc/TransportSecurityTest.kt, line 65 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/16#-MfJqSuk0Am-CZr2M0tx:-MfJqSuk0Am-CZr2M0ty:b-ehtly4) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/7eeb2dafa847a3cbe42775568ab63811ab70d828/src/test/kotlin/org/wfanet/measurement/common/grpc/TransportSecurityTest.kt#L65)):*
> ```
> trustedServerCertificates
> ```
You can still just pass this from clientCerts.trustedCertCollectionFile rather than re-reading it.

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/16)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/common/grpc/Channel.kt, line 43 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/16#-MfJpj92-Sxh65jwUJra:-MfJvAaj4m3RpbgpivNr:bxk1x2g) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/7eeb2dafa847a3cbe42775568ab63811ab70d828/src/main/kotlin/org/wfanet/measurement/common/grpc/Channel.kt#L43)):*
> buildMutualTlsChannel
changed to buildMutualTlsChannel 
___
*[src/test/kotlin/org/wfanet/measurement/common/grpc/TransportSecurityTest.kt, line 65 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/16#-MfJqSuk0Am-CZr2M0tx:-MfJvH3s2Hdzz6M2VyXo:b-ecnsbe) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/7eeb2dafa847a3cbe42775568ab63811ab70d828/src/test/kotlin/org/wfanet/measurement/common/grpc/TransportSecurityTest.kt#L65)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> trustedServerCertificates
> ```
You can still just pass this from clientCerts.trustedCertCollectionFile rather than re-reading it.
</blockquote></details>

yep, totally correct.

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/16)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones and @zachcwc)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 4 files at r2, 2 of 2 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/16)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliver-amzn and @zachcwc)

**Pull request merged**
