### PR TITLE
Add S3StorageClient

### PR DESCRIPTION
**Pull request by efoxepstein**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/68)

### CODE REVIEW

**Review by efoxepstein — COMMENTED** [review]
Amazon does not provide a fake implementation of S3, so short of reimplementing S3 or pulling in some unofficial local S3 third party package, we can't do this.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/68#-:-MqWV-P34yCRWm9wa6DQ:bb6vv3r)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/68)* status: all files reviewed, 4 unresolved discussions (waiting on @efoxepstein)

___
*[imports/java/software/amazon/awssdk/BUILD.bazel, line 4 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/68#-Mq_X_t51AZXy_Vr6OkX:-Mq_X_t51AZXy_Vr6OkY:b2t6dbt) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/5567df4de81b38e890b0377f843fb2b1a310465b/imports/java/software/amazon/awssdk/BUILD.bazel#L4)):*
> ```Starlark
> 
> alias(
>     name = "s3",
> ```

Looking at the Java package paths, shouldn't this be under a `services` subpackage?
___
*[src/main/kotlin/org/wfanet/measurement/aws/s3/S3StorageClient.kt, line 39 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/68#-Mq_YEg3BW4Lw-nS66HZ:-Mq_YEg3BW4Lw-nS66H_:bjmhqq3) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/5567df4de81b38e890b0377f843fb2b1a310465b/src/main/kotlin/org/wfanet/measurement/aws/s3/S3StorageClient.kt#L39)):*
> ```
> internal
> ```
not private? What else needs to access this?
___
*[src/main/kotlin/org/wfanet/measurement/aws/s3/S3StorageClient.kt, line 71 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/68#-Mq_YccE7xfyOa_uGBr4:-Mq_YccE7xfyOa_uGBr5:bv1b8nf) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/5567df4de81b38e890b0377f843fb2b1a310465b/src/main/kotlin/org/wfanet/measurement/aws/s3/S3StorageClient.kt#L71)):*
> ```
> md5.value
> ```
Won't this be a running MD5 of all of the content so far? Is that what this is supposed to be, or the MD5 of just that part?
___
*[src/main/kotlin/org/wfanet/measurement/common/Bytes.kt, line 220 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/68#-Mq_beuz5Wk21-3R_S0g:-Mq_beuz5Wk21-3R_S0h:b-jxn87c) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/5567df4de81b38e890b0377f843fb2b1a310465b/src/main/kotlin/org/wfanet/measurement/common/Bytes.kt#L220)):*
> ```
> ByteString.copyFrom(buffer)
> ```
Couldn't this result in the final ByteString having extra bytes if the buffer is too big? Likely need to specify the number of bytes actually read.

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/68)* status: 1 of 6 files reviewed, 4 unresolved discussions (waiting on @SanjayVas)

___
*[imports/java/software/amazon/awssdk/BUILD.bazel, line 4 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/68#-Mq_X_t51AZXy_Vr6OkX:-Mq_i2g8ED6SsRCReRnX:b-df76iq) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/5567df4de81b38e890b0377f843fb2b1a310465b/imports/java/software/amazon/awssdk/BUILD.bazel#L4)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Looking at the Java package paths, shouldn't this be under a `services` subpackage?
</blockquote></details>

What do we do about the fact that it has `services.s3` and `services.s3.model`? (Also: moved to services)
___
*[src/main/kotlin/org/wfanet/measurement/aws/s3/S3StorageClient.kt, line 39 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/68#-Mq_YEg3BW4Lw-nS66HZ:-Mq_gk7qAovjr-uVCiF0:b-53rbl8) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/5567df4de81b38e890b0377f843fb2b1a310465b/src/main/kotlin/org/wfanet/measurement/aws/s3/S3StorageClient.kt#L39)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> internal
> ```
not private? What else needs to access this?
</blockquote></details>

Ah, in an earlier version, `Blob` needed it but now it doesn't. Thanks, done.
___
*[src/main/kotlin/org/wfanet/measurement/aws/s3/S3StorageClient.kt, line 71 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/68#-Mq_YccE7xfyOa_uGBr4:-Mq_gs1Z2ebP4KK9V2wk:boy3o81) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/5567df4de81b38e890b0377f843fb2b1a310465b/src/main/kotlin/org/wfanet/measurement/aws/s3/S3StorageClient.kt#L71)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> md5.value
> ```
Won't this be a running MD5 of all of the content so far? Is that what this is supposed to be, or the MD5 of just that part?
</blockquote></details>

`digest` resets the `MessageDigest`: https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/security/MessageDigest.html#digest()
___
*[src/main/kotlin/org/wfanet/measurement/common/Bytes.kt, line 220 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/68#-Mq_beuz5Wk21-3R_S0g:-Mq_hp-x5vFlILNw5aqQ:b-oh7wt) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/5567df4de81b38e890b0377f843fb2b1a310465b/src/main/kotlin/org/wfanet/measurement/common/Bytes.kt#L220)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> ByteString.copyFrom(buffer)
> ```
Couldn't this result in the final ByteString having extra bytes if the buffer is too big? Likely need to specify the number of bytes actually read.
</blockquote></details>

Done, good catch

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/68)* status: all files reviewed, 3 unresolved discussions (waiting on @efoxepstein)

___
*[imports/java/software/amazon/awssdk/BUILD.bazel, line 4 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/68#-Mq_X_t51AZXy_Vr6OkX:-Mq_jnwZAHoiBycE4RKB:bdrytuc) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/5567df4de81b38e890b0377f843fb2b1a310465b/imports/java/software/amazon/awssdk/BUILD.bazel#L4)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

What do we do about the fact that it has `services.s3` and `services.s3.model`? (Also: moved to services)
</blockquote></details>

That's fine, as `model` is a subpackage.
___
*[imports/java/software/amazon/awssdk/BUILD.bazel, line 4 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/68#-Mq_k_SZ4Il6OWCM9wKL:-Mq_k_SZ4Il6OWCM9wKM:b-eyb825) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/a34e33debceeda998fe4eb5aa89300a8f240dddd/imports/java/software/amazon/awssdk/BUILD.bazel#L4)):*
> ```Starlark
> 
> alias(
>     name = "sdk-core",
> ```

Similarly, it looks like the highest-level Java package this provides is `software.amazon.awssdk.core`. Therefore, the Bazel target should be `//imports/java/software/amazon/awssdk/core:core`.
___
*[imports/java/software/amazon/awssdk/services/BUILD.bazel, line 4 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/68#-Mq_kBSHD0t5wy-qeKnN:-Mq_kBSHD0t5wy-qeKnO:b4gc5ef) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/a34e33debceeda998fe4eb5aa89300a8f240dddd/imports/java/software/amazon/awssdk/services/BUILD.bazel#L4)):*
> ```
> "s3"
> ```
If the highest-level Java package this introduces is `s3`, then this should be still be one level deeper in an `s3` subpackage.

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/68)* status: 3 of 8 files reviewed, 3 unresolved discussions (waiting on @SanjayVas)

___
*[imports/java/software/amazon/awssdk/BUILD.bazel, line 4 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/68#-Mq_X_t51AZXy_Vr6OkX:-Mq_rNNeDQNCJyVY16Pb:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/5567df4de81b38e890b0377f843fb2b1a310465b/imports/java/software/amazon/awssdk/BUILD.bazel#L4)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

That's fine, as `model` is a subpackage.
</blockquote></details>

Done.
___
*[imports/java/software/amazon/awssdk/BUILD.bazel, line 4 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/68#-Mq_k_SZ4Il6OWCM9wKL:-Mq_riM7BjwEIFWwla5w:b-9lnnkq) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/a34e33debceeda998fe4eb5aa89300a8f240dddd/imports/java/software/amazon/awssdk/BUILD.bazel#L4)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Similarly, it looks like the highest-level Java package this provides is `software.amazon.awssdk.core`. Therefore, the Bazel target should be `//imports/java/software/amazon/awssdk/core:core`.
</blockquote></details>

Done. Fixed the `http` one too
___
*[imports/java/software/amazon/awssdk/services/BUILD.bazel, line 4 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/68#-Mq_kBSHD0t5wy-qeKnN:-Mq_rjoU1RfnnGHiVbRD:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/a34e33debceeda998fe4eb5aa89300a8f240dddd/imports/java/software/amazon/awssdk/services/BUILD.bazel#L4)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> "s3"
> ```
If the highest-level Java package this introduces is `s3`, then this should be still be one level deeper in an `s3` subpackage.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/68)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @efoxepstein)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 4 of 5 files at r3, 5 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/68)* status: 10 of 11 files reviewed, 2 unresolved discussions (waiting on @efoxepstein and @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/aws/s3/S3StorageClient.kt, line 41 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/68#-MqpwbNsCVgAp0hMaB3E:-MqpwbNsCVgAp0hMaB3F:bqrhfw2) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/6341e3a5e8cfc57bba7cc1a328de6fcd3fe7ce09/src/main/kotlin/org/wfanet/measurement/aws/s3/S3StorageClient.kt#L41)):*
> ```Kotlin
> 
> /** Amazon Web Services (AWS) S3 implementation of [StorageClient] for a single bucket. */
> class S3StorageClient(private val s3: S3Client, private val bucketName: String) : StorageClient {
> ```

todo to move this to common?
___
*[src/main/kotlin/org/wfanet/measurement/common/Bytes.kt, line 214 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/68#-MqpwVtq9G7p0UrtmlBl:-MqpwVtrE0gy2ssfb1FB:bfiqzay) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/6341e3a5e8cfc57bba7cc1a328de6fcd3fe7ce09/src/main/kotlin/org/wfanet/measurement/common/Bytes.kt#L214)):*
> ```Kotlin
>  * @param bufferSize size of all except last output ByteString (which may be smaller)
>  */
> fun InputStream.asFlow(bufferSize: Int): Flow<ByteString> =
> ```

todo to put this in common?

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/68)* status: 10 of 11 files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/aws/s3/S3StorageClient.kt, line 41 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/68#-MqpwbNsCVgAp0hMaB3E:-Mqpy9UM-0bdU34EK4hC:b-lbut5x) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/6341e3a5e8cfc57bba7cc1a328de6fcd3fe7ce09/src/main/kotlin/org/wfanet/measurement/aws/s3/S3StorageClient.kt#L41)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

todo to move this to common?
</blockquote></details>

What do you mean?
___
*[src/main/kotlin/org/wfanet/measurement/common/Bytes.kt, line 214 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/68#-MqpwVtq9G7p0UrtmlBl:-MqpyBu03U02TsdiaQ0Y:b-lbut5x) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/6341e3a5e8cfc57bba7cc1a328de6fcd3fe7ce09/src/main/kotlin/org/wfanet/measurement/common/Bytes.kt#L214)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

todo to put this in common?
</blockquote></details>

What do you mean?

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/68)* status: 10 of 11 files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/68)* status: all files reviewed, 3 unresolved discussions (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/measurement/aws/s3/S3StorageClient.kt, line 76 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/68#-MqqM2cz1aanwinGJ_7K:-MqqM2d-AuGw89iYd6zg:b-iid10y) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/6341e3a5e8cfc57bba7cc1a328de6fcd3fe7ce09/src/main/kotlin/org/wfanet/measurement/aws/s3/S3StorageClient.kt#L76)):*
> ```
> digest.update(bytes.asReadOnlyByteBuffer())
> ```
nit: loop over bytes.asReadOnlyByteBufferList() and call update on each. This prevents byte array copies in the event that the ByteString has been formed from concatenated ByteStrings. Technically I believe the current implementation of asBufferedFlow doesn't do this, but it could change.

Even better would be adding a method to Hashing.kt, as then you can access some internal helper functions that do exactly this for you.
___
*[src/main/kotlin/org/wfanet/measurement/common/Bytes.kt, line 217 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/68#-MqqHHmA2Tj_h-GOqD6y:-MqqHHmA2Tj_h-GOqD6z:b5lv85e) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/6341e3a5e8cfc57bba7cc1a328de6fcd3fe7ce09/src/main/kotlin/org/wfanet/measurement/common/Bytes.kt#L217)):*
> ```
> true
> ```
Maybe use `isActive` here? I believe `emit` will also handle coroutine cancellation, but I feel like it's good practice to use `while(isActive)` rather than `while(true)` within coroutines.
___
*[src/main/kotlin/org/wfanet/measurement/common/Bytes.kt, line 224 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/68#-MqqGLez1YtfiiLJROQb:-MqqGLez1YtfiiLJROQc:b4iepp4) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/6341e3a5e8cfc57bba7cc1a328de6fcd3fe7ce09/src/main/kotlin/org/wfanet/measurement/common/Bytes.kt#L224)):*
> ```
> withContext(Dispatchers.IO)
> ```
nit: From my reading of the `flowOn` documentation, this `onCompletion` operation should already execute in the IO Dispatcher.

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/68)* status: 9 of 11 files reviewed, all discussions resolved (waiting on @SanjayVas and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/aws/s3/S3StorageClient.kt, line 76 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/68#-MqqM2cz1aanwinGJ_7K:-MqqQUcK6TlsNcWegFj7:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/6341e3a5e8cfc57bba7cc1a328de6fcd3fe7ce09/src/main/kotlin/org/wfanet/measurement/aws/s3/S3StorageClient.kt#L76)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> digest.update(bytes.asReadOnlyByteBuffer())
> ```
nit: loop over bytes.asReadOnlyByteBufferList() and call update on each. This prevents byte array copies in the event that the ByteString has been formed from concatenated ByteStrings. Technically I believe the current implementation of asBufferedFlow doesn't do this, but it could change.

Even better would be adding a method to Hashing.kt, as then you can access some internal helper functions that do exactly this for you.
</blockquote></details>

Done

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/68)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Pull request merged**
