### PR TITLE
Use grpc-java from Maven.

### PR DESCRIPTION
**Pull request by SanjayVas**
@io_grpc_grpc_java is imported solely for java_grpc_library.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/117)

### CODE REVIEW

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 33 of 33 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/117)* status: all files reviewed, 1 unresolved discussion (waiting on @iverson52000 and @SanjayVas)

___
*[`build/com_github_grpc_grpc_kotlin/repo.bzl` line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/117#-N2CcoVK1eJBtPvNX1LL:-N2CcoVK1eJBtPvNX1LM:b-g5dia9) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/3c2a99d830247bedc9720491f517d1c586d5a197/build/com_github_grpc_grpc_kotlin/repo.bzl#L26)):*
> ```Starlark
>             name = "com_github_grpc_grpc_kotlin",
>             sha256 = "fe0b50b833ce2c6edfdf6e98f45e02c162b936f89de55768173936103b3b11ce",
>             strip_prefix = "grpc-kotlin-1.2.1",
> ```

are you not wanting to do this at the same time?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/117)* status: all files reviewed, 1 unresolved discussion (waiting on @iverson52000 and @stevenwarejones)

___
*[`build/com_github_grpc_grpc_kotlin/repo.bzl` line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/117#-N2CcoVK1eJBtPvNX1LL:-N2Cgv5p4Fbmb_CqcbV4:bqpuqav) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/3c2a99d830247bedc9720491f517d1c586d5a197/build/com_github_grpc_grpc_kotlin/repo.bzl#L26)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

are you not wanting to do this at the same time?
</blockquote></details>

I'm not certain what you mean by "this". 1.2.1 is the most recent grpc-kotlin version. The use of grpc-kotlin libraries from source is unfortunately hard-coded into the `kt_jvm_grpc_library` rule implementation, so these cannot be loaded from Maven.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 14 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/117)* status: all files reviewed, 1 unresolved discussion (waiting on @iverson52000 and @SanjayVas)

___
*[`build/com_github_grpc_grpc_kotlin/repo.bzl` line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/117#-N2CcoVK1eJBtPvNX1LL:-N2NZfmm8i_dYAzIdlbR:buxxn3d) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/3c2a99d830247bedc9720491f517d1c586d5a197/build/com_github_grpc_grpc_kotlin/repo.bzl#L26)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I'm not certain what you mean by "this". 1.2.1 is the most recent grpc-kotlin version. The use of grpc-kotlin libraries from source is unfortunately hard-coded into the `kt_jvm_grpc_library` rule implementation, so these cannot be loaded from Maven.
</blockquote></details>

can you add that as a comment?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/117)* status: all files reviewed, 1 unresolved discussion (waiting on @iverson52000 and @stevenwarejones)

___
*[`build/com_github_grpc_grpc_kotlin/repo.bzl` line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/117#-N2CcoVK1eJBtPvNX1LL:-N2Nzk585wWrktLBcDjH:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/3c2a99d830247bedc9720491f517d1c586d5a197/build/com_github_grpc_grpc_kotlin/repo.bzl#L26)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

can you add that as a comment?
</blockquote></details>

Done.

**Review by SanjayVas — COMMENTED** [review]
> Dismissed @stevenwarejones from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/117)* status: 35 of 46 files reviewed, all discussions resolved (waiting on @iverson52000 and @stevenwarejones)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 24 of 33 files at r1, 11 of 14 files at r2, 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/117)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @iverson52000)

**Pull request merged**
