### PR TITLE
Move self issued id tokens related code here from cross-media-measurent

### PR DESCRIPTION
**Pull request by tristanvuong2021**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/77)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/77)* status: all files reviewed, 10 unresolved discussions (waiting on @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/tink/JwtKeyHandle.kt, line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/77#-Mr4IMGq8e0AXH_d7dny:-Mr4IMGq8e0AXH_d7dnz:btn1lvh) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/b67537235f5d4ea03814bb9d62cbccf5f71d83e6/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/JwtKeyHandle.kt#L29)):*
> ```Kotlin
> import com.google.gson.JsonParser
> 
> class JwtTinkPublicKeyHandle internal constructor(private val keysetHandle: KeysetHandle) {
> ```

nit: I think just `PublicJwkHandle` since there's no corresponding interface in the parent package (referencing JWK instead of JWT since I believe each of these handles is to a JWK).



_Code quote:_
```Kotlin
JwtTink
```
___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/tink/JwtKeyHandle.kt, line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/77#-Mr4LH2c3jGZhIdi1n1y:-Mr4LH2c3jGZhIdi1n1z:b-2grchu) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/b67537235f5d4ea03814bb9d62cbccf5f71d83e6/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/JwtKeyHandle.kt#L33)):*
> ```Kotlin
> 
>   fun getJwkKey(): JsonObject {
>     val jwkKeyset =
> ```

nit: `jwkSet` or `jsonWebKeySet`



_Code quote:_
```Kotlin
jwkKeyset
```
___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/tink/JwtKeyHandle.kt, line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/77#-Mr4I4_rE50TZTLtk0oy:-Mr4I4_rE50TZTLtk0oz:bxcwchz) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/b67537235f5d4ea03814bb9d62cbccf5f71d83e6/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/JwtKeyHandle.kt#L42)):*
> ```Kotlin
> 
>   companion object {
>     fun createJwtPublicKeyHandle(jwkKey: JsonObject): JwtTinkPublicKeyHandle {
> ```

Isn't the K in JWK already "key"?



_Code quote:_
```Kotlin
jwkKey
```
___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/tink/JwtKeyHandle.kt, line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/77#-Mr4J3sJA-v3RnuqBOdJ:-Mr4J3sJA-v3RnuqBOdK:b-jjs87x) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/b67537235f5d4ea03814bb9d62cbccf5f71d83e6/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/JwtKeyHandle.kt#L42)):*
> ```Kotlin
> 
>   companion object {
>     fun createJwtPublicKeyHandle(jwkKey: JsonObject): JwtTinkPublicKeyHandle {
> ```

nit: `fromJwk` or `fromJsonWebKey` would be more consistent with other naming.



_Code quote:_
```Kotlin
createJwtPublicKeyHandle
```
___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/tink/JwtKeyHandle.kt, line 56 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/77#-Mr4KuzQ3lIJTU7rqkne:-Mr4KuzRBsvh7UxfEefs:bg5npen) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/b67537235f5d4ea03814bb9d62cbccf5f71d83e6/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/JwtKeyHandle.kt#L56)):*
> ```Kotlin
> 
> class JwtTinkPrivateKeyHandle constructor(private val keysetHandle: KeysetHandle) {
>   private val publicKey = JwtTinkPublicKeyHandle(keysetHandle.publicKeysetHandle)
> ```

To parallel our other key handles, this should just be public. Then you don't need to have the slightly misleading method to get the public JWK.



_Code quote:_
```Kotlin
private
```
___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/tink/JwtKeyHandle.kt, line 75 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/77#-Mr4JPTg05bMlWj9BMva:-Mr4JPTg05bMlWj9BMvb:b-cpwkpp) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/b67537235f5d4ea03814bb9d62cbccf5f71d83e6/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/JwtKeyHandle.kt#L75)):*
> ```Kotlin
> 
>     /** Generates a new RSA key pair. */
>     fun generateRSA(): JwtTinkPrivateKeyHandle {
> ```

Camel case naming rules dictate that this should be `Rsa`



_Code quote:_
```Kotlin
RSA
```
___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/tink/SelfIssuedIdTokens.kt, line 71 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/77#-Mr4LjM9EB3YTu3vseNg:-Mr4LjM9EB3YTu3vseNh:b88ybxy) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/b67537235f5d4ea03814bb9d62cbccf5f71d83e6/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/SelfIssuedIdTokens.kt#L71)):*
> ```Kotlin
>     val uri = URI.create(uriString)
> 
>     if (uri.scheme.equals("openid")) {
> ```

Use a precondition guard clause to reduce nesting.

```
require(uri.scheme.equals("openid")) { "Invalid scheme for Self-Issued OpenID Provider: ${uri.scheme}" }
```
___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/tink/SelfIssuedIdTokens.kt, line 90 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/77#-Mr4JxPF9loPJUOMthvk:-Mr4JxPF9loPJUOMthvl:b-z9orod) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/b67537235f5d4ea03814bb9d62cbccf5f71d83e6/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/SelfIssuedIdTokens.kt#L90)):*
> ```Kotlin
>           .addJsonObjectClaim("sub_jwk", jwkKey.toString())
> 
>       rawJwtBuilder.addStringClaim(STATE, queryParamMap[STATE])
> ```

Why are these not part of the chained call?
___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/tink/SelfIssuedIdTokens.kt, line 111 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/77#-Mr4NBaA0d7hQPvFYoB2:-Mr4NBaA0d7hQPvFYoB3:b-wexvf2) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/b67537235f5d4ea03814bb9d62cbccf5f71d83e6/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/SelfIssuedIdTokens.kt#L111)):*
> ```Kotlin
> 
>   private fun isQueryValid(queryParamMap: Map<String, String>): Boolean {
>     queryParamMap["scope"]?.contains("openid") ?: return false
> ```

I think this won't return false if the scope is not null but does not equal "openid".

You probably want something like
```
return queryParamMap.getOrDefault("response_type", "").equals("id_token") && queryMap.containsKey(STATE) // && ...
```



_Code quote:_
```Kotlin
queryParamMap["scope"]?.contains("openid") ?: return false
```
___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/tink/SelfIssuedIdTokens.kt, line 121 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/77#-Mr4MUjW9If0erKkj1Aw:-Mr4MUjW9If0erKkj1Ax:b-f17n3) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/b67537235f5d4ea03814bb9d62cbccf5f71d83e6/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/SelfIssuedIdTokens.kt#L121)):*
> ```Kotlin
>     val hash = hashSha256(ByteString.copyFromUtf8(jwtKey))
> 
>     return hash.toByteArray().base64UrlEncode()
> ```

Shouldn't need to convert ByteString to ByteArray for this. See https://github.com/world-federation-of-advertisers/common-jvm/blob/3985a3d3824f30473d8080a88a8c7a22f81a5c63/src/main/kotlin/org/wfanet/measurement/common/Base64.kt#L25



_Code quote:_
```Kotlin
.toByteArray()
```

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/77)* status: 1 of 3 files reviewed, 6 unresolved discussions (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/tink/SelfIssuedIdTokens.kt, line 71 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/77#-Mr4LjM9EB3YTu3vseNg:-Mr4bqFQ7ed-qgWHwjkm:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/3b7ce2eeb76b736b04de2dc2e1d097e97f9cbacd/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/SelfIssuedIdTokens.kt#L71)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use a precondition guard clause to reduce nesting.

```
require(uri.scheme.equals("openid")) { "Invalid scheme for Self-Issued OpenID Provider: ${uri.scheme}" }
```
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/tink/SelfIssuedIdTokens.kt, line 90 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/77#-Mr4JxPF9loPJUOMthvk:-Mr4bqWo2frOgYqzTWwd:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/3b7ce2eeb76b736b04de2dc2e1d097e97f9cbacd/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/SelfIssuedIdTokens.kt#L90)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why are these not part of the chained call?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/tink/SelfIssuedIdTokens.kt, line 111 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/77#-Mr4NBaA0d7hQPvFYoB2:-Mr4bqkl9y9WezQmwvya:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/3b7ce2eeb76b736b04de2dc2e1d097e97f9cbacd/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/SelfIssuedIdTokens.kt#L111)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I think this won't return false if the scope is not null but does not equal "openid".

You probably want something like
```
return queryParamMap.getOrDefault("response_type", "").equals("id_token") && queryMap.containsKey(STATE) // && ...
```
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/tink/SelfIssuedIdTokens.kt, line 121 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/77#-Mr4MUjW9If0erKkj1Aw:-Mr4br5J6zLxXsx_8RSx:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/3b7ce2eeb76b736b04de2dc2e1d097e97f9cbacd/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/SelfIssuedIdTokens.kt#L121)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Shouldn't need to convert ByteString to ByteArray for this. See https://github.com/world-federation-of-advertisers/common-jvm/blob/3985a3d3824f30473d8080a88a8c7a22f81a5c63/src/main/kotlin/org/wfanet/measurement/common/Base64.kt#L25
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/tink/JwtKeyHandle.kt, line 56 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/77#-Mr4KuzQ3lIJTU7rqkne:-Mr4bpHm3g90XGVp3Chn:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/3b7ce2eeb76b736b04de2dc2e1d097e97f9cbacd/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/JwtKeyHandle.kt#L56)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

To parallel our other key handles, this should just be public. Then you don't need to have the slightly misleading method to get the public JWK.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/tink/JwtKeyHandle.kt, line 75 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/77#-Mr4JPTg05bMlWj9BMva:-Mr4bprX0RxfCt6CmgIi:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/3b7ce2eeb76b736b04de2dc2e1d097e97f9cbacd/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/JwtKeyHandle.kt#L75)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Camel case naming rules dictate that this should be `Rsa`
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/77)* status: all files reviewed, 9 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/tink/SelfIssuedIdTokens.kt, line 90 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/77#-Mr4JxPF9loPJUOMthvk:-MrTSRZ9657xql9ESrMn:b-nikuy7) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/3b7ce2eeb76b736b04de2dc2e1d097e97f9cbacd/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/SelfIssuedIdTokens.kt#L90)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

There's no need to keep the builder addressible. Just 

```
val token = RawJwt.newBuilder().setXXX(xxx).setYYY(yyy).build()
```
___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/tink/SelfIssuedIdTokens.kt, line 16 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/77#-MrTOxHK5qVE22_Vqo49:-MrTOxHK5qVE22_Vqo4A:b-355iyz) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1aaf7e9e5e43670e13fefde6f492878a6328ba15/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/SelfIssuedIdTokens.kt#L16)):*
> ```Kotlin
> 
> /*
>  * Contains methods for working with self-issued id tokens.
> ```

nit: ID



_Code quote:_
```Kotlin
id
```
___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/tink/SelfIssuedIdTokens.kt, line 33 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/77#-MrTO4SQ9GaPK9cIPXcp:-MrTO4SQ9GaPK9cIPXcq:b-t3fb8l) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1aaf7e9e5e43670e13fefde6f492878a6328ba15/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/SelfIssuedIdTokens.kt#L33)):*
> ```Kotlin
> import org.wfanet.measurement.common.crypto.hashSha256
> 
> private const val EXP_TIME = 5000L
> ```

Use a more explicit name, including a time unit.

e.g. `EXPIRATION_SECONDS`.



_Code quote:_
```Kotlin
EXP_TIME
```
___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/tink/SelfIssuedIdTokens.kt, line 37 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/77#-MrTPOzJ7sULlzL7VTkj:-MrTPOzJ7sULlzL7VTkk:b4w77mi) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1aaf7e9e5e43670e13fefde6f492878a6328ba15/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/SelfIssuedIdTokens.kt#L37)):*
> ```Kotlin
> object SelfIssuedIdTokens {
>   private val HEADER: String
>   private const val STATE = "state"
> ```

nit: prefer putting const declarations before non-const ones
___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/tink/SelfIssuedIdTokens.kt, line 41 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/77#-MrTPC2U81AZdJ0qaIf_:-MrTPC2U81AZdJ0qaIfa:b-n5lu5l) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1aaf7e9e5e43670e13fefde6f492878a6328ba15/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/SelfIssuedIdTokens.kt#L41)):*
> ```Kotlin
>   private const val SELF_ISSUED_ISSUER = "https://self-issued.me"
> 
>   init {
> ```

nit: prefer putting the `init` block immediately following the declaration of the property it's initializing.

Note that in this case, you don't technically need an `init` block at all.

```
private val HEADER: String = JsonObject().apply {
  addProperty("typ", "JWT")
  addProperty("alg", "RS256")
}.toString()
```
___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/tink/SelfIssuedIdTokens.kt, line 67 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/77#-MrTOQIQ8Y_ldCq4bh54:-MrTOQIQ8Y_ldCq4bh55:b-qoe8vn) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1aaf7e9e5e43670e13fefde6f492878a6328ba15/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/SelfIssuedIdTokens.kt#L67)):*
> ```Kotlin
>     val uri = URI.create(uriString)
> 
>     require(uri.scheme.equals("openid")) {
> ```

nit: extract constant , e.g. `SELF_ISSUED_SCHEME` 



_Code quote:_
```Kotlin
"openid"
```
___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/tink/SelfIssuedIdTokens.kt, line 113 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/77#-MrTT0gU-BfqbL-ycMcT:-MrTT0gU-BfqbL-ycMcU:b-ch6fnm) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1aaf7e9e5e43670e13fefde6f492878a6328ba15/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/SelfIssuedIdTokens.kt#L113)):*
> ```Kotlin
> 
>   fun calculateRsaThumbprint(jwk: String): String {
>     val hash = hashSha256(ByteString.copyFromUtf8(jwk))
> ```

nit: `jwk.toByteStringUtf8()` from `com.google.protobuf.kotlin`



_Code quote:_
```Kotlin
ByteString.copyFromUtf8(jwk)
```
___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/tink/JwkHandle.kt, line 63 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/77#-MrTNe545pBC7gpULDF1:-MrTNe551H2p5r3NtOWE:b-jmdoi0) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1aaf7e9e5e43670e13fefde6f492878a6328ba15/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/JwkHandle.kt#L63)):*
> ```Kotlin
>   }
> 
>   fun getJwk(): JsonObject {
> ```

This is misleading, as someone might think this returns the *private* key as a JWK. Just let the caller use `.public.getJwk()` themselves.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/77)* status: all files reviewed, 4 unresolved discussions (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/tink/SelfIssuedIdTokens.kt, line 90 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/77#-Mr4JxPF9loPJUOMthvk:-MrTb5Fo3SQ55P5rrXaI:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/3b7ce2eeb76b736b04de2dc2e1d097e97f9cbacd/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/SelfIssuedIdTokens.kt#L90)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

There's no need to keep the builder addressible. Just 

```
val token = RawJwt.newBuilder().setXXX(xxx).setYYY(yyy).build()
```
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/tink/SelfIssuedIdTokens.kt, line 33 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/77#-MrTO4SQ9GaPK9cIPXcp:-MrTb3-W59faibx6HoM1:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1aaf7e9e5e43670e13fefde6f492878a6328ba15/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/SelfIssuedIdTokens.kt#L33)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use a more explicit name, including a time unit.

e.g. `EXPIRATION_SECONDS`.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/tink/JwkHandle.kt, line 63 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/77#-MrTNe545pBC7gpULDF1:-MrTb1sj4uwAK-HXZt14:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1aaf7e9e5e43670e13fefde6f492878a6328ba15/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/JwkHandle.kt#L63)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is misleading, as someone might think this returns the *private* key as a JWK. Just let the caller use `.public.getJwk()` themselves.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/77)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/common/idtoken/RequestUri.kt, line 16 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/77#-MrTl0iR6G-AnSIUohee:-MrTl0iS8KnMSkgjmBCI:bry75ph) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/5e11d742d878004ca5663048c14f9718f47b15d4/src/main/kotlin/org/wfanet/measurement/common/idtoken/RequestUri.kt#L16)):*
> ```Kotlin
> 
> package org.wfanet.measurement.common.idtoken
> ```

nit: maybe `openid` or `oidc` for the package name?



_Code quote:_
```Kotlin
idtoken
```

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 2 of 6 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/77)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/common/openid/RequestUri.kt, line 23 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/77#-Mrc1GG-5_tfoLWWzNLr:-Mrc1GG-5_tfoLWWzNLs:bbc34td) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/2e8dc1716278a1b3a2b110f85c3088237a09e1e5/src/main/kotlin/org/wfanet/measurement/common/openid/RequestUri.kt#L23)):*
> ```Kotlin
> fun createRequestUri(state: Long, nonce: Long, redirectUri: String, isSelfIssued: Boolean): String {
>   val uriParts = mutableListOf<String>()
>   uriParts.add("openid://?response_type=id_token")
> ```

can we combine this with the other url builders?

**Comment by tristanvuong2021** [comment]
___
*[src/main/kotlin/org/wfanet/measurement/common/openid/RequestUri.kt, line 23 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/77#-Mrc1GG-5_tfoLWWzNLr:-Mrc63CXA3euTqeWcr7a:b-t84smz) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/2e8dc1716278a1b3a2b110f85c3088237a09e1e5/src/main/kotlin/org/wfanet/measurement/common/openid/RequestUri.kt#L23)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

can we combine this with the other url builders?
</blockquote></details>

This is going to replace all the other similar code I use in cross-media-measurement.

**Pull request merged**
