### PR TITLE
Add InternalId/ExternalId overloads for Spanner value binding.

### PR DESCRIPTION
**Pull request by SanjayVas**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/33)

### CODE REVIEW

**Review by efoxepstein — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/33)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/gcloud/spanner/Mutations.kt, line 15 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/33#-Mj5NmAJ4izebCIAUpoR:-Mj5NmAKDlLoKd9q6oA2:bw03lhb) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/6654644a528e1ed089368d90dd6d08ce80d1ccb3/src/main/kotlin/org/wfanet/measurement/gcloud/spanner/Mutations.kt#L15)):*
> ```
> measurement
> ```

Super unrelated question: should we migrate common-jvm stuff into `org.wfanet.common` package instead of `measurement`?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/33)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/measurement/gcloud/spanner/Mutations.kt, line 15 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/33#-Mj5NmAJ4izebCIAUpoR:-Mj5YDrA-4MJwKRVi_gs:b29niey) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/6654644a528e1ed089368d90dd6d08ce80d1ccb3/src/main/kotlin/org/wfanet/measurement/gcloud/spanner/Mutations.kt#L15)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

> ```
> measurement
> ```

Super unrelated question: should we migrate common-jvm stuff into `org.wfanet.common` package instead of `measurement`?
</blockquote></details>

Yes, though actually using our new Halo domain rather than org.wfanet. So far I've been using the "measurement" package to mean "Halo", but we've been inconsistent (some of our repos use a separate sibling package to `measurement`).

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/33)* status: all files reviewed, 1 unresolved discussion (waiting on @corbantek, @efoxepstein, @SanjayVas, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/gcloud/spanner/Mutations.kt, line 15 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/33#-Mj5NmAJ4izebCIAUpoR:-Mj5cst25iv_qxyMLCr3:bmi8v7p) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/6654644a528e1ed089368d90dd6d08ce80d1ccb3/src/main/kotlin/org/wfanet/measurement/gcloud/spanner/Mutations.kt#L15)):*
> using our new Halo domain

do we have one yet?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/33)* status: all files reviewed, 1 unresolved discussion (waiting on @corbantek, @efoxepstein, @oliver-amzn, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/gcloud/spanner/Mutations.kt, line 15 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/33#-Mj5NmAJ4izebCIAUpoR:-Mj5ibPw36BvQY2l-1IQ:b-rzqpzo) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/6654644a528e1ed089368d90dd6d08ce80d1ccb3/src/main/kotlin/org/wfanet/measurement/gcloud/spanner/Mutations.kt#L15)):*
<details><summary><i>Previously, oliver-amzn (Oliver) wrote…</i></summary><blockquote>

> using our new Halo domain

do we have one yet? 
</blockquote></details>

Matt @ WFA got one and there were claims of an email with the info, but I haven't seen it.

**Pull request merged**
