### PR TITLE
Remove runBlocking usage in Spanner AsyncDatabaseClient

### PR DESCRIPTION
**Pull request by SanjayVas**
Reverts #155 by re-applying #150 with fixes.

This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/154)

### CODE REVIEW

**Comment by SanjayVas** [comment]
Thanks @renjiezh for catching this.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/154)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/storage/filesystem/FileSystemStorageServer.kt` line 54 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/154#-N9fvol52jrJamQ2_7tb:-N9fvol52jrJamQ2_7tc:b-bdmo0f) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/792f4d61eee78b3f7d3c54f78b4ad21c135cfd42/src/main/kotlin/org/wfanet/measurement/storage/filesystem/FileSystemStorageServer.kt#L54)):*
> ```Kotlin
>       serverFlags,
>       SERVER_NAME,
>       FileSystemStorageService(directory, Dispatchers.IO + CoroutineName("file-system-io"))
> ```

what are best practices around coroutine names?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/154)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/storage/filesystem/FileSystemStorageServer.kt` line 54 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/154#-N9fvol52jrJamQ2_7tb:-N9gfu2E3DE5CvMATB2m:b-ckl6xd) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/792f4d61eee78b3f7d3c54f78b4ad21c135cfd42/src/main/kotlin/org/wfanet/measurement/storage/filesystem/FileSystemStorageServer.kt#L54)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

what are best practices around coroutine names?
</blockquote></details>

I actually spent some time trying to figure that out. I couldn't find anything discussing how to name these. Looking at Google's codebase, I saw a complete mix of patterns including phrases with spaces.

My understanding is that this is for debugging only and nothing should be trying to e.g. parse these. It just helps show information about what coroutine had an exception, etc.

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/154)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Comment by SanjayVas** [comment]
Re-requested review as I made some changes to deal with the fact that the integration test still wasn't passing. It turns out that Spanner Emulator only supports one read-write transaction at a time.

**Comment by SanjayVas** [comment]
CC @tristanvuong2021 since we were discussing this

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 11 of 13 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/154)* status: 10 of 13 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/common/Futures.kt` line 74 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/154#-NAF3Yp56nE2XlfyjS0S:-NAF3Yp56nE2XlfyjS0T:b-aboqo5) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/f267975c740483e56d4ad65646c23f91cffedced/src/main/kotlin/org/wfanet/measurement/gcloud/common/Futures.kt#L74)):*
> ```Kotlin
>   block: suspend CoroutineScope.() -> T
> ): ApiFuture<T> {
>   // Despite this being marked as an internal API, this should be safe due to the fact that we're
> ```

i thought one of the points of using ApiFuture is so that guava can be shaded? What other options do we have here other than using an internal API?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/154)* status: 10 of 13 files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/common/Futures.kt` line 74 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/154#-NAF3Yp56nE2XlfyjS0S:-NAF_OWAAWoKzf2WL0rX:b-5g23xl) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/f267975c740483e56d4ad65646c23f91cffedced/src/main/kotlin/org/wfanet/measurement/gcloud/common/Futures.kt#L74)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i thought one of the points of using ApiFuture is so that guava can be shaded? What other options do we have here other than using an internal API?
</blockquote></details>

My understanding is that it is so Guava *could* be shaded such that you can use a different version of Guava elsewhere in your application. The Google Cloud Java library ended up dropping any attempt to create their own own artifact with Guava shaded[^1]. Therefore if would be up to us to do any shading if we needed to, which we currently don't and should try to avoid regardless.

[^1]: https://github.com/googleapis/google-cloud-java/issues/1573

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/154)* status: 10 of 13 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/common/Futures.kt` line 74 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/154#-NAF3Yp56nE2XlfyjS0S:-NAFjUa_08HtYSHKn8o2:b9d3ki4) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/f267975c740483e56d4ad65646c23f91cffedced/src/main/kotlin/org/wfanet/measurement/gcloud/common/Futures.kt#L74)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

My understanding is that it is so Guava *could* be shaded such that you can use a different version of Guava elsewhere in your application. The Google Cloud Java library ended up dropping any attempt to create their own own artifact with Guava shaded[^1]. Therefore if would be up to us to do any shading if we needed to, which we currently don't and should try to avoid regardless.

[^1]: https://github.com/googleapis/google-cloud-java/issues/1573
</blockquote></details>

Just for completeness, the other options include:

1. Writing our own `ApiFuture` wrapper for `ListenableFuture`.
2. Writing our own version of the `CoroutineScope.future` method that works on `ApiFuture`. This would basically be copying that code directly and tweaking the type names.

Turns out (1) might be trivial, so I'll do that.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/154)* status: 10 of 13 files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/common/Futures.kt` line 74 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/154#-NAF3Yp56nE2XlfyjS0S:-NAFq2XeAM9FOdV_3Vyp:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/f267975c740483e56d4ad65646c23f91cffedced/src/main/kotlin/org/wfanet/measurement/gcloud/common/Futures.kt#L74)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Just for completeness, the other options include:

1. Writing our own `ApiFuture` wrapper for `ListenableFuture`.
2. Writing our own version of the `CoroutineScope.future` method that works on `ApiFuture`. This would basically be copying that code directly and tweaking the type names.

Turns out (1) might be trivial, so I'll do that.
</blockquote></details>

Done.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 13 files at r2, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/154)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
