### PR TITLE
Parse a more diverse set of key identifiers from ASN1

### PR DESCRIPTION
**Pull request by stevenwarejones**
The current implementation for parsing key identifiers from ASN1 does not correctly parse our SKI or AKI. I have added new logic that naively parses a 20 octet length key identifier and added new tests.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/101)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/101)* status: all files reviewed, 4 unresolved discussions (waiting on @chipingyeh and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/SecurityProvider.kt, line 39 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/101#-N-9jDKLBWNtCkzBr7Ew:-N-9jDKLBWNtCkzBr7Ex:b-7raoox) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/35823e9347622938244f8e8f3916cbfd8fc464d5/src/main/kotlin/org/wfanet/measurement/common/crypto/SecurityProvider.kt#L39)):*
> ```Kotlin
> 
> /** All Ski and Aki must have length 20. */
> private const val OID_KEY_LENGTH: Int = 20
> ```

Is this the length of the OID key, or the size of the key identifier in bytes?



_Code quote:_
```Kotlin
OID_KEY_LENGTH
```
___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/SecurityProvider.kt, line 119 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/101#-N-9_YWY5WDg4JjPB51V:-N-9_YWY5WDg4JjPB51W:b8jxv2i) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/35823e9347622938244f8e8f3916cbfd8fc464d5/src/main/kotlin/org/wfanet/measurement/common/crypto/SecurityProvider.kt#L119)):*
> ```Kotlin
>  * a 20 octet identifier, it returns null.
>  */
> fun X509Certificate.parseExtensionValue(oid: String): ByteString? {
> ```

This is specific to parsing key identifiers from AKI or SKI extensions, so probably should have a less generic name.



_Code quote:_
```Kotlin
parseExtensionValue
```
___
*[src/test/kotlin/org/wfanet/measurement/common/crypto/SecurityProviderTest.kt, line 149 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/101#-N-9jaYMBdcqc9KMAEuo:-N-9jaYMBdcqc9KMAEup:bufgchw) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/35823e9347622938244f8e8f3916cbfd8fc464d5/src/test/kotlin/org/wfanet/measurement/common/crypto/SecurityProviderTest.kt#L149)):*
> ```Kotlin
> 
>   @Test
>   fun `subjectKeyIdentifier returns SKID of issuer for client certificate`() {
> ```

The AKID is the SKID of the issuer. This test looks like it's just comparing against an expected SKID constant for a different cert.



_Code quote:_
```Kotlin
of issuer
```
___
*[src/test/kotlin/org/wfanet/measurement/common/crypto/SecurityProviderTest.kt, line 156 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/101#-N-9joji9-wNRxQq6NAO:-N-9joji9-wNRxQq6NAP:b7b4rd1) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/35823e9347622938244f8e8f3916cbfd8fc464d5/src/test/kotlin/org/wfanet/measurement/common/crypto/SecurityProviderTest.kt#L156)):*
> ```Kotlin
> 
>   @Test
>   fun `authorityKeyIdentifier returns AKID of issuer for client certificate`() {
> ```

Same here. This looks like it's just comparing against an expected AKID constant, rather than comparing to the SKID that's read from the issuer cert. That's fine, as long as the function name matches what the test is doing.



_Code quote:_
```Kotlin
 of issuer
```

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/101)* status: all files reviewed, 4 unresolved discussions (waiting on @chipingyeh and @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/SecurityProvider.kt, line 39 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/101#-N-9jDKLBWNtCkzBr7Ew:-N-Ov7po1Suaglb40but:b-2y4lo5) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/35823e9347622938244f8e8f3916cbfd8fc464d5/src/main/kotlin/org/wfanet/measurement/common/crypto/SecurityProvider.kt#L39)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Is this the length of the OID key, or the size of the key identifier in bytes?
</blockquote></details>

how about KEY_IDENTIFIER_LENGTH?



_Code quote:_
```Kotlin
OID_KEY_LENGTH
```
___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/SecurityProvider.kt, line 119 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/101#-N-9_YWY5WDg4JjPB51V:-N-OvEJn5HLXWb5WunWT:bhb082f) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/35823e9347622938244f8e8f3916cbfd8fc464d5/src/main/kotlin/org/wfanet/measurement/common/crypto/SecurityProvider.kt#L119)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is specific to parsing key identifiers from AKI or SKI extensions, so probably should have a less generic name.
</blockquote></details>

parseKeyIdentifierExtensionValue okay?



_Code quote:_
```Kotlin
parseExtensionValue
```
___
*[src/test/kotlin/org/wfanet/measurement/common/crypto/SecurityProviderTest.kt, line 149 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/101#-N-9jaYMBdcqc9KMAEuo:-N-OvNRW5o2OP7zIL7KW:btt3734) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/35823e9347622938244f8e8f3916cbfd8fc464d5/src/test/kotlin/org/wfanet/measurement/common/crypto/SecurityProviderTest.kt#L149)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The AKID is the SKID of the issuer. This test looks like it's just comparing against an expected SKID constant for a different cert.
</blockquote></details>

`subjectKeyIdentifier returns correct SKID of certificate` ?
___
*[src/test/kotlin/org/wfanet/measurement/common/crypto/SecurityProviderTest.kt, line 156 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/101#-N-9joji9-wNRxQq6NAO:-N-OvTuD1PNShHi8nPnQ:b-52xwdz) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/35823e9347622938244f8e8f3916cbfd8fc464d5/src/test/kotlin/org/wfanet/measurement/common/crypto/SecurityProviderTest.kt#L156)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Same here. This looks like it's just comparing against an expected AKID constant, rather than comparing to the SKID that's read from the issuer cert. That's fine, as long as the function name matches what the test is doing.
</blockquote></details>

`authorityKeyIdentifier returns correct AKID of certificate` ?

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/101)* status: all files reviewed, 2 unresolved discussions (waiting on @chipingyeh and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/SecurityProvider.kt, line 119 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/101#-N-9_YWY5WDg4JjPB51V:-N-P30vd2raDMcmnxb-s:b-i8ma0z) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/35823e9347622938244f8e8f3916cbfd8fc464d5/src/main/kotlin/org/wfanet/measurement/common/crypto/SecurityProvider.kt#L119)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

parseKeyIdentifierExtensionValue okay?
</blockquote></details>

Maybe `extractExtensionKeyIdentifier` and rename the parameter to `extensionOid`?
___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/SecurityProvider.kt, line 115 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/101#-N-P3Xkz5f8s9GWn3KBl:-N-P3Xkz5f8s9GWn3KBm:b87sb82) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/d057474f5ce6c7114f128597f330289ddf1503e8/src/main/kotlin/org/wfanet/measurement/common/crypto/SecurityProvider.kt#L115)):*
> ```Kotlin
> 
> /**
>  * This function naively parses ANS1 for a Key Identifier of length 20. It assumes that the Key
> ```

Follow style guide for KDoc blocks: https://developer.android.com/kotlin/style-guide#documentation

Specifically, have a summary fragment followed optionally by separate paragraphs of additional detail. e.g.

```
Extracts a key identifier from an extension.

This assumes that the key identifier starts at byte index [KEY_IDENTIFIER_START_INDEX] of the extension and is [KEY_IDENTIFIER_LENGTH] bytes long.
```

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/101)* status: all files reviewed, 3 unresolved discussions (waiting on @chipingyeh and @stevenwarejones)

___
*[src/test/kotlin/org/wfanet/measurement/common/crypto/SecurityProviderTest.kt, line 149 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/101#-N-9jaYMBdcqc9KMAEuo:-N-P5DleBg5EQlKlq5q2:b-c2obdf) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/35823e9347622938244f8e8f3916cbfd8fc464d5/src/test/kotlin/org/wfanet/measurement/common/crypto/SecurityProviderTest.kt#L149)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

`subjectKeyIdentifier returns correct SKID of certificate` ?
</blockquote></details>

This test and the other that tests the same thing (`subjectKeyIdentifier returns SKID`) should have similar names, but indicate exactly how they differ.



_Code quote:_
```Kotlin
subjectKeyIdentifier returns SKID
```

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/101)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @chipingyeh and @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/SecurityProvider.kt, line 115 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/101#-N-P3Xkz5f8s9GWn3KBl:-N-P7qnr2p2TWsTFojtx:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/d057474f5ce6c7114f128597f330289ddf1503e8/src/main/kotlin/org/wfanet/measurement/common/crypto/SecurityProvider.kt#L115)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Follow style guide for KDoc blocks: https://developer.android.com/kotlin/style-guide#documentation

Specifically, have a summary fragment followed optionally by separate paragraphs of additional detail. e.g.

```
Extracts a key identifier from an extension.

This assumes that the key identifier starts at byte index [KEY_IDENTIFIER_START_INDEX] of the extension and is [KEY_IDENTIFIER_LENGTH] bytes long.
```
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/measurement/common/crypto/SecurityProviderTest.kt, line 149 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/101#-N-9jaYMBdcqc9KMAEuo:-N-P7V_C2i_lv_gSg_7m:b-kxm45c) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/35823e9347622938244f8e8f3916cbfd8fc464d5/src/test/kotlin/org/wfanet/measurement/common/crypto/SecurityProviderTest.kt#L149)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This test and the other that tests the same thing (`subjectKeyIdentifier returns SKID`) should have similar names, but indicate exactly how they differ.
</blockquote></details>

suffixed with `with another format`. lmk what you think

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/101)* status: all files reviewed, 1 unresolved discussion (waiting on @chipingyeh and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/SecurityProvider.kt, line 117 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/101#-N-P9HI3BMHM7F67ScvW:-N-P9HI3BMHM7F67ScvX:buttsun) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/22ad733d8d24e2328fe3d6e1caeabcdd8c6483a3/src/main/kotlin/org/wfanet/measurement/common/crypto/SecurityProvider.kt#L117)):*
> ```Kotlin
>  * Extracts a key identifier from an extension.
>  *
>  * Assumes that the key identifier starts at byte index [KEY_IDENTIFIER_START_INDEX] of the
> ```

This constant doesn't exist yet.

The fact that both constants would have the same value is coincidence.



_Code quote:_
```Kotlin
KEY_IDENTIFIER_START_INDEX
```

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/101)* status: all files reviewed, 1 unresolved discussion (waiting on @chipingyeh and @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/SecurityProvider.kt, line 117 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/101#-N-P9HI3BMHM7F67ScvW:-N-PBTUhCLfir7Apn0Y0:b-q2sito) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/b61cf539caa9071d647d3d683a5113bdaa0abbca/src/main/kotlin/org/wfanet/measurement/common/crypto/SecurityProvider.kt#L117)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This constant doesn't exist yet.

The fact that both constants would have the same value is coincidence.
</blockquote></details>

I don't think its coincidence. The start index I'm using specifies the length of the key identifier. At least that's how I read the spec.

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/101)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @chipingyeh and @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/SecurityProvider.kt, line 117 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/101#-N-P9HI3BMHM7F67ScvW:-N-PC4cY0rMJvXpFSwZO:bctf2wl) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/b61cf539caa9071d647d3d683a5113bdaa0abbca/src/main/kotlin/org/wfanet/measurement/common/crypto/SecurityProvider.kt#L117)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I don't think its coincidence. The start index I'm using specifies the length of the key identifier. At least that's how I read the spec.
</blockquote></details>

how I read the spec was that it was not coincidence. For variable length key identifers, the octet preceding the key identifier is the length of the key identifier.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/101)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @chipingyeh, @SanjayVas, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/SecurityProvider.kt, line 117 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/101#-N-P9HI3BMHM7F67ScvW:-N-PC4JE-qLZBScPsn1g:b-4ghrq1) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/b61cf539caa9071d647d3d683a5113bdaa0abbca/src/main/kotlin/org/wfanet/measurement/common/crypto/SecurityProvider.kt#L117)):*
> For variable length key identifers, the octet preceding the key identifier is the length of the key identifier.

The spec says that the octet (i.e. the byte) preceding the key identifier contains the length of the identifier. That statement has nothing to do with what index that size octet nor the key identifier are at within the byte array.

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/101)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @chipingyeh and @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/SecurityProvider.kt, line 117 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/101#-N-P9HI3BMHM7F67ScvW:-N-PI5kkAD6Nt8INAlMN:b-ncfu3a) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/b61cf539caa9071d647d3d683a5113bdaa0abbca/src/main/kotlin/org/wfanet/measurement/common/crypto/SecurityProvider.kt#L117)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> For variable length key identifers, the octet preceding the key identifier is the length of the key identifier.

The spec says that the octet (i.e. the byte) preceding the key identifier contains the length of the identifier. That statement has nothing to do with what index that size octet nor the key identifier are at within the byte array.
</blockquote></details>

correct. that's why the code naively looks for the index of that size octet.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/101)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chipingyeh)

**Review by stevenwarejones — COMMENTED** [review]
> Reviewed 2 of 4 files at r2, 1 of 2 files at r4, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/101)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chipingyeh)

**Pull request merged**
