### PR TITLE
Update TinkKeyId into an unique id as Long.

### PR DESCRIPTION
**Pull request by renjiezh**
Address issue #138

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/236)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/236)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/TinkKeyId.kt` line 39 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/236#-NsKYJHJBjNI5th0jrXc:-NsKYJHJBjNI5th0jrXd:undefined) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/d46c37388f3c029ec86c101666259021455daa17/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/TinkKeyId.kt#L39)):*
> ```Kotlin
>   val publicKeyData =
>     ByteString.newOutput().use {
>       publicKey.keysetHandle.write(CleartextKeysetWriter(it), CleartextAead())
> ```





_Suggestion:_
```Kotlin
writeNoSecret(CleartextKeysetWriter(it))
```
___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/TinkKeyId.kt` line 45 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/236#-NsKYQxq8kuFgvWG-qSw:-NsKYQxq8kuFgvWG-qSx:b-ahkp83) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/d46c37388f3c029ec86c101666259021455daa17/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/TinkKeyId.kt#L45)):*
> ```Kotlin
> }
> 
> internal class CleartextKeysetWriter(private val stream: OutputStream) : KeysetWriter {
> ```

This can be a private class that's internal to TinkKeyId



_Code quote:_
```Kotlin
internal
```
___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/TinkKeyId.kt` line 45 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/236#-NsKYYEC9L4I63JCmNpI:-NsKYYEC9L4I63JCmNpJ:b-wyf42a) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/d46c37388f3c029ec86c101666259021455daa17/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/TinkKeyId.kt#L45)):*
> ```Kotlin
> }
> 
> internal class CleartextKeysetWriter(private val stream: OutputStream) : KeysetWriter {
> ```

The name here implies it's writing the keyset in clear text. This is not actually what we want. We just happen to be implementing the KeysetWriter interface to get access to some internals.

This shouldn't actually write anything anywhere. It should instead populate some field. e.g.

```kotlin
private class KeyIdWriter : KeysetWriter {
  lateinit var keyId: Long
    private set

  override fun write(keyset: Keyset) {
    // Check precondition that keyId is not initialized ...

    // Compute and set keyId ...
  }
}
```



_Code quote:_
```Kotlin
CleartextKeysetWriter
```

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/236)* status: all files reviewed, 5 unresolved discussions (waiting on @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/TinkKeyId.kt` line 39 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/236#-NsKpHLf93gAl4TTdiVY:-NsKpHLf93gAl4TTdiVZ:bqtxo3p) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/4f68e21f8709324ca5977b2c73f214e4ca8a74c1/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/TinkKeyId.kt#L39)):*
> ```Kotlin
>     private set
> 
>   override fun write(keyset: Keyset?) {
> ```

This is only marked as nullable because Kotlin doesn't know about the nullability when the interface is defined in Java. You can explicitly indicate it's not nullable if it's an error to call it with null.



_Suggestion:_
```Kotlin
Keyset
```
___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/TinkKeyId.kt` line 43 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/236#-NsKpgKk-mwNUEa5wVgY:-NsKpgKlCmWQyT8nAX3s:bniddsq) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/4f68e21f8709324ca5977b2c73f214e4ca8a74c1/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/TinkKeyId.kt#L43)):*
> ```Kotlin
>     val primaryKey =
>       keyset.keyList.find { it.keyId == keyset.primaryKeyId }
>         ?: error("Primary key cannot be found.")
> ```

nit: this should technically be IllegalArgumentException rather than IllegalStateException. You can wrap the result of `find` in `requireNotNull` instead.



_Code quote:_
```Kotlin
error("Primary key cannot be found.")
```
___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/TinkKeyId.kt` line 46 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/236#-NsKq1xK13khqfqimBOE:-NsKq1xK13khqfqimBOF:b-l2wvz0) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/4f68e21f8709324ca5977b2c73f214e4ca8a74c1/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/TinkKeyId.kt#L46)):*
> ```Kotlin
>     val data =
>       ByteString.newOutput().use {
>         it.write(primaryKey.keyData.value.toByteArray())
> ```

Isn't this already a ByteString? Why convert to a ByteArray then write to a ByteString via OutputStream?



_Code quote:_
```Kotlin
primaryKey.keyData.value
```
___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/TinkKeyId.kt` line 49 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/236#-NsKqFQ9BdMCx5TrEaH9:-NsKqFQ9BdMCx5TrEaHA:b-21d988) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/4f68e21f8709324ca5977b2c73f214e4ca8a74c1/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/TinkKeyId.kt#L49)):*
> ```Kotlin
>         it.toByteString()
>       }
>     keyId = Hashing.hashSha256(data).substring(0, 8).toLong()
> ```

Use a 64-bit fingerprinter instead of truncating a 256-bit hash, e.g. Fingerprint64.
___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/TinkKeyId.kt` line 53 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/236#-NsKoquJA22fmfJBsPAE:-NsKoquJA22fmfJBsPAF:b-d5t6j5) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/4f68e21f8709324ca5977b2c73f214e4ca8a74c1/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/TinkKeyId.kt#L53)):*
> ```Kotlin
> 
>   override fun write(keyset: EncryptedKeyset?) {
>     // Supposed not to be used.
> ```

nit: throw `UnsupportedOperationException`

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/236)* status: all files reviewed, 6 unresolved discussions (waiting on @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/TinkKeyId.kt` line 1 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/236#-NsKqf7PA-PqdKOFnnTQ:-NsKqf7PA-PqdKOFnnTR:bs26g7d) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/4f68e21f8709324ca5977b2c73f214e4ca8a74c1/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/TinkKeyId.kt#L1)):*
> ```Kotlin
> // Copyright 2024 The Cross-Media Measurement Authors
> ```

Don't update copyright notices for existing files. The year is when the file was first created.

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/236)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/TinkKeyId.kt` line 1 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/236#-NsKqf7PA-PqdKOFnnTQ:-NsKrg0m0B5qBZ6RMlf7:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/4f68e21f8709324ca5977b2c73f214e4ca8a74c1/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/TinkKeyId.kt#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Don't update copyright notices for existing files. The year is when the file was first created.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/TinkKeyId.kt` line 39 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/236#-NsKpHLf93gAl4TTdiVY:-NsKr6_J7ojWFw7uQZ6G:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/4f68e21f8709324ca5977b2c73f214e4ca8a74c1/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/TinkKeyId.kt#L39)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is only marked as nullable because Kotlin doesn't know about the nullability when the interface is defined in Java. You can explicitly indicate it's not nullable if it's an error to call it with null.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/TinkKeyId.kt` line 46 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/236#-NsKq1xK13khqfqimBOE:-NsKyKJd9vRPieRG3DM1:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/4f68e21f8709324ca5977b2c73f214e4ca8a74c1/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/TinkKeyId.kt#L46)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Isn't this already a ByteString? Why convert to a ByteArray then write to a ByteString via OutputStream?
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/TinkKeyId.kt` line 49 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/236#-NsKqFQ9BdMCx5TrEaH9:-NsKzx5p44fxw6dY6548:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/4f68e21f8709324ca5977b2c73f214e4ca8a74c1/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/TinkKeyId.kt#L49)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use a 64-bit fingerprinter instead of truncating a 256-bit hash, e.g. Fingerprint64.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/236)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/236)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/TinkKeyId.kt` line 47 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/236#-NsTaalI8WKeP5_-jsDN:-NsTaalI8WKeP5_-jsDO:b-58qzky) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/8e9bd43687d96c715b51e4198a28c0a9bf685d2a/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/TinkKeyId.kt#L47)):*
> ```Kotlin
> 
>   override fun write(keyset: EncryptedKeyset) {
>     // Supposed not to be called.
> ```

nit: `Should not be called` - also not sure if that comment is even needed given the exception message is nearly identical

**Review by renjiezh — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/236)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Pull request merged**
