### PR TITLE
Update argument list of failGrpc() to include the cause of error

### PR DESCRIPTION
**Pull request by renjiezh**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/95)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/95)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @renjiezh and @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/common/grpc/Preconditions.kt, line 57 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/95#-MvuGxec5FgZaaERsTEf:-MvuGxec5FgZaaERsTEg:b1x1gz4) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/87e092eb286db69b1200cb025663dd9f2e2e6076/src/main/kotlin/org/wfanet/measurement/common/grpc/Preconditions.kt#L57)):*
> ```Kotlin
>   provideDescription: () -> String
> ): Nothing =
>   if (cause == null) {
> ```

When the body is just an if-else, that's a good indicator that you should have a separate overload rather than an optional parameter.

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/95)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/common/grpc/Preconditions.kt, line 57 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/95#-MvuGxec5FgZaaERsTEf:-MvuMQnD2FuywR8FxtGt:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/87e092eb286db69b1200cb025663dd9f2e2e6076/src/main/kotlin/org/wfanet/measurement/common/grpc/Preconditions.kt#L57)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

When the body is just an if-else, that's a good indicator that you should have a separate overload rather than an optional parameter.
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/95)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh)

___
*[src/test/kotlin/org/wfanet/measurement/common/grpc/PreconditionsTest.kt, line 26 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/95#-MvuNOSA6iJT1IxAIs_y:-MvuNOSA6iJT1IxAIs_z:b-vidsn9) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/387dff61074c37882bcf5aed46c329a10cbe58de/src/test/kotlin/org/wfanet/measurement/common/grpc/PreconditionsTest.kt#L26)):*
> ```Kotlin
>   @Test
>   fun `failGrpc without cause`() {
>     try {
> ```

This test will incorrectly pass in the event that the function doesn't throw an exception at all. Use assertFailsWith from kotlin.test.

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/95)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[src/test/kotlin/org/wfanet/measurement/common/grpc/PreconditionsTest.kt, line 26 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/95#-MvuNOSA6iJT1IxAIs_y:-MvuQe1e0MBnidhpR7ac:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/387dff61074c37882bcf5aed46c329a10cbe58de/src/test/kotlin/org/wfanet/measurement/common/grpc/PreconditionsTest.kt#L26)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This test will incorrectly pass in the event that the function doesn't throw an exception at all. Use assertFailsWith from kotlin.test.
</blockquote></details>

Done.

**Review by SanjayVas — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/95)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @renjiezh and @SanjayVas)

___
*[src/test/kotlin/org/wfanet/measurement/common/grpc/PreconditionsTest.kt, line 41 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/95#-MvuTaa5-3IzPs8v5Hq_:-MvuTaa6C64KsWDTnOqg:bktkmtp) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/8910f92be3b14f7523fcc4f70bf314e9d4df661d/src/test/kotlin/org/wfanet/measurement/common/grpc/PreconditionsTest.kt#L41)):*
> ```Kotlin
>     val exception =
>       assertFailsWith<StatusRuntimeException> {
>         failGrpc(Status.FAILED_PRECONDITION, StatusException(Status.INTERNAL)) {
> ```

nit: weird to have the cause be another status exception. Use something more common, like IllegalArgumentException.



_Code quote:_
```Kotlin
StatusException(Status.INTERNAL)
```

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/95)* status: all files reviewed, 2 unresolved discussions (waiting on @renjiezh)

___
*[src/test/kotlin/org/wfanet/measurement/common/grpc/PreconditionsTest.kt, line 33 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/95#-MwDAwHE1UXhn5RsoQcd:-MwDAwHE1UXhn5RsoQce:b-n2qjyl) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/d2685631e6b13d72f2abd5cd711c24173549291f/src/test/kotlin/org/wfanet/measurement/common/grpc/PreconditionsTest.kt#L33)):*
> ```Kotlin
>     assertThat(exception.status.code).isEqualTo(Status.Code.FAILED_PRECONDITION)
>     assertThat(exception.status.cause).isEqualTo(null)
>     assertThat(exception.status.description).isEqualTo("No cause")
> ```

`isNull()`



_Code quote:_
```Kotlin
isEqualTo(null)
```
___
*[src/test/kotlin/org/wfanet/measurement/common/grpc/PreconditionsTest.kt, line 46 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/95#-MwDARB79tNYsZIc9cVI:-MwDARB79tNYsZIc9cVJ:b-4e24fo) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/d2685631e6b13d72f2abd5cd711c24173549291f/src/test/kotlin/org/wfanet/measurement/common/grpc/PreconditionsTest.kt#L46)):*
> ```Kotlin
>       }
>     assertThat(exception.status.code).isEqualTo(Status.Code.FAILED_PRECONDITION)
>     assertThat(exception.status.cause.toString()).isEqualTo(IllegalArgumentException().toString())
> ```

Don't compare by string. I think what you're looking for is `isInstanceOf`.



_Code quote:_
```Kotlin
.toString()
```

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/95)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[src/test/kotlin/org/wfanet/measurement/common/grpc/PreconditionsTest.kt, line 33 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/95#-MwDAwHE1UXhn5RsoQcd:-MwDEXNT8MP0zIVvCGN7:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/d2685631e6b13d72f2abd5cd711c24173549291f/src/test/kotlin/org/wfanet/measurement/common/grpc/PreconditionsTest.kt#L33)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

`isNull()`
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/measurement/common/grpc/PreconditionsTest.kt, line 46 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/95#-MwDARB79tNYsZIc9cVI:-MwDEYAU36DzTR7IQ-EY:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/d2685631e6b13d72f2abd5cd711c24173549291f/src/test/kotlin/org/wfanet/measurement/common/grpc/PreconditionsTest.kt#L46)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Don't compare by string. I think what you're looking for is `isInstanceOf`.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/95)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Review by kungfucraig — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/95)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Pull request merged**
