### PR TITLE
Add health probe server for build-in Grpc probe

### PR DESCRIPTION
**Pull request by renjiezh**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/146)

Deprecate the [grpc-health-probe](https://github.com/grpc-ecosystem/grpc-health-probe/ ) and turn to the built-in Grpc probe.

`cross-media-measruement` needs to upgrade the k8s version to 1.24 to enable the feature. Deployment config needs to add `--probe-port=` arg for kingdom, duchy, and reporting server.

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/146)* status: all files reviewed, 2 unresolved discussions (waiting on @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/common/grpc/CommonServer.kt` line 38 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/146#-N8k3JaY1m1vI2zhMIOD:-N8k3JaY1m1vI2zhMIOE:bwkbype) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/c1f3186facb7eedb130b75d70e7940ac02ceb383/src/main/kotlin/org/wfanet/measurement/common/grpc/CommonServer.kt#L38)):*
> ```Kotlin
>   services: Iterable<ServerServiceDefinition>,
>   sslContext: SslContext?,
>   private val healthProbePort: Int = 0,
> ```

Drop "probe" from all of these and just refer to "health".

This is just a non-TLS server hosting the Health service. The fact that we use it for liveness/readiness probing isn't relevant here.



_Code quote:_
```Kotlin
Probe
```
___
*[`src/main/kotlin/org/wfanet/measurement/common/grpc/CommonServer.kt` line 114 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/146#-N8k3p8d9SQ0CzkDyaUW:-N8k3p8d9SQ0CzkDyaUX:b-eak6io) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/c1f3186facb7eedb130b75d70e7940ac02ceb383/src/main/kotlin/org/wfanet/measurement/common/grpc/CommonServer.kt#L114)):*
> ```Kotlin
>       names = ["--probe-port"],
>       description = ["TCP port for non-TLS health probe server."],
>       defaultValue = "8090"
> ```

nit: 8080, making the other default 8443. See note in other PR.



_Code quote:_
```Kotlin
8090
```

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/146)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/common/grpc/CommonServer.kt` line 38 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/146#-N8k3JaY1m1vI2zhMIOD:-N8yf0rB0kq_OnEUdE_w:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/c1f3186facb7eedb130b75d70e7940ac02ceb383/src/main/kotlin/org/wfanet/measurement/common/grpc/CommonServer.kt#L38)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Drop "probe" from all of these and just refer to "health".

This is just a non-TLS server hosting the Health service. The fact that we use it for liveness/readiness probing isn't relevant here.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/146)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/common/grpc/CommonServer.kt` line 94 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/146#-N8yfmbn3z-j5B7kCyM9:-N8yfmbn3z-j5B7kCyMA:b-smlwag) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/607dc2ce71c17c92b6884ebf8b1f34523a5de78b/src/main/kotlin/org/wfanet/measurement/common/grpc/CommonServer.kt#L94)):*
> ```Kotlin
>       names = ["--port", "-p"],
>       description = ["TCP port for gRPC server."],
>       defaultValue = "8043"
> ```

8443, not 8043

We're moving the default https port of 443 into non-root space by adding 8000.



_Code quote:_
```Kotlin
8043
```

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 4 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/146)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kungfucraig)

**Comment by SanjayVas** [comment]
This is for https://github.com/world-federation-of-advertisers/cross-media-measurement/issues/555

**Pull request merged**
