### PR TITLE
Add kt_jvm_proto_library BUILD rule.

### PR DESCRIPTION
**Pull request by efoxepstein**
This should eventually be owned by rules_kotlin (https://github.com/bazelbuild/rules_kotlin).

This initial PR contains some minor hacks that future PRs will address before attempting to move this over to rules_kotlin.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/26)

### CODE REVIEW

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/26)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/26#-MgrWfj_6Eufo238NygK:-MgrWfjaCyDiUoSbN2eF:bfafwsx) (no related file):*
TODO: add tests

---
*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/26#-MgrWglB0Ibi4NUZf3ig:-MgrWglB0Ibi4NUZf3ih:byxnpz1) (no related file):*
TODO: how does this interact with kt_jvm_grpc_library?

---

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/26)* status: all files reviewed, 8 unresolved discussions (waiting on @efoxepstein)

___
*[build/common_jvm_maven.bzl, line 71 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/26#-MgrW49HEx2fLRGK3ii3:-MgrW49HEx2fLRGK3ii4:bxpvtzi) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1eed9b06d8a959bc7e586342836c2dd4189ea2bb/build/common_jvm_maven.bzl#L71)):*
> ```Starlark
>         "com.squareup:kotlinpoet": "1.8.0",
> 
>         # For kt_jvm_proto_library.
> ```

Add a comment that this must match the version of `com_google_protobuf`.
___
*[build/kt_jvm_proto_library.bzl, line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/26#-MgrX9kW51B8WP5QRIkJ:-MgrX9kW51B8WP5QRIkK:b-9naf7p) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1eed9b06d8a959bc7e586342836c2dd4189ea2bb/build/kt_jvm_proto_library.bzl#L28)):*
> ```Starlark
>         short_path = short_path[second_slash + 1:]
> 
>     virtual_imports = "_virtual_imports/"
> ```

Does ProtoInfo.proto_source_root help at all with this, or is that something else? It just doesn't seem like we should be digging into virtual_imports.
___
*[build/kt_jvm_proto_library.bzl, line 70 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/26#-MgrXeaN2I0TctFlv9sW:-MgrXeaN2I0TctFlv9sX:bx7i3ac) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1eed9b06d8a959bc7e586342836c2dd4189ea2bb/build/kt_jvm_proto_library.bzl#L70)):*
> ```
> KtGrpcSrcJar
> ```
This isn't related to gRPC. Perhaps KtProtoSrcJar?
___
*[build/kt_jvm_proto_library.bzl, line 96 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/26#-MgrZHriDgtYCdaNrTGk:-MgrZHriDgtYCdaNrTGl:b-h5oewn) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1eed9b06d8a959bc7e586342836c2dd4189ea2bb/build/kt_jvm_proto_library.bzl#L96)):*
> ```Starlark
>             providers = [JavaInfo],  # This also shouldn't be needed
>         ),
>         proto_dep = attr.label(providers = [ProtoInfo]),
> ```

Did you check if the `java_proto_library` also provides ProtoInfo? If so, maybe we can drop the `proto_library` src.
___
*[build/kt_jvm_proto_library.bzl, line 163 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/26#-MgrYjvv2HM-0sYuVjLV:-MgrYjvv2HM-0sYuVjLW:bjbwmuo) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1eed9b06d8a959bc7e586342836c2dd4189ea2bb/build/kt_jvm_proto_library.bzl#L163)):*
> ```Starlark
>         name = generated_kt_name,
>         proto_dep = srcs[0],
>         deps = deps,
> ```

Can we hard-code this target to `visibility://private`?
___
*[build/kt_jvm_proto_library.bzl, line 176 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/26#-MgrY7kR7AehTeqGulCY:-MgrY7kR7AehTeqGulCZ:brr5vx8) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1eed9b06d8a959bc7e586342836c2dd4189ea2bb/build/kt_jvm_proto_library.bzl#L176)):*
> ```Starlark
>         restricted_to = restricted_to,
>         visibility = visibility,
>         flavor = flavor,
> ```

I don't think kt_jvm_library supports some of these attributes such as flavor.

Mayhaps just list the params that we actually use/check and pass the rest as `**kwargs` to kt_jvm_library?

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/26)* status: all files reviewed, 9 unresolved discussions (waiting on @efoxepstein)

___
*[build/kt_jvm_proto_library.bzl, line 176 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/26#-Mgr_VNr5b7WGzV3inJ7:-Mgr_VNr5b7WGzV3inJ8:b-uq6gkt) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1eed9b06d8a959bc7e586342836c2dd4189ea2bb/build/kt_jvm_proto_library.bzl#L176)):*
> ```Starlark
>         restricted_to = restricted_to,
>         visibility = visibility,
>         flavor = flavor,
> ```

This should export the java_proto_library via the `exports` attr so that anyone adding this as a dep doesn't need a separate dep on the java_proto_library in order to follow strict deps.

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/26)* status: all files reviewed, 9 unresolved discussions (waiting on @efoxepstein and @SanjayVas)

___
*[build/common_jvm_maven.bzl, line 71 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/26#-MgrW49HEx2fLRGK3ii3:-MgraFXW9l6pnfIt-hKI:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1eed9b06d8a959bc7e586342836c2dd4189ea2bb/build/common_jvm_maven.bzl#L71)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Add a comment that this must match the version of `com_google_protobuf`.
</blockquote></details>

Done.
___
*[build/kt_jvm_proto_library.bzl, line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/26#-MgrX9kW51B8WP5QRIkJ:-MgraJQp848-e9429AQ5:b63l6s0) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1eed9b06d8a959bc7e586342836c2dd4189ea2bb/build/kt_jvm_proto_library.bzl#L28)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Does ProtoInfo.proto_source_root help at all with this, or is that something else? It just doesn't seem like we should be digging into virtual_imports.
</blockquote></details>

Can I add a TODO for now?
___
*[build/kt_jvm_proto_library.bzl, line 70 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/26#-MgrXeaN2I0TctFlv9sW:-MgraVru5ytH2ogZM_yZ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1eed9b06d8a959bc7e586342836c2dd4189ea2bb/build/kt_jvm_proto_library.bzl#L70)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> KtGrpcSrcJar
> ```
This isn't related to gRPC. Perhaps KtProtoSrcJar?
</blockquote></details>

Done.
___
*[build/kt_jvm_proto_library.bzl, line 163 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/26#-MgrYjvv2HM-0sYuVjLV:-MgrbWbf5UlHgvL-3uza:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1eed9b06d8a959bc7e586342836c2dd4189ea2bb/build/kt_jvm_proto_library.bzl#L163)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Can we hard-code this target to `visibility://private`?
</blockquote></details>

Done.
___
*[build/kt_jvm_proto_library.bzl, line 176 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/26#-MgrY7kR7AehTeqGulCY:-Mgr_9w7-fJ1Uoqmxz7Q:b-cj11ao) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1eed9b06d8a959bc7e586342836c2dd4189ea2bb/build/kt_jvm_proto_library.bzl#L176)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I don't think kt_jvm_library supports some of these attributes such as flavor.

Mayhaps just list the params that we actually use/check and pass the rest as `**kwargs` to kt_jvm_library?
</blockquote></details>

This is for consistency with https://github.com/grpc/grpc-kotlin/blob/master/kt_jvm_grpc.bzl#L150 -- which I think the reviewers wanted us to add. Happy to remove, though, if you prefer.
___
*[build/kt_jvm_proto_library.bzl, line 176 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/26#-Mgr_VNr5b7WGzV3inJ7:-MgrbeJ60r-2-WEubZ3B:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1eed9b06d8a959bc7e586342836c2dd4189ea2bb/build/kt_jvm_proto_library.bzl#L176)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This should export the java_proto_library via the `exports` attr so that anyone adding this as a dep doesn't need a separate dep on the java_proto_library in order to follow strict deps.
</blockquote></details>

Done.

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/26)* status: 0 of 7 files reviewed, 9 unresolved discussions (waiting on @SanjayVas)

___
*[build/kt_jvm_proto_library.bzl, line 96 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/26#-MgrZHriDgtYCdaNrTGk:-MgreVUI1G8KhoQgrzFb:b-an9h43) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1eed9b06d8a959bc7e586342836c2dd4189ea2bb/build/kt_jvm_proto_library.bzl#L96)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Did you check if the `java_proto_library` also provides ProtoInfo? If so, maybe we can drop the `proto_library` src.
</blockquote></details>

Alas, it does not :(

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/26)* status: 1 of 7 files reviewed, 2 unresolved discussions (waiting on @efoxepstein, @oliver-amzn, @SanjayVas, and @stevenwarejones)

___
*[build/kt_jvm_proto_library.bzl, line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/26#-MgrX9kW51B8WP5QRIkJ:-MgvK6PL9HcUfC0H_ofg:b-80tlqk) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1eed9b06d8a959bc7e586342836c2dd4189ea2bb/build/kt_jvm_proto_library.bzl#L28)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can I add a TODO for now?
</blockquote></details>

Sure.
___
*[build/kt_jvm_proto_library.bzl, line 176 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/26#-MgrY7kR7AehTeqGulCY:-MgvKFdTDrFpYHhuMaG_:b-wsxyjr) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1eed9b06d8a959bc7e586342836c2dd4189ea2bb/build/kt_jvm_proto_library.bzl#L176)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This is for consistency with https://github.com/grpc/grpc-kotlin/blob/master/kt_jvm_grpc.bzl#L150 -- which I think the reviewers wanted us to add. Happy to remove, though, if you prefer.
</blockquote></details>

It's mainly about the attributes that kt_jvm_library doesn't support and we don't check. It seems deceptive to have documented attributes that we do nothing with.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 4 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/26)* status: 5 of 7 files reviewed, 4 unresolved discussions (waiting on @efoxepstein, @oliver-amzn, and @SanjayVas)

___
*[build/common_jvm_maven.bzl, line 73 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/26#-MgvSIV_1sNeTR_KnFeC:-MgvSIV_1sNeTR_KnFeD:b9slzll) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/f4f060e0cffacc13e4e201f73a66194fd2c5e59f/build/common_jvm_maven.bzl#L73)):*
> ```Starlark
>         # For kt_jvm_proto_library.
>         # The version must match that in //build/com_google_protobuf/repo.bzl.
>         "com.google.protobuf:protobuf-kotlin": "3.17.3",
> ```

can you make this a constant for both files?
___
*[build/kt_jvm_proto_library.bzl, line 176 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/26#-MgrY7kR7AehTeqGulCY:-MgvS_lM54krzCNLcaax:b32v57) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1eed9b06d8a959bc7e586342836c2dd4189ea2bb/build/kt_jvm_proto_library.bzl#L176)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

It's mainly about the attributes that kt_jvm_library doesn't support and we don't check. It seems deceptive to have documented attributes that we do nothing with.
</blockquote></details>

+1
___
*[build/com_google_protobuf/repo.bzl, line 25 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/26#-MgvSbxbBhcA-5D10FJZ:-MgvSbxbBhcA-5D10FJ_:bi5sx0n) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/f4f060e0cffacc13e4e201f73a66194fd2c5e59f/build/com_google_protobuf/repo.bzl#L25)):*
> ```Starlark
>         name = "com_google_protobuf",
>         sha256 = "77ad26d3f65222fd96ccc18b055632b0bfedf295cb748b712a98ba1ac0b704b2",
>         strip_prefix = "protobuf-3.17.3",
> ```

make the version a constant

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/26)* status: 4 of 7 files reviewed, 3 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, and @stevenwarejones)

___
*[build/common_jvm_maven.bzl, line 73 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/26#-MgvSIV_1sNeTR_KnFeC:-MgvY4PwCNsj_BEBs7tm:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/f4f060e0cffacc13e4e201f73a66194fd2c5e59f/build/common_jvm_maven.bzl#L73)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

can you make this a constant for both files?
</blockquote></details>

Done.
___
*[build/kt_jvm_proto_library.bzl, line 176 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/26#-MgrY7kR7AehTeqGulCY:-MgvY35239bxa7K4ddD5:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1eed9b06d8a959bc7e586342836c2dd4189ea2bb/build/kt_jvm_proto_library.bzl#L176)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[build/com_google_protobuf/repo.bzl, line 25 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/26#-MgvSbxbBhcA-5D10FJZ:-MgvY3as8SyW6txsLh_W:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/f4f060e0cffacc13e4e201f73a66194fd2c5e59f/build/com_google_protobuf/repo.bzl#L25)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

make the version a constant
</blockquote></details>

Done.

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 5 of 7 files at r2, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/26)* status: all files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 4 of 7 files at r2, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/26)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/26)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @efoxepstein)

**Pull request merged**
