### PR TITLE
Create shared test certificates.

### PR DESCRIPTION
**Pull request by wangyaopw**
This includes certificates for
1 kingdom
3 duchies
6 EDPs
1 MC

Also generated private/public key pairs for the 6 EDPs and 1 MC.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/10)

### CODE REVIEW

**Review by SanjayVas — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/10)* status: 0 of 36 files reviewed, 1 unresolved discussion (waiting on @oliver-amzn and @wangyaopw)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/10#-Mel_u8Q62BYnffcqpDu:-Mel_u8Q62BYnffcqpDv:b-6udezx) (no related file):*
Approving this to unblock, but do we need static checked-in certificates (i.e. needing known keys) for this, or can we just have Bazel genrule targets to create them on-the-fly as needed?

---

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/10)* status: 0 of 36 files reviewed, 1 unresolved discussion (waiting on @oliver-amzn and @SanjayVas)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/10#-Mel_u8Q62BYnffcqpDu:-MelcdPNE3hCEvg_ExLj:b-m1lcz2) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Approving this to unblock, but do we need static checked-in certificates (i.e. needing known keys) for this, or can we just have Bazel genrule targets to create them on-the-fly as needed?
</blockquote></details>

for correctness test, I was planning to hardcode the der bytes in those preferred_certificate_der fields, and the paths to the server.PEM in the cue config.

I guess using genrule should also work although I don't know how to do that yet

---

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/10)* status: 0 of 36 files reviewed, 1 unresolved discussion (waiting on @oliver-amzn and @wangyaopw)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/10#-Mel_u8Q62BYnffcqpDu:-MelfTEPEDqIcoUloNeE:b-ecobzo) (no related file):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

for correctness test, I was planning to hardcode the der bytes in those preferred_certificate_der fields, and the paths to the server.PEM in the cue config.

I guess using genrule should also work although I don't know how to do that yet
</blockquote></details>

genrules are simple. They are just Bazel targets that run a command-line to generate files. See [example in CMMS](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/76ed543b461d5f234912c25dea927fc670f47eba/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/BUILD.bazel#L65) and [Bazel documentation](https://docs.bazel.build/versions/4.1.0/be/general.html#genrule).

For background, I checked in the existing ones as testdata to be able to have a unit tests which compare against a known SKID and AKID to make sure I was parsing those correctly. TransportSecurityTest also generates them on-the-fly, but from Kotlin code rather than Bazel target.

---

**Comment by wangyaopw** [comment]
Switched to generate certs using genrule.

**Comment by stevenwarejones** [comment]
is there a pull where i can see generating certs using genrules?

**Comment by wangyaopw** [comment]
> is there a pull where i can see generating certs using genrules?

https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/159

Not completed yet. Certs are generated, need to use them in the cues.

**Pull request closed without merging**
