### PR TITLE
revert: Postgres Connection Pool

### PR DESCRIPTION
**Pull request by tristanvuong2021**
Revert #289

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/292)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/292)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/292#-OER0qKz16I5IsVocniu:-OER0qKz16I5IsVocniv:b-ej2grr) (no related file):*
Was this revert not automatically generated? I see some parts missing, e.g. the MODULE.bazel change is not reverted in this PR. Use the "Revert" button in the GitHub UI to generate a PR that reverts another PR.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/292)* status: 1 of 6 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/292#-OER0qKz16I5IsVocniu:-OERAE-82M1LL9PV7H4Y:b-896fix) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Was this revert not automatically generated? I see some parts missing, e.g. the MODULE.bazel change is not reverted in this PR. Use the "Revert" button in the GitHub UI to generate a PR that reverts another PR.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/292)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
