### PR TITLE
Add more test cert files for unit-tests.

### PR DESCRIPTION
**Pull request by wangyaopw**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/24)

### CODE REVIEW

**Review by SanjayVas — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/24)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/24)* status: all files reviewed, 1 unresolved discussion (waiting on @wangyaopw)

___
*[-- commits, line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/24#-MgMXqoWE3HzmfzzZcKV:-MgMXqoWE3HzmfzzZcKW:bd28ic9) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/0261870f5686b579c5dce651d4800b251ba1e774/-- commits#L1)):*
i don't think this is supposed to make it into the diff

**Review by oliver-amzn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/24)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[-- commits, line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/24#-MgMXqoWE3HzmfzzZcKV:-MgMYaIK7jdwzEQNPvvC:byigcww) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/0261870f5686b579c5dce651d4800b251ba1e774/-- commits#L1)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i don't think this is supposed to make it into the diff
</blockquote></details>

Funny - I don't see that file in the github diffs.

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/24)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[-- commits, line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/24#-MgMXqoWE3HzmfzzZcKV:-MgMYwk6BfRe8xlejrjx:bc13y4o) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/0261870f5686b579c5dce651d4800b251ba1e774/-- commits#L1)):*
<details><summary><i>Previously, oliver-amzn (Oliver) wrote…</i></summary><blockquote>

Funny - I don't see that file in the github diffs.
</blockquote></details>

what shouldn't be in the diff is in it? Not sure what you are referring to.

**Review by oliver-amzn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/24)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[-- commits, line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/24#-MgMXqoWE3HzmfzzZcKV:-MgMZeYZ5Mg5cL2quGSm:b-n9c8ks) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/0261870f5686b579c5dce651d4800b251ba1e774/-- commits#L1)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

what shouldn't be in the diff is in it? Not sure what you are referring to.
</blockquote></details>

This "Commits" file. Unless that's not really a file and just a new Reviewable feature?

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/24)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[-- commits, line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/24#-MgMXqoWE3HzmfzzZcKV:-MgM_lRU2pU7Fp9q4J5j:b-5vgwpj) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/0261870f5686b579c5dce651d4800b251ba1e774/-- commits#L1)):*
<details><summary><i>Previously, oliver-amzn (Oliver) wrote…</i></summary><blockquote>

This "Commits" file. Unless that's not really a file and just a new Reviewable feature? 
</blockquote></details>

Interesting, some PRs have commit listed in reviewalbe, but some RPs don't.

For example, https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/177 also have it

but in gerrit, we always see commit message as a file listed in the PR.

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/24)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/24)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @oliver-amzn, @SanjayVas, and @wangyaopw)

___
*[-- commits, line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/24#-MgMXqoWE3HzmfzzZcKV:-MgMl5Pk0LnojSdctxI4:bwprmi7) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/0261870f5686b579c5dce651d4800b251ba1e774/-- commits#L1)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

Interesting, some PRs have commit listed in reviewalbe, but some RPs don't.

For example, https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/177 also have it

but in gerrit, we always see commit message as a file listed in the PR.


</blockquote></details>

i think some setting turned this on in the last few days. I didn't see it until a few days ago, but you're right its suddenly popping up across PRs. lgtm then.

**Review by wangyaopw — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/24)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[-- commits, line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/24#-MgMXqoWE3HzmfzzZcKV:-MgMyo9x7d-X7GdG_foq:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/0261870f5686b579c5dce651d4800b251ba1e774/-- commits#L1)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i think some setting turned this on in the last few days. I didn't see it until a few days ago, but you're right its suddenly popping up across PRs. lgtm then.
</blockquote></details>

Done.

**Review by wangyaopw — COMMENTED** [review]
> Dismissed @stevenwarejones from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/24)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)

___
*[-- commits, line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/24#-MgMXqoWE3HzmfzzZcKV:-MgMzFFI5W1-VcfR0gY7:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/0261870f5686b579c5dce651d4800b251ba1e774/-- commits#L1)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

**Pull request merged**
