### PR TITLE
Ensure common_jvm_maven_artifacts includes artifacts from grpc-java.

### PR DESCRIPTION
**Pull request by SanjayVas**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/114)

### CODE REVIEW

**Review by iverson52000 — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/114#-:-N1tN6azAi0urT1aZGw6:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 3 of 5 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/114)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`build/versions.bzl` line 18 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/114#-N1vUogk1ZCuVcUtFlGd:-N1vUogk1ZCuVcUtFlGe:b-j7h4v6) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/a8920267e6f04a43fd4020898d804592072f66e3/build/versions.bzl#L18)):*
> ```Starlark
> 
> GRPC_JAVA_VERSION = "1.46.0"
> PROTOBUF_VERSION = "3.19.1"
> ```

do you want to put kotlin versions here too?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/114)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`build/versions.bzl` line 18 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/114#-N1vUogk1ZCuVcUtFlGd:-N1yj8yE5cDkgLBPPw0W:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/a8920267e6f04a43fd4020898d804592072f66e3/build/versions.bzl#L18)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

do you want to put kotlin versions here too?
</blockquote></details>

Done.

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 2 of 5 files at r2, 1 of 2 files at r4, 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/114)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

**Review by SanjayVas — COMMENTED** [review]
> Dismissed @stevenwarejones from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/114)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
