### PR TITLE
Add a hashSha256 method to common-jvm.

### PR DESCRIPTION
**Pull request by wangyaopw**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/32)

### CODE REVIEW

**Review by SanjayVas — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/32)* status: all files reviewed, 1 unresolved discussion (waiting on @oliver-amzn and @wangyaopw)

___
*[src/test/kotlin/org/wfanet/measurement/common/crypto/HashingTest.kt, line 30 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/32#-Mih3H-N2gSsrhR5g0wt:-Mih3H-OCpivhtZJeOry:b-3nxs9v) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/43605dc600f972078333b86a7405694c3abd1ce1/src/test/kotlin/org/wfanet/measurement/common/crypto/HashingTest.kt#L30)):*
> ```Kotlin
>     val result = hashSha256(ByteString.copyFromUtf8("foo"))
>     assertThat(Base64.getEncoder().encodeToString(result.toByteArray()))
>       .isEqualTo("LCa0a2j/xo/5m0U8HTBBNBNCLXBkg7+g+YpeiGJm564=")
> ```

nit: we more commonly see sha256 hashes as hex strings, but this is fine

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/32)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @oliver-amzn and @SanjayVas)

___
*[src/test/kotlin/org/wfanet/measurement/common/crypto/HashingTest.kt, line 30 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/32#-Mih3H-N2gSsrhR5g0wt:-MihQlNg-btWQixKQ8Xs:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/43605dc600f972078333b86a7405694c3abd1ce1/src/test/kotlin/org/wfanet/measurement/common/crypto/HashingTest.kt#L30)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: we more commonly see sha256 hashes as hex strings, but this is fine
</blockquote></details>

Done

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/32)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliver-amzn)

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/32)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)

**Pull request merged**
