### PR TITLE
Add snakeyaml.

### PR DESCRIPTION
**Pull request by tristanvuong2021**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/123)

### CODE REVIEW

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/123)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by stevenwarejones — DISMISSED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/123)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1 and @tristanvuong2021)

___
*[`imports/java/org/yaml/BUILD.bazel` line 4 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/123#-N48hQBRChIrRSdebskH:-N48hQBRChIrRSdebskI:b-yk0mga) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/8538b8d722eb526b7cc05c0d7134d9f9201385a0/imports/java/org/yaml/BUILD.bazel#L4)):*
> ```Starlark
> 
> alias(
>     name = "snakeyaml",
> ```

whats the need for this dep?

**Comment by tristanvuong2021** [comment]
*[`imports/java/org/yaml/BUILD.bazel` line 4 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/123#-N48hQBRChIrRSdebskH:-N48iX6q3pi1hvKJ0Ka7:b-6z7o7b) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/8538b8d722eb526b7cc05c0d7134d9f9201385a0/imports/java/org/yaml/BUILD.bazel#L4)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

whats the need for this dep?
</blockquote></details>

@stevenwarejones It is for parsing liquibase yaml files when testing postgres code.

**Review by duliomatos1 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/123)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

**Pull request merged**
