### PR TITLE
Add testing utilities for loading keys from files.

### PR DESCRIPTION
**Pull request by SanjayVas**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/70)

https://rally1.rallydev.com/#/?detail=/task/619013800849&fdp=true

### CODE REVIEW

**Review by wangyaopw — APPROVED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/70)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/testing/KeyLoading.kt, line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/70#-Mq_HOJ3E4d4OEF72T92:-Mq_HOJ3E4d4OEF72T93:b-jjg4sh) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/36fbd8e6e2006d451039b5d91cab22c96141aa0c/src/main/kotlin/org/wfanet/measurement/common/crypto/testing/KeyLoading.kt#L29)):*
> ```
> certificateDer.inputStream().use { input -> readCertificate(input) }
> ```
maybe add this as another `readCertificate(derFile:File)` overload inside `src/main/kotlin/org/wfanet/measurement/common/crypto/SecurityProvider.kt`?

**Review by wangyaopw — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/70)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/testing/KeyLoading.kt, line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/70#-Mq_HOJ3E4d4OEF72T92:-Mq_aDJE594EvZ8iOXge:b32wwp) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/36fbd8e6e2006d451039b5d91cab22c96141aa0c/src/main/kotlin/org/wfanet/measurement/common/crypto/testing/KeyLoading.kt#L29)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I wanted to keep this in a test-only package, since there's no reason to read a cert from a DER file in production.
</blockquote></details>

sg

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/70)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/testing/KeyLoading.kt, line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/70#-Mq_HOJ3E4d4OEF72T92:-MqaIUSW48nFtDl1tGIf:b-c3sr88) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/36fbd8e6e2006d451039b5d91cab22c96141aa0c/src/main/kotlin/org/wfanet/measurement/common/crypto/testing/KeyLoading.kt#L29)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

sg
</blockquote></details>

I find one case in which we read DER file.

When we create certificate resources, we need to DER ByteStrings. So I saved the certificates as DER files such that I don't need to convert from PEM to DER in kotlin. As a result, the EDP, duchy and MC now also read certificate from DER files when they need to sign something.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/70)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/testing/KeyLoading.kt, line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/70#-Mq_HOJ3E4d4OEF72T92:-MqaavlS7ObEzjTTcuht:bkoy5ao) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/36fbd8e6e2006d451039b5d91cab22c96141aa0c/src/main/kotlin/org/wfanet/measurement/common/crypto/testing/KeyLoading.kt#L29)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

I find one case in which we read DER file.

When we create certificate resources, we need to DER ByteStrings. So I saved the certificates as DER files such that I don't need to convert from PEM to DER in kotlin. As a result, the EDP, duchy and MC now also read certificate from DER files when they need to sign something.


</blockquote></details>

That's still only in a test though, right? In production, certificates will come from one of two places:
1. The API where they will be DER-encoded `ByteString`s
2. A `SigningKeyHandle`, which itself either comes from a `SigningKeyStore` or from the Certificate Authority service when generating a new cert/key pair. `SigningKeyStore` stores a PEM file that contains both the certificate and private key together.

I don't believe there's ever a case where we have a DER-encoded file in production.

**Review by wangyaopw — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/70)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/testing/KeyLoading.kt, line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/70#-Mq_HOJ3E4d4OEF72T92:-MqomhPu9Fks4_IY1doV:b-dptvyi) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/36fbd8e6e2006d451039b5d91cab22c96141aa0c/src/main/kotlin/org/wfanet/measurement/common/crypto/testing/KeyLoading.kt#L29)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

That's still only in a test though, right? In production, certificates will come from one of two places:
1. The API where they will be DER-encoded `ByteString`s
2. A `SigningKeyHandle`, which itself either comes from a `SigningKeyStore` or from the Certificate Authority service when generating a new cert/key pair. `SigningKeyStore` stores a PEM file that contains both the certificate and private key together.

I don't believe there's ever a case where we have a DER-encoded file in production.
</blockquote></details>

Sure, We don't need a DER-encoded file if we have a function to convert a PEM file or Certificate object to the DER-encoded ByteString.

When creating a certificate we need to get the DER-encoded ByteString from a file or `SigningKeyHandle`

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/70)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/testing/KeyLoading.kt, line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/70#-Mq_HOJ3E4d4OEF72T92:-Mqonb3O63hIzslpCKk_:b5dgdeh) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/36fbd8e6e2006d451039b5d91cab22c96141aa0c/src/main/kotlin/org/wfanet/measurement/common/crypto/testing/KeyLoading.kt#L29)):*
> When creating a certificate we need to get the DER-encoded ByteString from a file or `SigningKeyHandle`

From a `SigningKeyHandle`, using `X509Certificate.encoded`.

**Review by kungfucraig — COMMENTED** [review]
I don't see tests for the newly added code.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/70#-:-MquBV7hA7vSGQXRksJH:b76r6nu)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by SanjayVas — COMMENTED** [review]
These are simple test utils. They are exercised in follow-up PR https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/400

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/70#-:-MquOfc94_qNWvLfsSoN:bwhdtqm)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by SanjayVas — COMMENTED** [review]
> I don't see tests for the newly added code.

Added tests for tink/KeyHandle.kt and SigningKeyHandle that exercise this code.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/70#-:-MqvGWxw9ebveWfY1uFm:b-puvwqc)* status: 12 of 17 files reviewed, all discussions resolved (waiting on @stevenwarejones and @wangyaopw)

**Review by wangyaopw — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 2 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/70)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by kungfucraig — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/70)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Pull request merged**
