### PR TITLE
Allow CoroutineContexts and Executors to be specified/configured.

### PR DESCRIPTION
**Pull request by SanjayVas**
This includes using a fixed thread pool Executor for gRPC servers. It allows more control over thread usage.

- - -
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/160)

### CODE REVIEW

**Comment by SanjayVas** [comment]
The linter warning can safely be ignored. It's triggering https://github.com/bazelbuild/buildtools/issues/1069.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 24 of 25 files at r1, 2 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/160)* status: all files reviewed, 3 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/TinkKeyStorageProvider.kt` line 28 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/160#-NAP_MqE-Vm3JmmzDKY_:-NAP_MqE-Vm3JmmzDKYa:b-b7ueom) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/fee843f3f53c91ca94b4704b76fd043f38e4f224/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/TinkKeyStorageProvider.kt#L28)):*
> ```Kotlin
> 
> class TinkKeyStorageProvider(
>   private val aeadContext: @BlockingExecutor CoroutineContext = Dispatchers.IO
> ```

what are the uses cases for needing to be able to configure aeadContext to something other than this?
___
*[`src/main/kotlin/org/wfanet/measurement/common/grpc/Channel.kt` line 39 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/160#-NAPa96922SXxIUNyzKs:-NAPa96922SXxIUNyzKt:bl3j4nk) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/fee843f3f53c91ca94b4704b76fd043f38e4f224/src/main/kotlin/org/wfanet/measurement/common/grpc/Channel.kt#L39)):*
> ```Kotlin
>   val channelBuilder =
>     NettyChannelBuilder.forTarget(target)
>       .directExecutor() // See https://github.com/grpc/grpc-kotlin/issues/263
> ```

are you noticing any performance increase by doing this?



_Code quote:_
```Kotlin
See https://github.com/grpc/grpc-kotlin/issues/263
```
___
*[`src/main/kotlin/org/wfanet/measurement/common/grpc/CommonServer.kt` line 63 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/160#-NAPaMgA-6XaGzN7TDE-:-NAPaMgA-6XaGzN7TDE0:b-x49ttw) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/fee843f3f53c91ca94b4704b76fd043f38e4f224/src/main/kotlin/org/wfanet/measurement/common/grpc/CommonServer.kt#L63)):*
> ```Kotlin
>       .apply {
>         executor(executor)
>         if (sslContext != null) {
> ```

why do you prefer this over let? Isn't let more kotlin-esque?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/160)* status: 24 of 25 files reviewed, 3 unresolved discussions (waiting on @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/TinkKeyStorageProvider.kt` line 28 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/160#-NAP_MqE-Vm3JmmzDKY_:-NAfZ1FD3Ox8eBl5bQve:b-b0r7kp) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/fee843f3f53c91ca94b4704b76fd043f38e4f224/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/TinkKeyStorageProvider.kt#L28)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

what are the uses cases for needing to be able to configure aeadContext to something other than this?
</blockquote></details>

If you want more control over the threads used by this. e.g. if you want to use a cached thread pool with different parameters, or one which uses a different thread factory.

The built-in Dispatchers aren't bad, but they don't allow you to easily control and track threads. We at Google are in fact [forbidden from using them in internal projects](https://github.com/grpc/grpc-kotlin/issues/60#issuecomment-618186497), and we would instead inject one that uses a thread pool constructed from one of our frameworks.

We're *probably* fine with `Dispatchers.Default` for CPU-bound and `Dispatchers.IO` for blocking I/O, but this leaves it open so callers can tune things.
___
*[`src/main/kotlin/org/wfanet/measurement/common/grpc/Channel.kt` line 39 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/160#-NAPa96922SXxIUNyzKs:-NAfaE3nCFLPHiaYOtW1:bryfrov) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/fee843f3f53c91ca94b4704b76fd043f38e4f224/src/main/kotlin/org/wfanet/measurement/common/grpc/Channel.kt#L39)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

are you noticing any performance increase by doing this?
</blockquote></details>

I haven't benchmarked it, but it does make sense given how grpc-kotlin uses coroutines. As mentioned in the linked issue, it should only be a problem if you have poorly-behaved interceptors (e.g. that do blocking I/O).

The [gRPC docs](https://grpc.io/docs/guides/performance/#java) recommend not using the default executors. The defaults are meant to avoid deadlocks/starvation in the case where blocking calls are done in places they shouldn't, but incur a performance penalty in well-behaved applications. See https://github.com/grpc/grpc-java/issues/7381 for more details on the default executor decision.
___
*[`src/main/kotlin/org/wfanet/measurement/common/grpc/CommonServer.kt` line 63 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/160#-NAPaMgA-6XaGzN7TDE-:-NAfdFZnDyadacfx_tcg:bq9f2q9) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/fee843f3f53c91ca94b4704b76fd043f38e4f224/src/main/kotlin/org/wfanet/measurement/common/grpc/CommonServer.kt#L63)):*
Our internal Google Kotlin best practices guide states to avoid using `?.let {...}` where smart casts would suffice, and explicitly calls out `if (namedVariable != null) { ... }` case.

>` expression?.let { something(it) }` is a common idiom in Kotlin to execute some operations on the result of an expression if expression does not evaluate to null. However, the Kotlin standard libraries almost never use this idiom: JetBrains has reached the conclusion that it generally harms readability.

I'm happy to change since we're not following this style explicitly in this project, but the advice seems sound given that it's what Google and Jetbrains, being authors of the Kotlin language, follow.

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/160)* status: 24 of 25 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/common/grpc/CommonServer.kt` line 63 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/160#-NAPaMgA-6XaGzN7TDE-:-NAkGD2XAQ-dPK-w8vQl:bfyc21t) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/fee843f3f53c91ca94b4704b76fd043f38e4f224/src/main/kotlin/org/wfanet/measurement/common/grpc/CommonServer.kt#L63)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Our internal Google Kotlin best practices guide states to avoid using `?.let {...}` where smart casts would suffice, and explicitly calls out `if (namedVariable != null) { ... }` case.

>` expression?.let { something(it) }` is a common idiom in Kotlin to execute some operations on the result of an expression if expression does not evaluate to null. However, the Kotlin standard libraries almost never use this idiom: JetBrains has reached the conclusion that it generally harms readability.

I'm happy to change since we're not following this style explicitly in this project, but the advice seems sound given that it's what Google and Jetbrains, being authors of the Kotlin language, follow.
</blockquote></details>

I'm fine either way but I `?.let` is all over the place and I've actually had a number of reviews where the reviewer asked me to change it to `?.let` on this project

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> Dismissed @stevenwarejones from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/160)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/common/grpc/CommonServer.kt` line 63 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/160#-NAPaMgA-6XaGzN7TDE-:-NAkhBzd01JtVCDoYWFI:b-49bj8t) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/fee843f3f53c91ca94b4704b76fd043f38e4f224/src/main/kotlin/org/wfanet/measurement/common/grpc/CommonServer.kt#L63)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I'm fine either way but I `?.let` is all over the place and I've actually had a number of reviews where the reviewer asked me to change it to `?.let` on this project
</blockquote></details>

There is one case where I think `?.let` may be more readable, and that's when chaining.

**Pull request merged**
