### PR TITLE
Add the google cloud bigquery to common imports

### PR DESCRIPTION
**Pull request by wangyaopw**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/56)

### CODE REVIEW

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/56)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @mpatel24, and @wangyaopw)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/56#-MnWldKd8m8qkFnR_wwb:-MnWldKd8m8qkFnR_wwc:bcc495s) (no related file):*
Just confirming that we're going to have some common BigQuery code in common-jvm?

---

**Comment by wangyaopw** [comment]
I'll add the dependency to cross-media-measurement directly.

**Comment by SanjayVas** [comment]
Adding it to imports is sufficient to add to common-jvm, I was just curious on if there was other code.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/56)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @kungfucraig, @mpatel24, @SanjayVas, and @wangyaopw)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/56#-MnWldKd8m8qkFnR_wwb:-MnbCKjh9_qbMz_BUSwf:bpvsre3) (no related file):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

ah, I am adding some BigQuery code in the cross-media-measurement repo. and I find there are some existing in the panel-exchange-client repo.

Do we only add the imports to common-jvm when we have code in it?
</blockquote></details>

can you point to where that code is? It'll need to get ported to other clouds. 

---

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/56)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @kungfucraig, @mpatel24, @SanjayVas, and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/56#-MnWldKd8m8qkFnR_wwb:-MnbIV3G82Z37Q4CJ0oT:bd0o80h) (no related file):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

can you point to where that code is? It'll need to get ported to other clouds. 
</blockquote></details>

The code doesn't exist yet. BigQuery will be used by the EDP simulator. In the M1B demo, the simulator will read the events from pre-generated synthetic data stored in bigquery.

---

**Review by wangyaopw — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/56)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @kungfucraig, @mpatel24, @SanjayVas, and @stevenwarejones)

**Pull request merged**
