### PR TITLE
Factor out postgre-b64-decoder to common-jvm

### PR DESCRIPTION
**Pull request by YuhongWang-Amazon**
This factors out the `JsonPrimitive.decodePostgresBase64` function from [ReportReader](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/28544c15a00adf06a19cdabf40667a9e2da33c98/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportReader.kt#LL531C1-L537C4) to common-jvm, so it could be used in ComputationReader and other Postgres Database Readers.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/199)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/199)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @YuhongWang-Amazon)

___
*[`src/main/kotlin/org/wfanet/measurement/common/db/r2dbc/postgres/PostgresBase64Decoder.kt` line 24 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/199#-NYU-9sS5NC0vY6u_TE1:-NYU-9sS5NC0vY6u_TE2:bqcn7tj) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/49d02f50b387f6fbd0384a959ff346e70c190a42/src/main/kotlin/org/wfanet/measurement/common/db/r2dbc/postgres/PostgresBase64Decoder.kt#L24)):*
> ```Kotlin
>  * the text. The MIME decoder ignores the \n.
>  */
> fun JsonPrimitive.decodePostgresBase64(): ByteArray {
> ```

This doesn't seem Postgres-specific. It's really just base64 w/MIME encoding (used in other formats such as PEM). The only dependency is gson, which is also a dependency of protobuf-java-util so basically a core dependency for us.

Put this function in `src/main/kotlin/org/wfanet/measurement/common/Base64.kt` and rename it. Maybe `base64MimeDecode`? We also tend to prefer to only use `ByteArray` when forced to at the edges of interactions with third-party libraries. We prefer `ByteString` due to immutability whenever we can do so without too many extra copies (these are cheaply convertible to read-only `ByteBuffer` instances when needed, and most modern Java APIs support those rather than just `ByteArray`).

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/199)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @YuhongWang-Amazon)

___
*[`src/main/kotlin/org/wfanet/measurement/common/db/r2dbc/postgres/PostgresBase64Decoder.kt` line 24 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/199#-NYU-9sS5NC0vY6u_TE1:-NYU4Dm11MT24s8bBvNS:b-xsof4w) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/49d02f50b387f6fbd0384a959ff346e70c190a42/src/main/kotlin/org/wfanet/measurement/common/db/r2dbc/postgres/PostgresBase64Decoder.kt#L24)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This doesn't seem Postgres-specific. It's really just base64 w/MIME encoding (used in other formats such as PEM). The only dependency is gson, which is also a dependency of protobuf-java-util so basically a core dependency for us.

Put this function in `src/main/kotlin/org/wfanet/measurement/common/Base64.kt` and rename it. Maybe `base64MimeDecode`? We also tend to prefer to only use `ByteArray` when forced to at the edges of interactions with third-party libraries. We prefer `ByteString` due to immutability whenever we can do so without too many extra copies (these are cheaply convertible to read-only `ByteBuffer` instances when needed, and most modern Java APIs support those rather than just `ByteArray`).

</blockquote></details>

Since you [should be](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/code-style.md#bazel-build-and-starlark) indicating the gson dependency explicitly, I wanted to point out that it's in the wrong place. It's at `//imports/java/com/google/code/gson`, but should actually be at `//imports/java/com/google/gson:gson` (to match the JVM package) so you may want to move it first.

**Review by YuhongWang-Amazon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/199)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/common/db/r2dbc/postgres/PostgresBase64Decoder.kt` line 24 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/199#-NYU-9sS5NC0vY6u_TE1:-NYUEGuL7539cZ_oNC1y:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/49d02f50b387f6fbd0384a959ff346e70c190a42/src/main/kotlin/org/wfanet/measurement/common/db/r2dbc/postgres/PostgresBase64Decoder.kt#L24)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Since you [should be](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/code-style.md#bazel-build-and-starlark) indicating the gson dependency explicitly, I wanted to point out that it's in the wrong place. It's at `//imports/java/com/google/code/gson`, but should actually be at `//imports/java/com/google/gson:gson` (to match the JVM package) so you may want to move it first.
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/199)* status: all files reviewed, 3 unresolved discussions (waiting on @YuhongWang-Amazon)

___
*[`src/main/kotlin/org/wfanet/measurement/common/Base64.kt` line 41 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/199#-NYUJh1M9N6itNQU2riY:-NYUJh1M9N6itNQU2riZ:bz4y809) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/8af9809ae2b03a19e33ee3119876ad743a4b9a9b/src/main/kotlin/org/wfanet/measurement/common/Base64.kt#L41)):*
> ```Kotlin
> 
> fun JsonPrimitive.base64MimeDecode(): ByteString {
>   return mimeDecoder.decode(this.asString).toByteString()
> ```

Follow existing pattern.



_Suggestion:_
```Kotlin
asString.decode(mimeDecoder)
```
___
*[`src/test/resources/db/postgres/create-test-schema.sql` line 33 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/199#-NYUKxw-1pg9mukl4yWz:-NYUKxw-1pg9mukl4yX-:b3mquyh) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/8af9809ae2b03a19e33ee3119876ad743a4b9a9b/src/test/resources/db/postgres/create-test-schema.sql#L33)):*
> ```TSQL
> );
> 
> CREATE TABLE CarDescriptions (
> ```

I don't see this used?

**Review by YuhongWang-Amazon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/199)* status: 6 of 8 files reviewed, 3 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/common/Base64.kt` line 41 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/199#-NYUJh1M9N6itNQU2riY:-NYUOiyi1CSKZ1q93T8O:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/8af9809ae2b03a19e33ee3119876ad743a4b9a9b/src/main/kotlin/org/wfanet/measurement/common/Base64.kt#L41)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Follow existing pattern.
</blockquote></details>

Done.
___
*[`src/test/resources/db/postgres/create-test-schema.sql` line 33 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/199#-NYUKxw-1pg9mukl4yWz:-NYUOSAL3wZtObRjReO6:b-yaibkt) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/8af9809ae2b03a19e33ee3119876ad743a4b9a9b/src/test/resources/db/postgres/create-test-schema.sql#L33)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I don't see this used?
</blockquote></details>

It was used to test the initial implementation. Missed when reverting those changes. Now removed.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/199)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @YuhongWang-Amazon)

**Pull request merged**
