### PR TITLE
Implement all TODOs for Tink skeletons

### PR DESCRIPTION
**Pull request by corbantek**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/49)

### CODE REVIEW

**Review by corbantek — COMMENTED** [review]
I've re-rebased on top of your branch however I think Reviewable is getting somewhat confused on a few of these files (I have to look at R2 - R3).  I think it will clear up once your stuff is merged.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/49#-:-MlvGIwbDueOgm58PbYG:bubap6u)* status: 0 of 12 files reviewed, 7 unresolved discussions (waiting on @SanjayVas)

**Review by stevenwarejones — COMMENTED** [review]
i'm happy once you take care of Eli and Sanjay's comments

> Reviewed 1 of 11 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/49#-:-Mm0IR562IIqDhylkRG3:b-6057sa)* status: all files reviewed, 10 unresolved discussions (waiting on @corbantek, @SanjayVas, and @zachcwc)

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/49)* status: all files reviewed, 9 unresolved discussions (waiting on @corbantek, @SanjayVas, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/tink/KmsStorageClient.kt, line 74 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/49#-Mm-PZFs7oKo1o0Fet1y:-Mm0J3nA0JD3gJhVg35y:b9cmxa0) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/c72e00dad869cb8d5c31021acdceb581541e6456/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/KmsStorageClient.kt#L74)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

OK, I'm a little dubious that it's worth the cost here instead of explicitly rebuffering the flow when it matters but doesn't seem too important
</blockquote></details>

Yeah, I can't remember exactly why I did it this way. I did a search and the only place I could find currrently where we read a blob and pass it over gRPC (Duchy->Duchy), it rebuffers later instead of passing this param. Probably should clean up StorageClient.Blob to remove the param at some point.

For now, I propose leaving this code as-is and respecting the param.

**Review by corbantek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/49)* status: 9 of 12 files reviewed, 6 unresolved discussions (waiting on @efoxepstein, @SanjayVas, @stevenwarejones, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/tink/KeyHandle.kt, line 45 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/49#-Mm-NvEM8DV3b8UlOcPF:-Mm0aDf86mn7IyJ2FagW:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/c72e00dad869cb8d5c31021acdceb581541e6456/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/KeyHandle.kt#L45)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ah, in that case: please use the already existing function
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/tink/KmsStorageClient.kt, line 39 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/49#-Mm-OEmH39Ope5R8Tqs-:-Mm0aSRu7HYIknb-UU14:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/c72e00dad869cb8d5c31021acdceb581541e6456/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/KmsStorageClient.kt#L39)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Nit: can you add a blank line between this and `@param`?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/tink/KmsStorageClient.kt, line 44 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/49#-Mm-OqXP3BQ9SUyokkmh:-Mm0akSC4tOfalKRtQKz:b-y0zr33) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/c72e00dad869cb8d5c31021acdceb581541e6456/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/KmsStorageClient.kt#L44)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Could you add an argument keyword in front of `null` so it's obvious what this means?
</blockquote></details>

I had originally tried that but since this is non kotlin class I'm calling it throws a syntax error, was there something else you were wanting?

I had tried 
```kotlin
val ciphertext = aead.encrypt(content.flatten().toByteArray(), associatedData = null)
```
but not allowed. 

Note: originally I had used `byteArrayOf()` instead of null but people didn't like that either
___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/tink/KmsStorageClient.kt, line 44 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/49#-Mm-UUUc8xd8igBSidEF:-Mm0bWSvArlfpNzalS1J:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/c72e00dad869cb8d5c31021acdceb581541e6456/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/KmsStorageClient.kt#L44)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`Bytes.kt` has a `Flow<ByteString>.toByteArray()` helper function
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/tink/KmsStorageClient.kt, line 65 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/49#-Mm-PpkT2GZw5c5oplaQ:-Mm0bgC5EOKLpUtkvytO:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/c72e00dad869cb8d5c31021acdceb581541e6456/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/KmsStorageClient.kt#L65)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/tink/KmsStorageClient.kt, line 68 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/49#-Mm-Q_YUBwD2ZGV0hn3U:-Mm0cJgf3oJVjiZBapom:b-92v43u) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/c72e00dad869cb8d5c31021acdceb581541e6456/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/KmsStorageClient.kt#L68)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

How does this work? There's no `emit` or `emitAll` call in here so what's outputting to the `FlowCollector`?
</blockquote></details>

I think I fixed it...
___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/tink/KmsStorageClient.kt, line 70 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/49#-Mm-eUGyAjHiuhvI_aoA:-Mm0bt0s9fn3HUk4Xcfx:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/c72e00dad869cb8d5c31021acdceb581541e6456/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/KmsStorageClient.kt#L70)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Nevermind, you were correct that we want the underlying read to use the storage client's default buffer size without resizing. It's better to use the parameterless `Blob.read` for that.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/tink/PrivateKeyStore.kt, line 42 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/49#-Mm-fUJ--fjengK6ZvGd:-Mm0cn4gEa7cTKEawzSt:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/c72e00dad869cb8d5c31021acdceb581541e6456/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/PrivateKeyStore.kt#L42)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> return@use 
> ```
`use` returns the value of the final expression, so the `return` is unnecessary
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/49)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/tink/KmsStorageClient.kt, line 44 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/49#-Mm-OqXP3BQ9SUyokkmh:-Mm0rXIlByHa1hSSXpAp:bcd5mpb) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/c72e00dad869cb8d5c31021acdceb581541e6456/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/KmsStorageClient.kt#L44)):*
<details><summary><i>Previously, corbantek (Kyle Johnson) wrote…</i></summary><blockquote>

I had originally tried that but since this is non kotlin class I'm calling it throws a syntax error, was there something else you were wanting?

I had tried 
```kotlin
val ciphertext = aead.encrypt(content.flatten().toByteArray(), associatedData = null)
```
but not allowed. 

Note: originally I had used `byteArrayOf()` instead of null but people didn't like that either
</blockquote></details>

Oh right, Aead is from Tink. Nevermind

**Pull request merged**
