### PR TITLE
Hardcode Kotlin version

### PR DESCRIPTION
**Pull request by efoxepstein**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/7)

### CODE REVIEW

**Review by SanjayVas — APPROVED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/7)* status: all files reviewed, 2 unresolved discussions (waiting on @efoxepstein)

___
*[build/io_bazel_rules_kotlin/deps.bzl, line 32 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/7#-MefIBtT6XAIOPkFFh1t:-MefIBtT6XAIOPkFFh1u:b-zbpc7z) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/9bec21831822884eefc3ab9b999db01bff7d9981/build/io_bazel_rules_kotlin/deps.bzl#L32)):*
> ```
> compiler_release = compiler_release
> ```
As an aside, I'm not actually sure why we specify a compiler release. It's not actually necessary unless we specifically want to override the default. I think I copied it from something Mark wrote.
___
*[build/io_bazel_rules_kotlin/repo.bzl, line 31 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/7#-MefIRiDA_IBcpKEHgYH:-MefIRiDA_IBcpKEHgYI:bov565q) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/9bec21831822884eefc3ab9b999db01bff7d9981/build/io_bazel_rules_kotlin/repo.bzl#L31)):*
> ```
> "v1.5.0-alpha-2",
> ```
Up to you if you want to do this in the same PR or not, but there's a beta release now (`v1.5.0-beta-2`).

**Review by SanjayVas — APPROVED** [review]
Maybe note why we want to hard-code this in common-jvm?

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/7#-:-MefIoURCq_mvOpQjLlJ:b-4qi37s)* status: all files reviewed, 2 unresolved discussions (waiting on @efoxepstein)

**Review by efoxepstein — COMMENTED** [review]
Done

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/7#-:-MefK50R4n9bDAKrDlv3:bb6un1j)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @SanjayVas)

___
*[build/io_bazel_rules_kotlin/repo.bzl, line 31 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/7#-MefIRiDA_IBcpKEHgYH:-MefJnZi0j6LrIx_OpB8:bc2gzcs) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/9bec21831822884eefc3ab9b999db01bff7d9981/build/io_bazel_rules_kotlin/repo.bzl#L31)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> "v1.5.0-alpha-2",
> ```
Up to you if you want to do this in the same PR or not, but there's a beta release now (`v1.5.0-beta-2`).
</blockquote></details>

This fails with some error about Android :(

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/7)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliver-amzn and @stevenwarejones)

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/7)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @stevenwarejones)

___
*[build/io_bazel_rules_kotlin/repo.bzl, line 31 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/7#-MefN5SPBKC51IK0dZaA:-MefN5SPBKC51IK0dZaB:b4pbppw) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/610dded25e131b5021e32c546c2b04c39f61edf0/build/io_bazel_rules_kotlin/repo.bzl#L31)):*
> ```Starlark
> def rules_kotlin_repo():
>     _rules_kotlin_repo(
>         version = "v1.5.0-alpha-2",
> ```

Question: do we now need to keep the kotlin compiler version in sync here and in `cross-media-measurement` ?

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/7)* status: all files reviewed, 1 unresolved discussion (waiting on @oliver-amzn and @stevenwarejones)

___
*[build/io_bazel_rules_kotlin/repo.bzl, line 31 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/7#-MefN5SPBKC51IK0dZaA:-MefNU4jB5HYGT7qLyuf:b-wy3v3f) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/610dded25e131b5021e32c546c2b04c39f61edf0/build/io_bazel_rules_kotlin/repo.bzl#L31)):*
<details><summary><i>Previously, oliver-amzn (Oliver) wrote…</i></summary><blockquote>

Question: do we now need to keep the kotlin compiler version in sync here and in `cross-media-measurement` ? 
</blockquote></details>

`cross-media-measurement` will be changed to use this function with the hardcoded version.

**Review by oliver-amzn — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/7)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

___
*[build/io_bazel_rules_kotlin/repo.bzl, line 31 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/7#-MefN5SPBKC51IK0dZaA:-MefQLYA9dWaZ8szrnE6:b3axgw) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/610dded25e131b5021e32c546c2b04c39f61edf0/build/io_bazel_rules_kotlin/repo.bzl#L31)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`cross-media-measurement` will be changed to use this function with the hardcoded version.
</blockquote></details>

❤️

**Pull request merged**
