### PR TITLE
Add kt_jvm_proto_library target for google.type.Date

### PR DESCRIPTION
**Pull request by yunyeng**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/30)

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/30)* status: all files reviewed, 1 unresolved discussion (waiting on @kgaynor, @SanjayVas, @stevenwarejones, and @yunyeng)

___
*[src/main/proto/google/type/BUILD.bazel, line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/30#-MiXGcwG0UROLfV3gMLh:-MiXGcwG0UROLfV3gMLi:bkr43c7) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/dcc706c1f0b3edd0a4651e7af5f770ad171c1870/src/main/proto/google/type/BUILD.bazel#L1)):*
> ```Starlark
> load("@wfa_common_jvm//build:kt_jvm_proto_library.bzl", "kt_jvm_proto_library")
> ```

Remove `@wfa_common_jvm` prefix please

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/30)* status: all files reviewed, 2 unresolved discussions (waiting on @kgaynor, @stevenwarejones, and @yunyeng)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/30#-MiXZS4P7nj3KG4ri9E-):*
> ```
> Move DateKt Dsl into common proto
> ```

What this PR is doing is *adding* a kt_jvm_proto_library target for `google.type.Date`. It's not *moving* anything. The fact that this does anything w.r.t. Kotlin DSL is an implementation detail.

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/30)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @efoxepstein, @SanjayVas, and @stevenwarejones)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/30#-MiXZS4P7nj3KG4ri9E-):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> Move DateKt Dsl into common proto
> ```

What this PR is doing is *adding* a kt_jvm_proto_library target for `google.type.Date`. It's not *moving* anything. The fact that this does anything w.r.t. Kotlin DSL is an implementation detail.
</blockquote></details>

Done.
___
*[src/main/proto/google/type/BUILD.bazel, line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/30#-MiXGcwG0UROLfV3gMLh:-MiXeNoL6-rVRolTad4Z:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/dcc706c1f0b3edd0a4651e7af5f770ad171c1870/src/main/proto/google/type/BUILD.bazel#L1)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Remove `@wfa_common_jvm` prefix please
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/30)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @stevenwarejones)

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/30)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Pull request merged**
