### PR TITLE
Add factory for generating Tink ECIES key pairs.

### PR DESCRIPTION
**Pull request by SanjayVas**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/67)

### CODE REVIEW

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/67)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/tink/KeyHandle.kt, line 84 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/67#-MqR7sNFEEVbfBSYHx_i:-MqR7sNFEEVbfBSYHx_j:b4p9owq) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/b5783009effd2a8becde70d94887539804033f6a/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/KeyHandle.kt#L84)):*
> ```
> ECIES_KEY_TEMPLATE
> ```
you can use `HybridKeyTemplates.ECIES_P256_HKDF_HMAC_SHA256_AES128_GCM` directly I think.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/67)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @stevenwarejones and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/tink/KeyHandle.kt, line 84 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/67#-MqR7sNFEEVbfBSYHx_i:-MqR9qwi1Yj5lApZF_3w:b2u3tme) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/b5783009effd2a8becde70d94887539804033f6a/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/KeyHandle.kt#L84)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> ECIES_KEY_TEMPLATE
> ```
you can use `HybridKeyTemplates.ECIES_P256_HKDF_HMAC_SHA256_AES128_GCM` directly I think.
</blockquote></details>

That's deprecated, with a message saying to use `KeyTemplates.get` instead.

**Review by wangyaopw — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/67)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/tink/KeyHandle.kt, line 84 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/67#-MqR7sNFEEVbfBSYHx_i:-MqRABWl9XR8Ftc5OTx5:btdsfzr) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/b5783009effd2a8becde70d94887539804033f6a/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/KeyHandle.kt#L84)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

That's deprecated, with a message saying to use `KeyTemplates.get` instead.
</blockquote></details>

I see.

**Review by wangyaopw — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/67)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/67)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
