### PR TITLE
Add function generateHpke to generate tink key pair.

### PR DESCRIPTION
**Pull request by renjiezh**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/233)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/233)* status: all files reviewed, 1 unresolved discussion (waiting on @ple13 and @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/KeyHandle.kt` line 88 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/233#-Nr7ZVAP9h2F2SCAel0Q:-Nr7ZVAQ5Qyvc3UOQbu_:bu0igab) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/6047f4a2891d0d477f2b1408ca041f8f88617ff8/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/KeyHandle.kt#L88)):*
> ```Kotlin
>     }
> 
>     fun generateDhkem(): TinkPrivateKeyHandle {
> ```

The actual standard that's different here is HPKE (Hybrid Public Key Encryption) instead of ECIES (Elliptic Curve Integrated Encryption Scheme). The DHKEM part is just indicating that the KEM part of HPKE is using DH (Diffie Hellman)



_Suggestion:_
```Kotlin
generateHpke
```

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/233)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @ple13 and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/KeyHandle.kt` line 88 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/233#-Nr7ZVAP9h2F2SCAel0Q:-Nr86kDlDCNrhAw_kdNp:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/6047f4a2891d0d477f2b1408ca041f8f88617ff8/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/KeyHandle.kt#L88)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The actual standard that's different here is HPKE (Hybrid Public Key Encryption) instead of ECIES (Elliptic Curve Integrated Encryption Scheme). The DHKEM part is just indicating that the KEM part of HPKE is using DH (Diffie Hellman)
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/233)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @ple13 and @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/KeyHandle.kt` line 67 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/233#-Nr8C6pM16I9vhPnrjO2:-Nr8C6pM16I9vhPnrjO3:bpxlgvm) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/6b60314835b7c65affafe33bc33ba56ebea2460f/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/KeyHandle.kt#L67)):*
> ```Kotlin
>   override val publicKey = TinkPublicKeyHandle(keysetHandle.publicKeysetHandle)
> 
>   val privateKey: ByteString
> ```

The Tink recommendation is to avoid ever exposing the cleartext private key. We currently only do so for testing, using the `tinkey` util rather than generating the keys from code.

Notice how `keysetHandle` is `internal`. This is to force the caller to use `PrivateKeyStore` if they want to write the bytes anywhere.
___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/KeyHandle.kt` line 113 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/233#-Nr8DOW79WSYVJbGXCMp:-Nr8DOW79WSYVJbGXCMq:b-tm2ach) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/6b60314835b7c65affafe33bc33ba56ebea2460f/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/KeyHandle.kt#L113)):*
> ```Kotlin
> fun loadPrivateKey(binaryKeyset: ByteString): TinkPrivateKeyHandle {
>   val keysetHandle: KeysetHandle =
>     binaryKeyset.toByteArray().inputStream().use { input ->
> ```

You shouldn't need to convert to a byte array first. `ByteString` has a `newInput` method that you can use.



_Code quote:_
```Kotlin
toByteArray()
```

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/233)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @ple13 and @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/KeyHandle.kt` line 67 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/233#-Nr8C6pM16I9vhPnrjO2:-Nr8F-zUBT60hyEv3tdN:b-ur4e1j) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/6b60314835b7c65affafe33bc33ba56ebea2460f/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/KeyHandle.kt#L67)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The Tink recommendation is to avoid ever exposing the cleartext private key. We currently only do so for testing, using the `tinkey` util rather than generating the keys from code.

Notice how `keysetHandle` is `internal`. This is to force the caller to use `PrivateKeyStore` if they want to write the bytes anywhere.
</blockquote></details>

Note that there's an open bug that needs addressing w.r.t. PrivateKeyStore. See #138

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/233)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @ple13 and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/KeyHandle.kt` line 67 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/233#-Nr8C6pM16I9vhPnrjO2:-NrCDkdnBTtRVC_bRpOw:b-hx3kgp) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/6b60314835b7c65affafe33bc33ba56ebea2460f/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/KeyHandle.kt#L67)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Note that there's an open bug that needs addressing w.r.t. PrivateKeyStore. See #138
</blockquote></details>

Done.
`privateKey` removed.
___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/KeyHandle.kt` line 113 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/233#-Nr8DOW79WSYVJbGXCMp:-NrCDqJu-1XSrTK3yOrk:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/6b60314835b7c65affafe33bc33ba56ebea2460f/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/KeyHandle.kt#L113)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You shouldn't need to convert to a byte array first. `ByteString` has a `newInput` method that you can use.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/233)* status: all files reviewed, 1 unresolved discussion (waiting on @ple13 and @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/tink/KeyHandle.kt` line 80 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/233#-NrCGHOX6r0MSiwXIvwb:-NrCGHOX6r0MSiwXIvwc:b2ni8l0) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/8dadcfa1853b00be12a9e5c016bf6bee48031718/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/KeyHandle.kt#L80)):*
> ```Kotlin
>     private val ECIES_KEY_TEMPLATE = KeyTemplates.get("ECIES_P256_HKDF_HMAC_SHA256_AES128_GCM")
> 
>     private val DHKEM_KEY_TEMPLATE =
> ```

nit



_Suggestion:_
```Kotlin
HPKE_KEY_TEMPLATE
```

**Review by ple13 — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/233)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/233)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Pull request merged**
