### PR TITLE
update rules_jvm_external

### PR DESCRIPTION
**Pull request by stevenwarejones**
Updates to latest rules_jvm_external release
Resolves differences in import versions (eg two versions of same package were being imported)

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/80)

### CODE REVIEW

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/80)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @efoxepstein)

**Review by efoxepstein — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/80)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[build/common_jvm_maven.bzl, line 61 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/80#-MtPlg6h472vuTp5lgxe:-MtPlg6i6mWE0nZvgrN7:b-zhvmj1) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/d5acd3a09b6e9bb5a47bf2d6c8015b439e92a8ad/build/common_jvm_maven.bzl#L61)):*
> ```Starlark
>     maven_artifacts.update({
>         "com.adobe.testing:s3mock-junit4": "2.2.3",
>         "com.google.api:gax": "2.7.0",
> ```

Has this been tested on Google Cloud? It's possible it compiles but causes runtime errors.

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/80)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @SanjayVas)

___
*[build/common_jvm_maven.bzl, line 61 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/80#-MtPlg6h472vuTp5lgxe:-MtQPvkuB-HBkj2RiqBQ:b-l4t2nu) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/d5acd3a09b6e9bb5a47bf2d6c8015b439e92a8ad/build/common_jvm_maven.bzl#L61)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Has this been tested on Google Cloud? It's possible it compiles but causes runtime errors.
</blockquote></details>

Do you mind testing it next week? Do I need to ask Yao too? I wont' merge until then. When the jar was getting zipped up, it was complaining that both versions were getting included.

**Review by efoxepstein — COMMENTED** [review]
> Reviewed 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/80)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @SanjayVas, and @stevenwarejones)

___
*[build/common_jvm_maven.bzl, line 61 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/80#-MtPlg6h472vuTp5lgxe:-MtZye5P4xDeJmvn0HIY:bf3jhl1) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/d5acd3a09b6e9bb5a47bf2d6c8015b439e92a8ad/build/common_jvm_maven.bzl#L61)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Do you mind testing it next week? Do I need to ask Yao too? I wont' merge until then. When the jar was getting zipped up, it was complaining that both versions were getting included.
</blockquote></details>

Happy to test it if you remind me to

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/80)* status: 1 of 4 files reviewed, all discussions resolved (waiting on @efoxepstein and @SanjayVas)

___
*[build/common_jvm_maven.bzl, line 61 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/80#-MtPlg6h472vuTp5lgxe:-MthNiwN1g9HutR-bNuM:b-he7vno) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/d5acd3a09b6e9bb5a47bf2d6c8015b439e92a8ad/build/common_jvm_maven.bzl#L61)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Happy to test it if you remind me to
</blockquote></details>

I split this part out into a separate PR so I can go ahead and merge this

**Review by stevenwarejones — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/80)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @efoxepstein and @SanjayVas)

**Pull request merged**
