### PR TITLE
Add helper functions for dealing with google.protobuf.Any messages.

### PR DESCRIPTION
**Pull request by SanjayVas**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/219)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/219)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/common/ProtoReflection.kt` line 229 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/219#-NhTPJBs0UUeU9k1w7HH:-NhTPJBs0UUeU9k1w7HI:b-m5hh2h) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/2c517cfa2d862aa55cfc833621e13f6c6f1c8869/src/main/kotlin/org/wfanet/measurement/common/ProtoReflection.kt#L229)):*
> ```Kotlin
> fun Message.pack(): ProtoAny {
>   return ProtoAny.pack(this)
> }
> ```

might be nice to have some unpack helper as well
___
*[`src/test/kotlin/org/wfanet/measurement/common/ProtoReflectionTest.kt` line 78 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/219#-NhTOoa-7hxct9rc3ZC9:-NhTOoa-7hxct9rc3ZCA:b-f1v1zi) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/2c517cfa2d862aa55cfc833621e13f6c6f1c8869/src/test/kotlin/org/wfanet/measurement/common/ProtoReflectionTest.kt#L78)):*
> ```Kotlin
> 
>   @Test
>   fun `getDefaultInstance returns default instance`() {
> ```

ideally, all the functions should have tests

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/219)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/common/ProtoReflection.kt` line 229 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/219#-NhTPJBs0UUeU9k1w7HH:-NhTW0yfBQ3mIncx6fsz:bwgei1z) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/2c517cfa2d862aa55cfc833621e13f6c6f1c8869/src/main/kotlin/org/wfanet/measurement/common/ProtoReflection.kt#L229)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

might be nice to have some unpack helper as well
</blockquote></details>

That already exists in com.google.protobuf.kotlin. Not sure why they didn't add the pack extension there as well.

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/219)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/common/ProtoReflection.kt` line 229 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/219#-NhTPJBs0UUeU9k1w7HH:-NhTXz5d5Szt54mgHOC8:b-6bzizf) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/2c517cfa2d862aa55cfc833621e13f6c6f1c8869/src/main/kotlin/org/wfanet/measurement/common/ProtoReflection.kt#L229)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

That already exists in com.google.protobuf.kotlin. Not sure why they didn't add the pack extension there as well.
</blockquote></details>

Is there any extra typeUrl checking we want to do in the unpack?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/219)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/common/ProtoReflection.kt` line 229 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/219#-NhTPJBs0UUeU9k1w7HH:-NhTn1lN5CqE6chnSrkg:b-7z06o3) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/2c517cfa2d862aa55cfc833621e13f6c6f1c8869/src/main/kotlin/org/wfanet/measurement/common/ProtoReflection.kt#L229)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Is there any extra typeUrl checking we want to do in the unpack?
</blockquote></details>

The one from com.google.protobuf.kotlin just delegates to `Any.unpack` which checks the type URL.
___
*[`src/test/kotlin/org/wfanet/measurement/common/ProtoReflectionTest.kt` line 78 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/219#-NhTOoa-7hxct9rc3ZC9:-NhTqahDBEmo-ME9BUxW:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/2c517cfa2d862aa55cfc833621e13f6c6f1c8869/src/test/kotlin/org/wfanet/measurement/common/ProtoReflectionTest.kt#L78)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

ideally, all the functions should have tests
</blockquote></details>

Done.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/219)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
