### PR TITLE
Require DNS hostname to be specified for certificate generation macros.

### PR DESCRIPTION
**Pull request by SanjayVas**
This hostname gets set in the Subject Alternative Name (SAN) X.509 v3 extension of the generated certificate. Prior to this change, the value was hard-coded to "localhost".

This also moves the macros to the //build/openssl Bazel package to match the existing convention for build defs that call an external binary.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/21)

### CODE REVIEW

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/21)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[build/openssl/generate_root_certificate_validator.sh, line 71 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/21#-Mfojk3KDMZpiAZrviqS:-Mfojk3KDMZpiAZrviqT:b1nb7gg) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/488c60c92d327cad6a7d77212671c636ba4a06c4/build/openssl/generate_root_certificate_validator.sh#L71)):*
> ```Shell
>   fi
> }
> ```

do you want to also check the value of `X509v3 Subject Alternative Name` here?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/21)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @stevenwarejones and @wangyaopw)

___
*[build/openssl/generate_root_certificate_validator.sh, line 71 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/21#-Mfojk3KDMZpiAZrviqS:-Mfop0Zj4W6VLVZL7CLE:bduph43) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/488c60c92d327cad6a7d77212671c636ba4a06c4/build/openssl/generate_root_certificate_validator.sh#L71)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

do you want to also check the value of `X509v3 Subject Alternative Name` here?
</blockquote></details>

It's checked by `openssl verify` using the `-verify_hostname` option.

**Review by wangyaopw — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/21)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[build/openssl/generate_root_certificate_validator.sh, line 71 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/21#-Mfojk3KDMZpiAZrviqS:-Mfoq3dr6b9O4viZe4wV:b-k488ax) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/488c60c92d327cad6a7d77212671c636ba4a06c4/build/openssl/generate_root_certificate_validator.sh#L71)):*
> ```
>  openssl verify -x509_strict -verbose -CAfile "${cert_file}" -verify_hostname "${HOSTNAME}" "${cert_file}"
> ```
got it

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 8 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/21)* status: 8 of 9 files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[build/openssl/defs.bzl, line 69 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/21#-MfrdrGJ5RR9fA92V2no:-MfrdrGJ5RR9fA92V2np:b-cdjtpn) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/488c60c92d327cad6a7d77212671c636ba4a06c4/build/openssl/defs.bzl#L69)):*
> ```Starlark
>         _location(key),
>         "-x509",
>         "-days 3650",
> ```

ditto below - plus is `3650` intentional here?
___
*[build/openssl/defs.bzl, line 158 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/21#-MfrdYuRAYb79j0g8a-F:-MfrdYuRAYb79j0g8a-G:b-foq8gp) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/488c60c92d327cad6a7d77212671c636ba4a06c4/build/openssl/defs.bzl#L158)):*
> ```Starlark
>         "-out",
>         _location(cert),
>         "-days 365",
> ```

are these rules going to be used for generating short-term use signing keys (possibly ephemeral)... if so, maybe these default days should be way shorter and also a param.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/21)* status: 8 of 9 files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)

___
*[build/openssl/defs.bzl, line 69 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/21#-MfrdrGJ5RR9fA92V2no:-Mfsjf0JDSQ6bXwP3Y5w:b-aqwyxw) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/488c60c92d327cad6a7d77212671c636ba4a06c4/build/openssl/defs.bzl#L69)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

ditto below - plus is `3650` intentional here?
</blockquote></details>

Yes. 10 years is normal for a root cert.
___
*[build/openssl/defs.bzl, line 158 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/21#-MfrdYuRAYb79j0g8a-F:-Mfsjhur8r79aeSW4mqd:btyi0f3) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/488c60c92d327cad6a7d77212671c636ba4a06c4/build/openssl/defs.bzl#L158)):*
> are these rules going to be used for generating short-term use signing keys

No, these macros should only be used for testing certs. Generation of production certificates should be handled using a different process. I went ahead and marked the generated targets as `testonly`.

> maybe these default days should be way shorter and also a param.

I made it an argument. I left the default decently long even for user certs (~1 year) to avoid the likelihood of encountering an expired cached certificate when testing.

These genrules technically don't follow Bazel best practices as the output depends on the current date. I went ahead and added an optional `cache_version` argument in case we need to invalidate all possible cached versions

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/21)* status: 7 of 9 files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[build/openssl/BUILD.bazel, line 7 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/21#-Mg7B2EP0B-j1k-ZxM_L:-Mg7B2EP0B-j1k-ZxM_M:b4x6ctc) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/133a1f405eb04aeae3c57a02d86db090d0dc3451/build/openssl/BUILD.bazel#L7)):*
> ```Starlark
> )
> 
> generate_root_certificate(
> ```

mark this file as `test_only`. not seeing that change
___
*[build/openssl/defs.bzl, line 158 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/21#-MfrdYuRAYb79j0g8a-F:-Mg7BbriAPVx13yZbe2Y:bsaghfl) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/488c60c92d327cad6a7d77212671c636ba4a06c4/build/openssl/defs.bzl#L158)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> are these rules going to be used for generating short-term use signing keys

No, these macros should only be used for testing certs. Generation of production certificates should be handled using a different process. I went ahead and marked the generated targets as `testonly`.

> maybe these default days should be way shorter and also a param.

I made it an argument. I left the default decently long even for user certs (~1 year) to avoid the likelihood of encountering an expired cached certificate when testing.

These genrules technically don't follow Bazel best practices as the output depends on the current date. I went ahead and added an optional `cache_version` argument in case we need to invalidate all possible cached versions
</blockquote></details>

one option could be to pass in start and end dates... set everything to 10 years... but that would just make those tests fail after that amount of time.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/21)* status: 7 of 9 files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)

___
*[build/openssl/BUILD.bazel, line 7 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/21#-Mg7B2EP0B-j1k-ZxM_L:-Mg7H_8p1ZnJuugMdHsX:boyq2g) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/133a1f405eb04aeae3c57a02d86db090d0dc3451/build/openssl/BUILD.bazel#L7)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

mark this file as `test_only`. not seeing that change
</blockquote></details>

The `generate_` macros themselves evaluate to targets that are inherently `testonly`, similar to how `_test` rule targets are inherently `testonly`.

If you tried to depend on the macro target from a non-testonly target, it would give an error. There's no error here since the only things that depend on the macro targets are `sh_test`s.
___
*[build/openssl/defs.bzl, line 158 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/21#-MfrdYuRAYb79j0g8a-F:-Mg7IVUi4SNn-Zl1BZb-:b-kjz33s) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/488c60c92d327cad6a7d77212671c636ba4a06c4/build/openssl/defs.bzl#L158)):*
> set everything to 10 years

Non-root certificates for TLS can't be 10 years. Many implementations limit them to 398 days as a result of a discussion at the CA/Browser Forum.

> one option could be to pass in start and end dates

AFAICT the openssl CLI only allows you to specify a number of days. It always generates certificate where the validity period starts at the current time.

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/21)* status: 7 of 9 files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[build/openssl/defs.bzl, line 158 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/21#-MfrdYuRAYb79j0g8a-F:-MgBGASz1zAqThVcTsnM:b-llrehf) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/488c60c92d327cad6a7d77212671c636ba4a06c4/build/openssl/defs.bzl#L158)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> set everything to 10 years

Non-root certificates for TLS can't be 10 years. Many implementations limit them to 398 days as a result of a discussion at the CA/Browser Forum.

> one option could be to pass in start and end dates

AFAICT the openssl CLI only allows you to specify a number of days. It always generates certificate where the validity period starts at the current time.
</blockquote></details>

Yeah - looks like you can only set the start date using `openssl ca` for self-signed CAs.

**Review by SanjayVas — COMMENTED** [review]
> Dismissed @stevenwarejones from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/21)* status: 7 of 9 files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 7 of 9 files at r1, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/21)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
