### PR TITLE
Add expand_template rule.

### PR DESCRIPTION
**Pull request by SanjayVas**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/188)

**Comment by SanjayVas** [comment]
Depends on #187

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/188)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`build/defs.bzl` line 75 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/188#-NSGkn27C4JeNQLoVGkc:-NSGkn27C4JeNQLoVGkd:b-8d8kzs) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/e203a6b8ff9bfedaa2f3e0e199d136e722f3b745/build/defs.bzl#L75)):*
> ```Starlark
>     )
> 
> expand_template = rule(
> ```

do yu have a PR open using this rule?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/188)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`build/defs.bzl` line 75 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/188#-NSGkn27C4JeNQLoVGkc:-NSHE2GpB5wBq-CLHsSa:b-hor9m) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/e203a6b8ff9bfedaa2f3e0e199d136e722f3b745/build/defs.bzl#L75)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

do yu have a PR open using this rule?
</blockquote></details>

Yes. It's already referenced in this PR: world-federation-of-advertisers/cross-media-measurement#923

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/188)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/188)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

**Review by SanjayVas — COMMENTED** [review]
> Dismissed @stevenwarejones from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/188)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/188)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

**Pull request merged**
