### PR TITLE
Add testing/CommandLineTest. Add captureInMode() into MockitoUtils.

### PR DESCRIPTION
**Pull request by renjiezh**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/147)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/147)* status: all files reviewed, 2 unresolved discussions (waiting on @renjiezh and @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/common/testing/CommandlineToolUtils.kt` line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/147#-N92KjTN2B3m1Wtwv8Ko:-N92KjTN2B3m1Wtwv8Kp:bpzhm7p) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/622b2a2c99f084203bc98e0fef78bb2aa438f324/src/main/kotlin/org/wfanet/measurement/common/testing/CommandlineToolUtils.kt#L26)):*
> ```Kotlin
> import java.security.Permission
> import kotlin.test.assertFailsWith
> ```

Wrap these in a CommandLineTesting object (renaming the file to the same name).

We're trying to avoid having new public non-receiver methods in the global scope.
___
*[`src/main/kotlin/org/wfanet/measurement/common/testing/MockitoUtils.kt` line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/147#-N92MjLo1R67sOxk8HpY:-N92MjLo1R67sOxk8HpZ:b-968egw) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/622b2a2c99f084203bc98e0fef78bb2aa438f324/src/main/kotlin/org/wfanet/measurement/common/testing/MockitoUtils.kt#L37)):*
> ```Kotlin
> 
> /** Captures all values with a parameter [mode] */
> inline fun <reified T, reified M> captureInMode(
> ```

nit: this can probably just be an overload of `verifyAndCapture`



_Code quote:_
```Kotlin
captureInMode
```

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/147)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @riemanli and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/common/testing/CommandlineToolUtils.kt` line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/147#-N92KjTN2B3m1Wtwv8Ko:-N93I7x266Zdr-KcVbJO:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/622b2a2c99f084203bc98e0fef78bb2aa438f324/src/main/kotlin/org/wfanet/measurement/common/testing/CommandlineToolUtils.kt#L26)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Wrap these in a CommandLineTesting object (renaming the file to the same name).

We're trying to avoid having new public non-receiver methods in the global scope.
</blockquote></details>

Done.

**Review by riemanli — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/147)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/147)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/common/testing/CommandlineToolUtils.kt` line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/147#-N92KjTN2B3m1Wtwv8Ko:-N93c3KnCVbJbiQdwSk7:b-bc2l31) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/622b2a2c99f084203bc98e0fef78bb2aa438f324/src/main/kotlin/org/wfanet/measurement/common/testing/CommandlineToolUtils.kt#L26)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think you misunderstood my comment. I was stating that the functions should remain as they were, just wrapped inside of an object. e.g.

```kotlin
object CommandLineTesting {
  fun capturingSystemOut(block: () -> Unit): String {
    //...
  }

  fun assertExitsWith(status: Int, block: () -> Unit) {
    // ...
  }
}
```

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/147)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/common/testing/CommandlineToolUtils.kt` line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/147#-N92KjTN2B3m1Wtwv8Ko:-N93d3Qt-ihIt8WFYb3d:b-atrtej) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/622b2a2c99f084203bc98e0fef78bb2aa438f324/src/main/kotlin/org/wfanet/measurement/common/testing/CommandlineToolUtils.kt#L26)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I think you misunderstood my comment. I was stating that the functions should remain as they were, just wrapped inside of an object. e.g.

```kotlin
object CommandLineTesting {
  fun capturingSystemOut(block: () -> Unit): String {
    //...
  }

  fun assertExitsWith(status: Int, block: () -> Unit) {
    // ...
  }
}
```
</blockquote></details>

Thanks for clarifying. Now I got it.
But I was thinking to wrap these functions up. So that for all our CommandLine tests, we can only call one function like 
```
val output = runCommandLineTest { MeasurementSystem.main(args) }
```
Or you prefer to keep them standalone for flexibility?

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/147)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/common/testing/CommandlineToolUtils.kt` line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/147#-N92KjTN2B3m1Wtwv8Ko:-N94-Zj46iYeZAy8i0iA:b6ozy26) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/622b2a2c99f084203bc98e0fef78bb2aa438f324/src/main/kotlin/org/wfanet/measurement/common/testing/CommandlineToolUtils.kt#L26)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Thanks for clarifying. Now I got it.
But I was thinking to wrap these functions up. So that for all our CommandLine tests, we can only call one function like 
```
val output = runCommandLineTest { MeasurementSystem.main(args) }
```
Or you prefer to keep them standalone for flexibility?
</blockquote></details>

Prefer keeping standalone for flexibility as well as readability (it should be clear exactly what you're trying to verify in a test).

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/147)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @riemanli and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/common/testing/CommandlineToolUtils.kt` line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/147#-N92KjTN2B3m1Wtwv8Ko:-N97oB3r2IwEu2GO_L6v:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/622b2a2c99f084203bc98e0fef78bb2aa438f324/src/main/kotlin/org/wfanet/measurement/common/testing/CommandlineToolUtils.kt#L26)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Prefer keeping standalone for flexibility as well as readability (it should be clear exactly what you're trying to verify in a test).
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/147)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
Needs tests

> Reviewed 1 of 3 files at r1, 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/147#-:-N9D35kT8df_O-dJKVEj:b-we5z6v)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kungfucraig)

**Review by renjiezh — COMMENTED** [review]
Added unit test for CommandLineTesting utils.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/147#-:-N9DeCo0-xaRfdH-xhGe:b-vbthsy)* status: 5 of 7 files reviewed, all discussions resolved (waiting on @kungfucraig)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/147)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kungfucraig)

**Pull request merged**
