### PR TITLE
Folder structure and main files for this repo - Extracted from c-m-m repo

### PR DESCRIPTION
**Pull request by uakyol**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/1)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/1)* status: 0 of 117 files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @uakyol)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/1#-McGyeefECbwbsvSZIUk:-McGyeefECbwbsvSZIUl:b-h6iyzn) (no related file):*
Similar to the discussion on https://github.com/world-federation-of-advertisers/consent-signaling-client/pull/1, the first PR should set up the common repo boilerplate. e.g. https://github.com/world-federation-of-advertisers/any-sketch-java/pull/1.

This way we can get linting and checks in place prior to any real code being added.

---

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 46 of 117 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/1)* status: 46 of 117 files reviewed, 3 unresolved discussions (waiting on @uakyol)

___
*[build/io_bazel_rules_docker/repo.bzl, line 20 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/1#-McKg3vq-ts-29RJuM2j:-McKg3vrCFpbN4jhPj1D:bcmrg2p) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/f5c592a2802bbefc5881318efd0d584f82126d72/build/io_bazel_rules_docker/repo.bzl#L20)):*
> ```Starlark
> 
> _RELEASE_URL = "https://github.com/bazelbuild/rules_docker/releases/download/v{version}/rules_docker-v{version}.tar.gz"
> _ARCHIVE_URL = "https://github.com/bazelbuild/rules_docker/archive/{commit}.tar.gz"
> ```

Would it make sense to generalize this to handle any old github repository? Seems like a lot of the `http_archive` rules are downloading things from GH. In other words:

```
def github_repo(repo, name, sha256, version = None, commit = None)
  ...
```

@sanjayvas 
___
*[imports/kotlin/com/nhaarman/mockitokotlin2/BUILD.bazel, line 5 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/1#-McKgifVBbfCZ9icQudG:-McKgifVBbfCZ9icQudH:b12guh2) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/f5c592a2802bbefc5881318efd0d584f82126d72/imports/kotlin/com/nhaarman/mockitokotlin2/BUILD.bazel#L5)):*
> ```Starlark
> alias(
>     name = "mockitokotlin2",
>     actual = "@maven//:com_nhaarman_mockitokotlin2_mockito_kotlin",
> ```

I believe that this is now part of Mockito officially and should be updated -- see https://github.com/world-federation-of-advertisers/panel-exchange-client/issues/8

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/1)* status: 46 of 117 files reviewed, 3 unresolved discussions (waiting on @efoxepstein and @uakyol)

___
*[build/io_bazel_rules_docker/repo.bzl, line 20 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/1#-McKg3vq-ts-29RJuM2j:-McKt32y8VUIkZQ3OkIe:b-4nfbgd) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/f5c592a2802bbefc5881318efd0d584f82126d72/build/io_bazel_rules_docker/repo.bzl#L20)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Would it make sense to generalize this to handle any old github repository? Seems like a lot of the `http_archive` rules are downloading things from GH. In other words:

```
def github_repo(repo, name, sha256, version = None, commit = None)
  ...
```

@sanjayvas 
</blockquote></details>

Yeah, when I wrote this I wasn't 100% certain on how consistent GitHub release archives were. This could definitely be made more generic, taking organization and repo name as args.

What I learned is that if your release uses semantic versioning with a `v` prefix in the release/tag name, this prefix will exist in the archive filename but *not* in the folder/prefix.

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 1 of 117 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/1)* status: 46 of 117 files reviewed, 3 unresolved discussions (waiting on @efoxepstein and @uakyol)

___
*[imports/kotlin/com/nhaarman/mockitokotlin2/BUILD.bazel, line 5 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/1#-McKgifVBbfCZ9icQudG:-McKvAmNDoMl__eY-J-E:bocv8n3) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/f5c592a2802bbefc5881318efd0d584f82126d72/imports/kotlin/com/nhaarman/mockitokotlin2/BUILD.bazel#L5)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I believe that this is now part of Mockito officially and should be updated -- see https://github.com/world-federation-of-advertisers/panel-exchange-client/issues/8
</blockquote></details>

We have a similar filing in https://github.com/world-federation-of-advertisers/cross-media-measurement/issues/48. Given that I believe this also requires all of the code that references this to switch namespaces, I think we should handle that separately after this initial extraction.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 47 of 117 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/1)* status: 48 of 117 files reviewed, 5 unresolved discussions (waiting on @efoxepstein and @uakyol)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/1#-McQ5Gsh6zQmZbuEMeTU:-McQ5Gsh6zQmZbuEMeTV:bvgqnu6) (no related file):*
So I'm concerned that we're losing all the history for these files when copying them over. I'm considering instead doing what I did when splitting up the subtrees: using a combination of the `git-subtree` command and message rewriting to update issue references. This would be a first pass, followed by cleaning up all the things that we don't actually want in this repo.

@efoxepstein wdyt?

---
___
*[WORKSPACE, line 66 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/1#-McQ2sx7AjptLPYhQ2gu:-McQ2sx7AjptLPYhQ2gv:bxev3bq) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/d0972c8284a5fe820eceb0d01e3861088de91654/WORKSPACE#L66)):*
> ```
> "legacy-1.4.0-rc4",
> ```
Note that you'll need to work with @tristanvuong2021 to reconcile this PR with https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/109
___
*[imports/java/com/google/cloud/spanner/BUILD.bazel, line 10 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/1#-McQ2I7JApBTQS9s4RDT:-McQ2I7JApBTQS9s4RDU:b-6xdu6z) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/d0972c8284a5fe820eceb0d01e3861088de91654/imports/java/com/google/cloud/spanner/BUILD.bazel#L10)):*
> ```
>         # Also export transitive deps com.google.api.core and com.google.api.gax
>         # to fix IntelliJ -- it doesn't pick up on these by itself.
> ```
I don't think we actually need these anymore, at least if we're using a sufficiently recent version of rules_kotlin. If you end up having an issue in IntelliJ, you can usually solve it by partially syncing the relevant target with the Bazel plugin.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/1)* status: 48 of 117 files reviewed, 5 unresolved discussions (waiting on @efoxepstein and @uakyol)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/1#-McQ5Gsh6zQmZbuEMeTU:-McRW4kF2XSPYFuMBsbx:b-da6q8k) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

So I'm concerned that we're losing all the history for these files when copying them over. I'm considering instead doing what I did when splitting up the subtrees: using a combination of the `git-subtree` command and message rewriting to update issue references. This would be a first pass, followed by cleaning up all the things that we don't actually want in this repo.

@efoxepstein wdyt?
</blockquote></details>

I was able to update my git-filter-repo script to do this. I think what would be best is creating a PR in the cross-media-measurement repo that updates ProtoUtilsTest to use the testing proto. Then I can import the rewritten commits. After that, you can do a subsequent PR for this repo to change the workspace name and remove Duchy ID stuff. Sound good?

---

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/1)* status: 48 of 117 files reviewed, 5 unresolved discussions (waiting on @efoxepstein, @SanjayVas, and @uakyol)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/1#-McQ5Gsh6zQmZbuEMeTU:-Mc_YBng7Duk-xKJY-MF:boun2ui) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I was able to update my git-filter-repo script to do this. I think what would be best is creating a PR in the cross-media-measurement repo that updates ProtoUtilsTest to use the testing proto. Then I can import the rewritten commits. After that, you can do a subsequent PR for this repo to change the workspace name and remove Duchy ID stuff. Sound good?
</blockquote></details>

This plan sounds fine to me. I'm also less concerned about losing Git history (which is only hypothetically useful) and more concerned about getting the common repos all set up quickly (which will definitely be useful).

---

**Comment by SanjayVas** [comment]
Filtered commits imported directly instead.

**Pull request closed without merging**
