### PR TITLE
Fix command line duration parsing

### PR DESCRIPTION
**Pull request by tristanvuong2021**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/174)

### CODE REVIEW

**Review by renjiezh — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/174#-:-NJl3ke_8mTU_0camzCG:bnfp4nl)* status: 0 of 2 files reviewed, all discussions resolved

**Review by kungfucraig — COMMENTED** [review]
Please add a test that exhibits the problem you fixed.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/174#-:-NJl7gqU41QLxefROPan:bco2d4n)* status: 0 of 2 files reviewed, all discussions resolved

**Review by duliomatos1 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/174#-:-NJltbXS2H9ezPgGI8cF:bnfp4nl)* status: 0 of 4 files reviewed, all discussions resolved

**Review by tristanvuong2021 — COMMENTED** [review]
> Reviewed 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/174)* status: 2 of 4 files reviewed, all discussions resolved

**Review by tristanvuong2021 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/174)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @tristanvuong2021)

**Review by tristanvuong2021 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/174)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/174)* status: all files reviewed, 1 unresolved discussion

___
*[`src/main/kotlin/org/wfanet/measurement/common/CommandLines.kt` line 42 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/174#-NL3Te3S6hrLwHRL8Mha:-NL3Te3S6hrLwHRL8Mhb:b-eiyy5y) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/2ae3aeb3e51f2f0b16d6b833bad3bca9e8d7d35c/src/main/kotlin/org/wfanet/measurement/common/CommandLines.kt#L42)):*
> ```Kotlin
>   command: Runnable,
>   args: Array<String>,
>   format: DurationFormat = DurationFormat.HUMAN_READABLE
> ```

What is this for? Where do we want to use anything other than HUMAN_READABLE for command-line duration parsing?

**Comment by tristanvuong2021** [comment]
*[`src/main/kotlin/org/wfanet/measurement/common/CommandLines.kt` line 42 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/174#-NL3Te3S6hrLwHRL8Mha:-NL3dSSfCHLGdfn0VXKV:b-unn506) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/2ae3aeb3e51f2f0b16d6b833bad3bca9e8d7d35c/src/main/kotlin/org/wfanet/measurement/common/CommandLines.kt#L42)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

What is this for? Where do we want to use anything other than HUMAN_READABLE for command-line duration parsing?
</blockquote></details>

This was for the Reporting tool.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/174)* status: all files reviewed, 1 unresolved discussion

___
*[`src/main/kotlin/org/wfanet/measurement/common/CommandLines.kt` line 42 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/174#-NL3Te3S6hrLwHRL8Mha:-NL7FtgD5c_pUOuX_rYi:b96or8f) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/2ae3aeb3e51f2f0b16d6b833bad3bca9e8d7d35c/src/main/kotlin/org/wfanet/measurement/common/CommandLines.kt#L42)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

This was for the Reporting tool.
</blockquote></details>

Why wouldn't we use HUMAN_READABLE there as well and be consistent in all of our CLIs?

**Pull request merged**
