### PR TITLE
Add key storage and cryptor interfaces with skeleton Tink implementations.

### PR DESCRIPTION
**Pull request by SanjayVas**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/46)

### CODE REVIEW

**Review by efoxepstein — COMMENTED** [review]
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/46)* status: all files reviewed, 4 unresolved discussions (waiting on @corbantek, @SanjayVas, and @stevenwarejones)

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/46)* status: all files reviewed, 4 unresolved discussions (waiting on @corbantek, @efoxepstein, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/KeyStorageProvider.kt, line 33 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/46#-MlvDGUK6zQecyPs2eG6:-Mlvd7oj4YM1vKeN7hBV:b-gbfsy1) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/b8bfc76d71bec99ac8d25c23e621bd05973d3cff/src/main/kotlin/org/wfanet/measurement/common/crypto/KeyStorageProvider.kt#L33)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

OOC, why String? Isn't the type implementation dependent? Should we use ByteString?
</blockquote></details>

The type parameter refers to the blob key context for the `Store`. The context is used when generating blob keys. In this case, we just want to specify the blob key itself.

`Store`s always store `ByteString`s.
___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/PrivateKeyStore.kt, line 17 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/46#-MlvDYqm8zm5SsuObbYE:-Mlw15lD5INvHHaqYd-f:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/b8bfc76d71bec99ac8d25c23e621bd05973d3cff/src/main/kotlin/org/wfanet/measurement/common/crypto/PrivateKeyStore.kt#L17)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

KDoc please
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/tink/KeyHandle.kt, line 24 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/46#-MlvDv8O1kedI4w57MBw:-Mlw1ChJACFli4KAymrM:bahtgb3) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/b8bfc76d71bec99ac8d25c23e621bd05973d3cff/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/KeyHandle.kt#L24)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Is this just to provide fields? Or do you ever need to treat things generically as KeyHandles?
</blockquote></details>

Yes, just to provide fields.
___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/KeyHandle.kt, line 20 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/46#-MlvCple7qLYcaiKnIg_:-Mlw0vNl5fmyo7krz4rU:b-qwzrii) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/2a043acae4272029112b609c1cf2892906bf8695/src/main/kotlin/org/wfanet/measurement/common/crypto/KeyHandle.kt#L20)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Add `Hybrid` to name? Since we have ElGamal and EcCommutativeCipher and AES and keys for signatures -- lots of types of keys, so probably best to be explicit where possible?
</blockquote></details>

I just dropped this interface as it wasn't useful. It incorrectly held the key ID (blob key for the private key).

**Review by corbantek — APPROVED** [review]
> Reviewed 2 of 13 files at r3, 3 of 7 files at r4, 4 of 6 files at r8, 2 of 3 files at r13, 2 of 2 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/46)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/46)* status: all files reviewed, 3 unresolved discussions (waiting on @stevenwarejones)

**Review by corbantek — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/46#-:-Mm0_qu21qT8XXJek45g:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by efoxepstein — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/46)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
