### PR TITLE
Yield in Throttler.loopOnReady

### PR DESCRIPTION
**Pull request by efoxepstein**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/41)

### CODE REVIEW

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/41)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @stevenwarejones, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/common/throttler/Throttler.kt, line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/41#-MkyJksv5Tx4566zKTqx:-MkyJksv5Tx4566zKTqy:b-psww1o) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/88ca9580c6beab1d3bde581ba23fbff16628304c/src/main/kotlin/org/wfanet/measurement/common/throttler/Throttler.kt#L33)):*
> ```Kotlin
>     while (true) {
>       onReady(block)
>       yield()
> ```

I think checking isActive is more clear since we have a while loop, but this still gets the job done.

**Review by wangyaopw — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/41)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @stevenwarejones)

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/41)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @SanjayVas, @stevenwarejones, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/common/throttler/Throttler.kt, line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/41#-MkyJksv5Tx4566zKTqx:-Ml0MOs90ihcBLuZJJV-:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/88ca9580c6beab1d3bde581ba23fbff16628304c/src/main/kotlin/org/wfanet/measurement/common/throttler/Throttler.kt#L33)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I think checking isActive is more clear since we have a while loop, but this still gets the job done.
</blockquote></details>

Done

**Comment by efoxepstein** [comment]
Fixed #42.

**Review by wangyaopw — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/41)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas and @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/41)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/41)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @efoxepstein)

**Pull request merged**
