### PR TITLE
perf: Add connection pool to configure connection lifecycle.

### PR DESCRIPTION
**Pull request by tristanvuong2021**
The pool will close connections that are idle for too long.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/289)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/289)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/postgres/PostgresConnectionFactories.kt` line 38 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/289#-ODTJhm2DwcDEiXTw6g4:-ODTJhm2DwcDEiXTw6g5:b-crtq45) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/335909ecbede077e63899043cb6536bf08d487c8/src/main/kotlin/org/wfanet/measurement/gcloud/postgres/PostgresConnectionFactories.kt#L38)):*
> ```Kotlin
>           .option(ConnectionFactoryOptions.DATABASE, flags.database)
>           .option(ConnectionFactoryOptions.HOST, flags.cloudSqlInstance)
>           .option(ConnectionFactoryOptions.STATEMENT_TIMEOUT, Duration.ofSeconds(120))
> ```

Have all of these values come from flags.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/289)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/postgres/PostgresConnectionFactories.kt` line 38 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/289#-ODTJhm2DwcDEiXTw6g4:-ODTNVSL902SCHIU_giu:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/335909ecbede077e63899043cb6536bf08d487c8/src/main/kotlin/org/wfanet/measurement/gcloud/postgres/PostgresConnectionFactories.kt#L38)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Have all of these values come from flags.
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/289)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/postgres/PostgresFlags.kt` line 50 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/289#-ODTazO-9lKvP5cqGJIY:-ODTazO06R0MAVaBQRT5:bvsqdni) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/8961386147d3f9d6f060a07faa1a3f6f3fc5cde9/src/main/kotlin/org/wfanet/measurement/gcloud/postgres/PostgresFlags.kt#L50)):*
> ```Kotlin
>     required = false,
>   )
>   var statementTimeoutSeconds: Long = 120
> ```

Use Duration for these



_Suggestion:_
```Kotlin
    names = ["--statement-timeout"],
    description = ["Statement timeout"],
    required = false,
    defaultValue = "120s",
  )
  lateinit var statementTimeout: Duration
```

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/289)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/postgres/PostgresFlags.kt` line 50 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/289#-ODTazO-9lKvP5cqGJIY:-ODgCetdCWiT94L7ngI8:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/8961386147d3f9d6f060a07faa1a3f6f3fc5cde9/src/main/kotlin/org/wfanet/measurement/gcloud/postgres/PostgresFlags.kt#L50)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use Duration for these
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/289)* status: all files reviewed, 2 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/postgres/PostgresFlags.kt` line 51 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/289#-ODhUhCIEMSm4TIAKesq:-ODhUhCIEMSm4TIAKesr:bererv2) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/4c013c6e79ddcfb1d65cb83f8a5be8f65a7b46fe/src/main/kotlin/org/wfanet/measurement/gcloud/postgres/PostgresFlags.kt#L51)):*
> ```Kotlin
>     required = false,
>   )
>   var statementTimeout: Duration = Duration.ofSeconds(120)
> ```

Don't assign the default in Kotlin. Make these lateinit vars and use defaultValue from the Option annotation



_Code quote:_
```Kotlin
= Duration.ofSeconds(120)
```
___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/postgres/PostgresFlags.kt` line 55 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/289#-ODhUZ1iACz1jaNXWIkU:-ODhUZ1iACz1jaNXWIkV:undefined) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/4c013c6e79ddcfb1d65cb83f8a5be8f65a7b46fe/src/main/kotlin/org/wfanet/measurement/gcloud/postgres/PostgresFlags.kt#L55)):*
> ```Kotlin
> 
>   @CommandLine.Option(
>     names = ["--max-idle-time-minutes"],
> ```





_Suggestion:_
```Kotlin
--max-idle-time
```

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/289)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/postgres/PostgresFlags.kt` line 51 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/289#-ODhUhCIEMSm4TIAKesq:-ODhX_TR8jXYWnVwF39F:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/4c013c6e79ddcfb1d65cb83f8a5be8f65a7b46fe/src/main/kotlin/org/wfanet/measurement/gcloud/postgres/PostgresFlags.kt#L51)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Don't assign the default in Kotlin. Make these lateinit vars and use defaultValue from the Option annotation
</blockquote></details>

Done.

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/289)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/postgres/PostgresFlags.kt` line 55 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/289#-ODhUZ1iACz1jaNXWIkU:-ODhXeu90X-Mx-osNuE7:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/4c013c6e79ddcfb1d65cb83f8a5be8f65a7b46fe/src/main/kotlin/org/wfanet/measurement/gcloud/postgres/PostgresFlags.kt#L55)):*
> ```Kotlin
> 
>   @CommandLine.Option(
>     names = ["--max-idle-time-minutes"],
> ```

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/289)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/postgres/PostgresFlags.kt` line 50 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/289#-ODhYZe17wC0EY9afJ2q:-ODhYZe17wC0EY9afJ2r:b-z828p0) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/54e00e4016992cbebd1a09e8b6689d39bf1d2afd/src/main/kotlin/org/wfanet/measurement/gcloud/postgres/PostgresFlags.kt#L50)):*
> ```Kotlin
>     description = ["Statement timeout duration."],
>     required = false,
>     defaultValue = "PT120S",
> ```

This should be using human readable durations. I've stated in a previous PR that `org.wfanet.measurement.common.DurationFormat` shouldn't exist and it should always use the human-readable format, i.e. that https://github.com/world-federation-of-advertisers/common-jvm/pull/174 should never have been merged.



_Suggestion:_
```Kotlin
120s
```

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/289)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/postgres/PostgresFlags.kt` line 50 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/289#-ODhYZe17wC0EY9afJ2q:-ODhnTok8W2PZ8wyseFN:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/54e00e4016992cbebd1a09e8b6689d39bf1d2afd/src/main/kotlin/org/wfanet/measurement/gcloud/postgres/PostgresFlags.kt#L50)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This should be using human readable durations. I've stated in a previous PR that `org.wfanet.measurement.common.DurationFormat` shouldn't exist and it should always use the human-readable format, i.e. that https://github.com/world-federation-of-advertisers/common-jvm/pull/174 should never have been merged.
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/289)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/postgres/PostgresFlags.kt` line 69 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/289#-ODi5mCT1m7U_eBUiMYe:-ODi5mCU2X-Lqnf9r3tZ:b-5m3l3w) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/c076d6c8d54081d20dcd7dbea6c9b0d66d205f3a/src/main/kotlin/org/wfanet/measurement/gcloud/postgres/PostgresFlags.kt#L69)):*
> ```Kotlin
>     required = false,
>   )
>   var maxPoolSize: Int = 16
> ```

Same here re: not setting defaults in Kotlin when they can be set using defaultValue



_Suggestion:_
```Kotlin
var maxPoolSize by Delegates.notNull<Int>()
```

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/289)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/postgres/PostgresFlags.kt` line 69 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/289#-ODi5mCT1m7U_eBUiMYe:-ODiMXawAz9XzHNUEJqW:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/c076d6c8d54081d20dcd7dbea6c9b0d66d205f3a/src/main/kotlin/org/wfanet/measurement/gcloud/postgres/PostgresFlags.kt#L69)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Same here re: not setting defaults in Kotlin when they can be set using defaultValue
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/289)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 5 files at r1, 3 of 4 files at r4, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/289)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
