### PR TITLE
Update java base images to use Debian 11 nonroot images

### PR DESCRIPTION
**Pull request by oliver-amzn**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/39)

### CODE REVIEW

**Review by SanjayVas — APPROVED** [review]
Can you also indicate that this update switches to images based on Debian 11?

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/39#-:-MkrhgoS3c2L5Ms-0Pc6:b-djuwlr)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @efoxepstein and @wangyaopw)

___
*[build/io_bazel_rules_docker/base_images.bzl, line 38 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/39#-MkrgB-h06HJAc7UK7yj:-MkrgB-iA9p0NiCTi7qJ:b-byi48m) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/c56aeff31e36f503b0d863e35368abe9a62ddadb/build/io_bazel_rules_docker/base_images.bzl#L38)):*
> ```
> distroless/java
> ```
I was initially surprised this worked. I assumed this would have to be `distroless/java-debian11`. Turns out that they made Debian 11 the default now, such that `java:11-nonroot` is the same as `java-debian11-11-nonroot`.

**Review by oliver-amzn — COMMENTED** [review]
Done

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/39#-:-MkrjbPE-fco7kImwP7r:bb6un1j)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @efoxepstein and @wangyaopw)

___
*[build/io_bazel_rules_docker/base_images.bzl, line 38 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/39#-MkrgB-h06HJAc7UK7yj:-MkrjUtwE3TES4U5Nl0f:bt3f0xz) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/c56aeff31e36f503b0d863e35368abe9a62ddadb/build/io_bazel_rules_docker/base_images.bzl#L38)):*
> java-debian11-11-nonroot

I guess using `java-debian11-11-nonroot` makes it more explicit what base distro you're pulling in so I'd prefer to keep it that way unless there's a good argument against it.

**Review by SanjayVas — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/39)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @oliver-amzn, and @wangyaopw)

___
*[build/io_bazel_rules_docker/base_images.bzl, line 38 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/39#-MkrgB-h06HJAc7UK7yj:-Mkrl9vd7O4lBW97csN2:b-2cxe6x) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/c56aeff31e36f503b0d863e35368abe9a62ddadb/build/io_bazel_rules_docker/base_images.bzl#L38)):*
<details><summary><i>Previously, oliver-amzn (Oliver) wrote…</i></summary><blockquote>

> java-debian11-11-nonroot

I guess using `java-debian11-11-nonroot` makes it more explicit what base distro you're pulling in so I'd prefer to keep it that way unless there's a good argument against it.

</blockquote></details>

I'd suggest whichever you choose, match the `repository` attr to what you mention in the comment. If you want to be explicit about using java-debian11 in the comment, then update the attr to be `distroless/java-debian11`

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/39)* status: all files reviewed, 1 unresolved discussion (waiting on @oliver-amzn and @wangyaopw)

**Review by wangyaopw — APPROVED** [review]

**Review by wangyaopw — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/39)* status: all files reviewed, 1 unresolved discussion (waiting on @oliver-amzn)

**Review by oliver-amzn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/39)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @SanjayVas, and @wangyaopw)

___
*[build/io_bazel_rules_docker/base_images.bzl, line 38 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/39#-MkrgB-h06HJAc7UK7yj:-Mks7iFG5jL_e2M42UTq:b4rumvk) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/c56aeff31e36f503b0d863e35368abe9a62ddadb/build/io_bazel_rules_docker/base_images.bzl#L38)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I'd suggest whichever you choose, match the `repository` attr to what you mention in the comment. If you want to be explicit about using java-debian11 in the comment, then update the attr to be `distroless/java-debian11`
</blockquote></details>

Ohhh, good catch, I totally overlooked that. Yes, the repo is `distroless/java-debian11` - fixed that, thank you!

**Review by oliver-amzn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/39)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @SanjayVas, and @wangyaopw)

___
*[build/io_bazel_rules_docker/base_images.bzl, line 38 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/39#-MkrgB-h06HJAc7UK7yj:-MksAxTa0V2qV-f3y3Oh:b-g4r1do) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/c56aeff31e36f503b0d863e35368abe9a62ddadb/build/io_bazel_rules_docker/base_images.bzl#L38)):*
<details><summary><i>Previously, oliver-amzn (Oliver) wrote…</i></summary><blockquote>

Ohhh, good catch, I totally overlooked that. Yes, the repo is `distroless/java-debian11` - fixed that, thank you!
</blockquote></details>

And this probably worked cause they push all the images to all the repos so the sha was there.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/39)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliver-amzn)

**Pull request merged**
