### PR TITLE
s3client fixes

### PR DESCRIPTION
**Pull request by stevenwarejones**
fixes encoding of the hash to match how amazon computes it

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/108)

### CODE REVIEW

**Review by efoxepstein — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/108)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @robinsons, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/aws/s3/S3StorageClient.kt` line 89 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/108#-N0co29n8M41IyUNAf1c:-N0co29n8M41IyUNAf1d:b-hfrwtu) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/dd30678c3d25864255e0dc351ac98f8b9f96f17b/src/main/kotlin/org/wfanet/measurement/aws/s3/S3StorageClient.kt#L89)):*
> ```Kotlin
>       .map { (i, bytes) ->
>         val digest = MessageDigest.getInstance("MD5")
>         val md5 = String(Base64.getEncoder().encode(digest.digest(bytes.toByteArray())))
> ```

Is the only change here using base64 instead of hex?
___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/spanner/testing/SpannerEmulatorMain.kt` line 66 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/108#-N0cnjSI7vs68OizdWFb:-N0cnjSI7vs68OizdWFc:b8jjcf) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/dd30678c3d25864255e0dc351ac98f8b9f96f17b/src/main/kotlin/org/wfanet/measurement/gcloud/spanner/testing/SpannerEmulatorMain.kt#L66)):*
> ```Kotlin
>           emulatorHost
>         )
>         .use { spanner ->
> ```

Unrelated changes?

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/108)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @efoxepstein, @robinsons, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/aws/s3/S3StorageClient.kt` line 89 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/108#-N0co29n8M41IyUNAf1c:-N0esOPs9WaNp2GQHI6f:b-6b7cg0) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/dd30678c3d25864255e0dc351ac98f8b9f96f17b/src/main/kotlin/org/wfanet/measurement/aws/s3/S3StorageClient.kt#L89)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Is the only change here using base64 instead of hex?
</blockquote></details>

yeah - thats the only real change other than not using a forEach to update the digest.
___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/spanner/testing/SpannerEmulatorMain.kt` line 66 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/108#-N0cnjSI7vs68OizdWFb:-N0esXeUBwtZ2Wb_ZR31:bhf8gnu) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/dd30678c3d25864255e0dc351ac98f8b9f96f17b/src/main/kotlin/org/wfanet/measurement/gcloud/spanner/testing/SpannerEmulatorMain.kt#L66)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Unrelated changes?
</blockquote></details>

this is just the linter

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/108)* status: all files reviewed, 1 unresolved discussion (waiting on @robinsons, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/aws/s3/S3StorageClient.kt` line 89 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/108#-N0co29n8M41IyUNAf1c:-N0fCt6O10t_WuXSraLy:b4ljjfs) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/dd30678c3d25864255e0dc351ac98f8b9f96f17b/src/main/kotlin/org/wfanet/measurement/aws/s3/S3StorageClient.kt#L89)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

yeah - thats the only real change other than not using a forEach to update the digest.
</blockquote></details>

So one issue we've encountered in production is that the JVM GC is running every second and really struggling to keep up due to byte arrays created by storage clients. I'll approve as is but we might want to consider sticking to the original technique, which doesn't copy the bytes into a separate byte array.

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/108)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @efoxepstein, @robinsons, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/aws/s3/S3StorageClient.kt` line 89 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/108#-N0co29n8M41IyUNAf1c:-N0fnq6UBPdF6NwSxrg7:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/dd30678c3d25864255e0dc351ac98f8b9f96f17b/src/main/kotlin/org/wfanet/measurement/aws/s3/S3StorageClient.kt#L89)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I'm actually going to be a bit stronger and block on this part of the change. The `asReadOnlyByteBufferList` call was specifically to avoid extra copies, leveraging the fact that the digest can be computed piecemeal without needing all of the bytes at once.
</blockquote></details>

Done.

**Pull request merged**
