### PR TITLE
Set up wfa_common_jvm workspace.

### PR DESCRIPTION
**Pull request by SanjayVas**
* Add .bazelrc with compiler/environment config.
* Remove files that are specific to the Measurement System (e.g. utils for Duchies).

TODO:
* Adjust build target visibility.
  * Remove references to packages that aren't in this workspace.
  * Make most targets public.
* Drop deps that aren't used by this workspace.
* Move test protos to the appropriate location.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/3)

### CODE REVIEW

**Review by efoxepstein — APPROVED** [review]
> Reviewed 22 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/3)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[build/cue/defs.bzl, line 56 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/3#-Md1ptOp0gIBBWbUYnei:-Md1ptOp0gIBBWbUYnej:b89tvlc) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/e69e725bcbed50b71b5f70c536009569b600df31/build/cue/defs.bzl#L56)):*
> ```Starlark
> )
> 
> def cue_string_field(name, src, identifier, package = None, **kwargs):
> ```

Does Cue stuff belong in `common-jvm`? I agree that it's common and I don't have a better home for it and I agree that all our binaries are JVM-based... but thought I'd double check that this makes sense.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/3)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

___
*[build/cue/defs.bzl, line 56 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/3#-Md1ptOp0gIBBWbUYnei:-Md2tKk3AJgLgi9jgyPa:b-569aag) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/e69e725bcbed50b71b5f70c536009569b600df31/build/cue/defs.bzl#L56)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Does Cue stuff belong in `common-jvm`? I agree that it's common and I don't have a better home for it and I agree that all our binaries are JVM-based... but thought I'd double check that this makes sense.
</blockquote></details>

Probably not. Removing it from here is covered by the TODO for dropping things this repo doesn't use. As much as we loath having an explosion of repos, it probably belongs in its own `rules_cue` repo.

This file was only touched in this PR to update the workspace name.

**Review by efoxepstein — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/3)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

___
*[build/cue/defs.bzl, line 56 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/3#-Md1ptOp0gIBBWbUYnei:-Md2vDI81YV15W8WV6Re:b-hfghm4) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/e69e725bcbed50b71b5f70c536009569b600df31/build/cue/defs.bzl#L56)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Probably not. Removing it from here is covered by the TODO for dropping things this repo doesn't use. As much as we loath having an explosion of repos, it probably belongs in its own `rules_cue` repo.

This file was only touched in this PR to update the workspace name.
</blockquote></details>

Sounds good

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
1. Whats the philosophy on which protos go in this repo? Just config and testing? Panel-client currently has additional proto dependencies on measurement: https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/b5e60f17d2cd48ef0fdae089a458fac7e599afd3/src/main/kotlin/org/wfanet/panelmatch/client/deploy/BUILD.bazel#L9
2. I'd love to see `wfa_measurement_system//src/main/kotlin/org/wfanet/measurement/storage:client` moved here as well. https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/8a80df415796058aad77548895657fa82dbb8f73/src/main/kotlin/org/wfanet/panelmatch/client/storage/BUILD.bazel#L15

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/3#-:-Md3chMM5l-BsBkDfcwg:b-oi76nx)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/common/identity/BUILD.bazel, line 12 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/3#-Md3cEelEru_QBLFQz2n:-Md3cEem4iw8sOGT507F:b-5yvpqp) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/e69e725bcbed50b71b5f70c536009569b600df31/src/main/kotlin/org/wfanet/measurement/common/identity/BUILD.bazel#L12)):*
> ```Starlark
>     srcs = glob(["*.kt"]),
>     deps = [
>         "//src/main/kotlin/org/wfanet/measurement/common",
> ```

shouldn't this repo not depend on any of the other repos?

**Review by SanjayVas — COMMENTED** [review]
> Whats the philosophy on which protos go in this repo?

Just the ones that are depended upon by the JVM targets here. As mentioned in the TODO, the protos in this repo should be moved to a different package. The intent is to not have anything specific to the CMMS in here (e.g. nothing referencing the CMMS public API, nor Kingdoms/Duchies).

> Panel-client currently has additional proto dependencies on measurement.

That looks like it's depending on a proto library from the cross-media-measurement-api repo. The language-specific rule targets (e.g. `kt_jvm_grpc_library`) need not be shared, and can trivially be redefined in any repo that needs them. The opposite approach is to define language-specific targets for every `proto_library` target in the same repo as the `proto_library` target, but we've so far chosen not to do that.

> I'd love to see wfa_measurement_system//src/main/kotlin/org/wfanet/measurement/storage:client moved here as well.

It is here. I imported the filtered commits for the `common`, `gcloud`, and `storage` subtrees from the cross-media-measurement repo to this one.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/3#-:-Md3hdJr-82PkV-t1ncN:bexhdea)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/common/identity/BUILD.bazel, line 12 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/3#-Md3cEelEru_QBLFQz2n:-Md3hRlX9JeHtkogFz8V:biujba3) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/e69e725bcbed50b71b5f70c536009569b600df31/src/main/kotlin/org/wfanet/measurement/common/identity/BUILD.bazel#L12)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

shouldn't this repo not depend on any of the other repos?
</blockquote></details>

It doesn't? That's a local repo target label.

There's a TODO mentioned in the commit message that covers dropping all the unused deps from the WORKSPACE.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 22 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/3)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
