### PR TITLE
Add tool library for updating Spanner schema using Liquibase.

### PR DESCRIPTION
**Pull request by SanjayVas**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/109)

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/109)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/spanner/tools/UpdateSchema.kt` line 47 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/109#-N1Q97315eDMcgVJyLgv:-N1Q97315eDMcgVJyLgw:bdfer6x) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/310ae8326f968468b55c2a9d5566be19ea3032d3/src/main/kotlin/org/wfanet/measurement/gcloud/spanner/tools/UpdateSchema.kt#L47)):*
> ```Kotlin
>     val connectionString =
>       if (flags.emulatorHost == null) {
>         "jdbc:cloudspanner:/projects/${flags.projectName}/instances/${flags.instanceName}/" +
> ```

Maybe `val databasePath = "projects/.../instances/.../databases/..."` so you can reuse it between the two branches here (and also make it more compact).

That could even be a property on `SpannerFlags`.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/109)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/spanner/tools/UpdateSchema.kt` line 47 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/109#-N1Q97315eDMcgVJyLgv:-N1eGlPNBJH8vDG6-a75:b-j06bww) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/310ae8326f968468b55c2a9d5566be19ea3032d3/src/main/kotlin/org/wfanet/measurement/gcloud/spanner/tools/UpdateSchema.kt#L47)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Maybe `val databasePath = "projects/.../instances/.../databases/..."` so you can reuse it between the two branches here (and also make it more compact).

That could even be a property on `SpannerFlags`.
</blockquote></details>

Done, and moved to `SpannerFlags`.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 3 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/109)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/109)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein)

**Review by efoxepstein — APPROVED** [review]
> Reviewed 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/109)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
