### PR TITLE
Add X509Certificate.validate method.

### PR DESCRIPTION
**Pull request by SanjayVas**
This also updates SigningCerts to make it easier to obtain the trusted issuer certificate given an AKID.

- - -
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/172)

https://rally1.rallydev.com/#/?detail=/task/672131371333&fdp=true

### CODE REVIEW

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/172)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @duliomatos1 and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/Signatures.kt` line 171 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/172#-NI4WSF1ADAxO4LewrbK:-NI4WSF1ADAxO4LewrbL:bxz90hn) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/a16e9d5dfda8661c635f4dfccf86c4fdc11e5c0c/src/main/kotlin/org/wfanet/measurement/common/crypto/Signatures.kt#L171)):*
> ```Kotlin
>  * @throws CertPathValidatorException if the certificate does not validate
>  */
> fun X509Certificate.validate(trustedIssuer: X509Certificate) {
> ```

can't we just use X509Certificate.verify ? based on the root certificate?
https://docs.oracle.com/javase/8/docs/api/java/security/cert/X509Certificate.html#verify-java.security.PublicKey-java.security.Provider-

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/172)* status: all files reviewed, 2 unresolved discussions (waiting on @duliomatos1 and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/SigningCerts.kt` line 32 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/172#-NI4b-y4CQPPAAMgsYsT:-NI4b-y4CQPPAAMgsYsU:b1y6d8r) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/a16e9d5dfda8661c635f4dfccf86c4fdc11e5c0c/src/main/kotlin/org/wfanet/measurement/common/crypto/SigningCerts.kt#L32)):*
> ```Kotlin
>   ) : this(
>     privateKeyHandle,
>     trustedCertificates.associateBy { requireNotNull(it.authorityKeyIdentifier) }
> ```

verify that the ski == aki?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/172)* status: 11 of 12 files reviewed, 2 unresolved discussions (waiting on @duliomatos1 and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/Signatures.kt` line 171 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/172#-NI4WSF1ADAxO4LewrbK:-NI4cTRwAYiFE9YQDyyp:b-wzabw6) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/a16e9d5dfda8661c635f4dfccf86c4fdc11e5c0c/src/main/kotlin/org/wfanet/measurement/common/crypto/Signatures.kt#L171)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

can't we just use X509Certificate.verify ? based on the root certificate?
https://docs.oracle.com/javase/8/docs/api/java/security/cert/X509Certificate.html#verify-java.security.PublicKey-java.security.Provider-

</blockquote></details>

Path validator is a bit more complete. It validates both certificates including dates. See `sun.security.provider.certpath.PKIXCertPathValidator` for the default implementation.
___
*[`src/main/kotlin/org/wfanet/measurement/common/crypto/SigningCerts.kt` line 32 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/172#-NI4b-y4CQPPAAMgsYsT:-NI4ceWE9zJ_EcQvxt0v:bm1hjmt) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/a16e9d5dfda8661c635f4dfccf86c4fdc11e5c0c/src/main/kotlin/org/wfanet/measurement/common/crypto/SigningCerts.kt#L32)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

verify that the ski == aki?
</blockquote></details>

Changed to use SKID instead of AKID, as it's not strictly necessary for TLS that these are root certs (e.g. you could trust an intermediate cert).

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/172)* status: all files reviewed, 2 unresolved discussions (waiting on @duliomatos1 and @SanjayVas)

___
*[`src/test/kotlin/org/wfanet/measurement/common/crypto/SignaturesTest.kt` line 140 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/172#-NI8X29U-UCC42qxNz3a:-NI8X29U-UCC42qxNz3b:banr4jf) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/0e2f0910fed12b399fe9fab7c131c5dde9a6c58d/src/test/kotlin/org/wfanet/measurement/common/crypto/SignaturesTest.kt#L140)):*
> ```Kotlin
>       assertFailsWith<CertPathValidatorException> { expiredCertificate.validate(issuerCertificate) }
>     assertThat(exception.reason).isEqualTo(CertPathValidatorException.BasicReason.EXPIRED)
>   }
> ```

might be good to add a test that uses a trusted intermediate certificate. should all pass now but would help prevent regressions in the future.



_Code quote (from src/test/kotlin/org/wfanet/measurement/common/grpc/TransportSecurityTest.kt):_
```Kotlin
buildTlsChannel
```

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/172)* status: all files reviewed, 2 unresolved discussions (waiting on @duliomatos1 and @stevenwarejones)

___
*[`src/test/kotlin/org/wfanet/measurement/common/crypto/SignaturesTest.kt` line 140 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/172#-NI8X29U-UCC42qxNz3a:-NI9GMp-CAGKKDYBJNGG:b-y0jqgh) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/0e2f0910fed12b399fe9fab7c131c5dde9a6c58d/src/test/kotlin/org/wfanet/measurement/common/crypto/SignaturesTest.kt#L140)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

might be good to add a test that uses a trusted intermediate certificate. should all pass now but would help prevent regressions in the future.
</blockquote></details>

To clarify, this `validate` method isn't expected to work with an intermediate cert as it's used only for consent signaling. That is to say we expect the issuer of a consent signaling certificate to be a root CA cert.

My  statement about trust for intermediate certificates only applies to TLS, not consent signaling. Issuer certificates for both are combined into a single trusted certificate collection.

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/172)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1)

**Review by SanjayVas — COMMENTED** [review]
> Dismissed @stevenwarejones from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/172)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1)

**Pull request merged**
