### PR TITLE
Update rules_kotlin to 1.8-RC-1 and Kotlin to 1.8.21

### PR DESCRIPTION
**Pull request by riemanli**

### CODE REVIEW

**Comment by riemanli** [comment]
Current dependencies on/for this PR:
* main
  * **PR #192** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/common-jvm/192" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/world-federation-of-advertisers/common-jvm/192?utm_source=stack-comment).

**Comment by riemanli** [comment]
@SanjayVas 
I am not able to remove jdk7 and 8 in [BUILD.com_github_jetbrains_kotlin](https://github.com/world-federation-of-advertisers/common-jvm/blob/main/build/rules_kotlin/BUILD.com_github_jetbrains_kotlin#L14). I am not sure what BUILD.com_github_jetbrains_kotlin is for. Should we keep them?

**Review by SanjayVas — COMMENTED** [review]
That file exists to ensure we use the libraries from Maven. What do you mean you're unable to remove them?

> Reviewed 9 of 11 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/192#-:-NUSAy0gCe8Zn916emY-:b-ag6bae)* status: 10 of 11 files reviewed, 2 unresolved discussions (waiting on @riemanli)

___
*[`imports/kotlin/kotlin/BUILD.bazel` line 4 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/192#-NUSAay89ZzjKOZ6tNIg:-NUSAay9-hXFeEOtXJtl:bw0h0o5) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1dfbef03771aba2c63023c90a715582cb24cb330/imports/kotlin/kotlin/BUILD.bazel#L4)):*
> ```Starlark
> 
> alias(
>     name = "stdlib",
> ```

We shouldn't need this. The main stdlib is a default dependency of any kt_jvm_library target.
___
*[`src/main/kotlin/org/wfanet/measurement/common/db/r2dbc/ReadWriteContext.kt` line 43 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/192#-NUSAn7P2Ae37ZlE4Cuk:-NUSAn7P2Ae37ZlE4Cul:b-cax6xn) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1dfbef03771aba2c63023c90a715582cb24cb330/src/main/kotlin/org/wfanet/measurement/common/db/r2dbc/ReadWriteContext.kt#L43)):*
> ```Kotlin
>   ReadWriteContext, ReadContextImpl(connection) {
> 
>   @OptIn(kotlinx.coroutines.ExperimentalCoroutinesApi::class)
> ```

Document what the opt-in is for.



_Code quote:_
```Kotlin
@OptIn(kotlinx.coroutines.ExperimentalCoroutinesApi::class)
```

**Review by riemanli — COMMENTED** [review]
Based on the [update](https://kotlinlang.org/docs/whatsnew18.html#updated-jvm-compilation-target) in Kotlin 1.8.0, we don't need to declare `kotlin-stdlib-jdk7` and `kotlin-stdlib-jdk8`. I was trying to remove them from BUILD.com_github_jetbrains_kotlin, but it failed to compile.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/192#-:-NUSFBt1-yzI_7BfnRvV:b1380j7)* status: 9 of 11 files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[`imports/kotlin/kotlin/BUILD.bazel` line 4 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/192#-NUSAay89ZzjKOZ6tNIg:-NUSFnD_3RcoJ7G6bPsu:bo2397p) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1dfbef03771aba2c63023c90a715582cb24cb330/imports/kotlin/kotlin/BUILD.bazel#L4)):*
The [update note](https://kotlinlang.org/docs/whatsnew18.html#updated-jvm-compilation-target) for Kotlin 1.8.0 said

> If you have explicitly declared `kotlin-stdlib-jdk7` and `kotlin-stdlib-jdk8` as dependencies in your build scripts, then you should replace them with `kotlin-stdlib`.
___
*[`src/main/kotlin/org/wfanet/measurement/common/db/r2dbc/ReadWriteContext.kt` line 43 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/192#-NUSAn7P2Ae37ZlE4Cuk:-NUSKbZR-g5EiuaRdtFC:b-896fja) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1dfbef03771aba2c63023c90a715582cb24cb330/src/main/kotlin/org/wfanet/measurement/common/db/r2dbc/ReadWriteContext.kt#L43)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Document what the opt-in is for.
</blockquote></details>

Done!

**Review by SanjayVas — COMMENTED** [review]
> That file exists to ensure we use the libraries from Maven. 

Turns out this was incorrect. What this does it ensure that the libraries are tagged with Maven coordinates, but it's still using the ones from the Kotlin repo instead of Maven. This relates back to https://github.com/bazelbuild/rules_kotlin/issues/752.

Basically rules_kotlin still references the jdk7/jdk8 targets from the Kotlin repo. We don't want that. Therefore, I think what we need to do is:

1. Drop BUILD.com_github_jetbrains_kotlin and the Maven override targets
2. Explicitly pull the stdlibs (everything listed in _JETBRAINS_KOTLIN_OVERRIDE_TARGETS) from Maven rather than overriding them with targets from the Kotlin repo.
3. Update [our kt_kotlinc_options](https://github.com/world-federation-of-advertisers/common-jvm/blob/main/build/rules_kotlin/toolchain/BUILD.bazel) to set `include_stdlibs` to "none". This means that `kt_jvm_libarary` will no longer automatically add a dep to `kotlin-stdlib`.
4. Add the library deps wherever we need to.

> Reviewed 1 of 11 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/192#-:-NUS_-ezEEUwb9pPuYGV:b-zcg27s)* status: all files reviewed, 1 unresolved discussion (waiting on @riemanli)

___
*[`imports/kotlin/kotlin/BUILD.bazel` line 4 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/192#-NUSAay89ZzjKOZ6tNIg:-NUSWg_2EIR6Xa81XIc3:bswvk37) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1dfbef03771aba2c63023c90a715582cb24cb330/imports/kotlin/kotlin/BUILD.bazel#L4)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

The [update note](https://kotlinlang.org/docs/whatsnew18.html#updated-jvm-compilation-target) for Kotlin 1.8.0 said

> If you have explicitly declared `kotlin-stdlib-jdk7` and `kotlin-stdlib-jdk8` as dependencies in your build scripts, then you should replace them with `kotlin-stdlib`.
</blockquote></details>

That's general advice that's not specific to Bazel. In our case, `kt_jvm_library` from rules_kotlin always includes the kotlin-stdlib dependency for us.

That said, we may have to change this. See my other comment.

**Review by riemanli — COMMENTED** [review]
Offline discussion: in addition to the steps above, we will create a macro that has the same functionality of `kt_jvm_library` but include maven kotlin stdlib in `deps` automatically.

Some bazel rookie questions. For the macro replacing `kt_jvm_library`, 
1. which file is a good place to declare it?
2. is it done by using [repository rules](https://bazel.build/extending/repo)?

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/192#-:-NUe1kTWBrINDIe3uXN3:batte82)* status: all files reviewed, 1 unresolved discussion (waiting on @riemanli)

**Review by SanjayVas — COMMENTED** [review]
> which file is a good place to declare it?

`build/rules_kotlin/defs.bzl` (doesn't yet exist)

> is it done by using [repository rules](https://bazel.build/extending/repo)?

No, just a regular Bazel macro. See https://bazel.build/extending/macros

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/192#-:-NUgxaDoAmiuFFNb0Hfx:b8cf4te)* status: all files reviewed, 1 unresolved discussion (waiting on @riemanli)

**Review by riemanli — COMMENTED** [review]
Some usages of `kt_jvm_library` are using `runtime_deps` to include the `stdlib` ex: [build file of throttler](https://github.com/world-federation-of-advertisers/common-jvm/blob/main/src/main/kotlin/org/wfanet/measurement/common/throttler/BUILD.bazel#L8). If we make a macro that always includes `@maven//:org_jetbrains_kotlin_kotlin_stdlib` in `deps`, is that ok?

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/192#-:-NUzIM_Z9e1qa7hoQfw0:by95ub)* status: all files reviewed, 1 unresolved discussion (waiting on @riemanli)

**Review by SanjayVas — COMMENTED** [review]
That's fine. They were doing so because the extra JDK7 bindings were only needed at runtime. Recall that before this PR, all of these kt_jvm_library rules had a compile-time dependency on the base stdlib. We're just reintroducing that manually now that the rule isn't doing it for us.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/192#-:-NV0RFGI7dgOGwrlVODE:bhljjrg)* status: all files reviewed, 1 unresolved discussion (waiting on @riemanli)

**Review by riemanli — COMMENTED** [review]
Got it. Finished the modification. PTAL.

Side question: how did the previous pass the lint test?  I got a lot of following lint errors: `By convention, every public macro needs a "name" argument (even if it doesn't use it).`

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/192#-:-NV1wVcUBtVGftmEjJBd:b422d92)* status: 3 of 46 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`imports/kotlin/kotlin/BUILD.bazel` line 4 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/192#-NUSAay89ZzjKOZ6tNIg:-NV1wUpp73x-_dJ8Z7rW:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1dfbef03771aba2c63023c90a715582cb24cb330/imports/kotlin/kotlin/BUILD.bazel#L4)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

That's general advice that's not specific to Bazel. In our case, `kt_jvm_library` from rules_kotlin always includes the kotlin-stdlib dependency for us.

That said, we may have to change this. See my other comment.
</blockquote></details>

Done.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/192)* status: 8 of 49 files reviewed, 4 unresolved discussions (waiting on @riemanli)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/192#-NV5V-n-85xNQHfXkDVL:-NV5V-n-85xNQHfXkDVM:bfk0oud) (no related file):*
rules_kotlin v1.8-RC-2 has now been released (though confusingly they tagged it as RC12): https://github.com/bazelbuild/rules_kotlin/releases/tag/v1.8-RC-12

___

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/192)* status: 4 of 49 files reviewed, 4 unresolved discussions (waiting on @riemanli)

___
*[`build/rules_kotlin/defs.bzl` line 23 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/192#-NV5R9fo9cN3nNmDH0-k:-NV63x1yCEh_rphFdAo-:b-kti5oa) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/ee21ee3cb7f2aa96333ba2225504cb7afe39ffae/build/rules_kotlin/defs.bzl#L23)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Do you mean creating an alias like what we did in `imports/kotlin/kotlin/BUILD.bazel` before and use that in `deps`?
</blockquote></details>

Yes. No build target should reference maven deps directly and should instead reference the import alias.

**Review by riemanli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/192)* status: 4 of 49 files reviewed, 4 unresolved discussions (waiting on @SanjayVas)

___
*[`build/rules_kotlin/defs.bzl` line 23 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/192#-NV5R9fo9cN3nNmDH0-k:-NV6tJgOBwidoRmfSULI:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/ee21ee3cb7f2aa96333ba2225504cb7afe39ffae/build/rules_kotlin/defs.bzl#L23)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Yes. No build target should reference maven deps directly and should instead reference the import alias.
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 4 of 46 files at r4, 39 of 40 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/192)* status: all files reviewed, 1 unresolved discussion (waiting on @riemanli)

___
*[`imports/kotlin/kotlin/BUILD.bazel` line 9 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/192#-NVAvq4V2Qpv2Pevv2G7:-NVAvq4V2Qpv2Pevv2G8:b-rg0f8n) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/0cd0039e844298e1055936e1c4bfcf866ab440cd/imports/kotlin/kotlin/BUILD.bazel#L9)):*
> ```Starlark
> 
> alias(
>     name = "reflect",
> ```

This introduces the `kotlin.reflect` Kotlin package, so it should go into a `reflect` Bazel package.

**Review by riemanli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/192)* status: 46 of 49 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`imports/kotlin/kotlin/BUILD.bazel` line 9 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/192#-NVAvq4V2Qpv2Pevv2G7:-NVAxqlrDfp673vkazr9:b-e4fea9) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/0cd0039e844298e1055936e1c4bfcf866ab440cd/imports/kotlin/kotlin/BUILD.bazel#L9)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This introduces the `kotlin.reflect` Kotlin package, so it should go into a `reflect` Bazel package.
</blockquote></details>

Thanks for pointing that out. I put it under `imports/kotlin/kotlin/reflect/jvm/BUILD.bazel`. Is that the right place? Or just `imports/kotlin/kotlin/reflect/BUILD.bazel`?

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/192)* status: 47 of 49 files reviewed, 1 unresolved discussion (waiting on @riemanli)

___
*[`imports/kotlin/kotlin/BUILD.bazel` line 9 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/192#-NVAvq4V2Qpv2Pevv2G7:-NVB36jJDp8SwBybhD39:bkm8ymw) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/0cd0039e844298e1055936e1c4bfcf866ab440cd/imports/kotlin/kotlin/BUILD.bazel#L9)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Thanks for pointing that out. I put it under `imports/kotlin/kotlin/reflect/jvm/BUILD.bazel`. Is that the right place? Or just `imports/kotlin/kotlin/reflect/BUILD.bazel`?
</blockquote></details>

The latter.

**Review by riemanli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/192)* status: 46 of 49 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`imports/kotlin/kotlin/BUILD.bazel` line 9 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/192#-NVAvq4V2Qpv2Pevv2G7:-NVBX45l0eqnJ2XESrlY:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/0cd0039e844298e1055936e1c4bfcf866ab440cd/imports/kotlin/kotlin/BUILD.bazel#L9)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The latter.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 3 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/192)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @riemanli)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 11 files at r1, 1 of 1 files at r3, 3 of 46 files at r4, 34 of 40 files at r5, 1 of 3 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/192)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @riemanli)

**Pull request merged**
