### PR TITLE
build!: Update rules_kotlin_jvm dep for Maven BOMs

### PR DESCRIPTION
**Pull request by SanjayVas**
This reduces compatibility issues with Maven version resolution.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/268)

**Comment by SanjayVas** [comment]
Depends on world-federation-of-advertisers/rules_kotlin_jvm#8

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/268)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/268)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
