### PR TITLE
Add function overloads and extension properties for X.509 certificates.

### PR DESCRIPTION
**Pull request by SanjayVas**
This also adds tests for SecurityProvider.kt with corresponding test certificates/keys.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/6)

### CODE REVIEW

**Comment by SanjayVas** [comment]
This replaces https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/147

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 8 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/6)* status: 8 of 12 files reviewed, all discussions resolved (waiting on @oliver-amzn)

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/6)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/testing/testdata/openssl.cnf, line 11 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/6#-MeevSMhDQ4gZLdoyYiD:-MeevSMhDQ4gZLdoyYiE:bha0gj8) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/408460d7dfc567e30428e2a269096635b1c4f983/src/main/kotlin/org/wfanet/measurement/common/crypto/testing/testdata/openssl.cnf#L11)):*
> ```
> [subject_alt_name]
> DNS=localhost
> IP=127.0.0.1
> ```

nit: missing newline at the end of the file?

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/6)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
