### PR TITLE
Move Maven from WORKSPACE to bzl files

### PR DESCRIPTION
**Pull request by enfreck**
Move Maven deps from WORKSPACE to bzl files

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/23)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/23)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @enfreck)

___
*[build/common_jvm_maven.bzl, line 72 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/23#-MgCUgLx0-Zh_VOx7Kvs:-MgCUgLx0-Zh_VOx7Kvt:bdvkvwf) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/92dd953c78b183073d0d76d0f1a392cd22c2a621/build/common_jvm_maven.bzl#L72)):*
> ```Starlark
>     })
> 
>     maven_install(
> ```

How would other workspaces that depend on this one install additional Maven artifacts?

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/23)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[build/common_jvm_maven.bzl, line 72 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/23#-MgCUgLx0-Zh_VOx7Kvs:-MgCVrI71XpA7EXZo31p:b-qtlex) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/92dd953c78b183073d0d76d0f1a392cd22c2a621/build/common_jvm_maven.bzl#L72)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

How would other workspaces that depend on this one install additional Maven artifacts?
</blockquote></details>

@sanjayvas is your recommendation to add parameters to this macro to add additional artifacts/override_targets, or should this file just provide a big list of all the artifacts and override_targets and then the WORKSPACE has to manually run maven_install?

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/23)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein)

___
*[build/common_jvm_maven.bzl, line 72 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/23#-MgCUgLx0-Zh_VOx7Kvs:-MgCX3Lx1uDTckc5sfeo:b7pqvwl) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/92dd953c78b183073d0d76d0f1a392cd22c2a621/build/common_jvm_maven.bzl#L72)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

@sanjayvas is your recommendation to add parameters to this macro to add additional artifacts/override_targets, or should this file just provide a big list of all the artifacts and override_targets and then the WORKSPACE has to manually run maven_install?
</blockquote></details>

The latter gives the most flexibility to the workspace that depends on this one, but would require the grpc-java and grpc-kt repo targets to be called separately. The workspace would also have to make sure to set certain attributes in order for things to work, e.g. we depend on `generate_compat_repositories` being true.

Despite the downsides, I think that's the better approach: expose a function that returns artifacts and a constant merged collection of override targets. Workspaces that depend on this one should be able to make other changes to their Maven setup, e.g. to enable pinning.

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/23)* status: 3 of 4 files reviewed, 5 unresolved discussions (waiting on @efoxepstein, @enfreck, and @SanjayVas)

___
*[build/common_jvm_maven.bzl, line 39 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/23#-MgDFQfTCuETcw3nJ86w:-MgDFQfTCuETcw3nJ86x:bdbpfk9) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/bc573a54b675a6d5e6df6709e9c617af9ed1757c/build/common_jvm_maven.bzl#L39)):*
> ```Starlark
> load("//build/maven:artifacts.bzl", "artifacts")
> 
> def common_jvm_maven():
> ```

Add `_artifacts` to the name please
___
*[build/common_jvm_maven.bzl, line 46 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/23#-MgDFFmv15Ydkg_2RhdB:-MgDFFmv15Ydkg_2RhdC:b-jt2qbu) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/bc573a54b675a6d5e6df6709e9c617af9ed1757c/build/common_jvm_maven.bzl#L46)):*
> ```Starlark
>         An updated dictionary from a list of Java and Kotlin artifacts
>     """
>     MAVEN_ARTIFACTS = artifacts.list_to_dict(
> ```

lower_case_please
___
*[build/common_jvm_maven.bzl, line 74 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/23#-MgDFJ8F2qTFAsG0DnXd:-MgDFJ8F2qTFAsG0DnXe:b-v5jjhu) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/bc573a54b675a6d5e6df6709e9c617af9ed1757c/build/common_jvm_maven.bzl#L74)):*
> ```Starlark
>     })
> 
>     return MAVEN_ARTIFACTS
> ```

Would it be simpler to just return `return artifacts.dict_to_list(maven_artifacts)` here and not expose `common_jvm_maven_artifacts` below?
___
*[build/common_jvm_maven.bzl, line 91 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/23#-MgDF7Lp2XLjg3G6I9Ky:-MgDF7Lp2XLjg3G6I9Kz:bgsaf3q) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/bc573a54b675a6d5e6df6709e9c617af9ed1757c/build/common_jvm_maven.bzl#L91)):*
> ```Starlark
> )
> 
> def common_jvm_maven_grpc():
> ```

These aren't really related to maven, they just need to happen after it. Can they go into the next step? Or are they prerequisites of the next step?

**Review by enfreck — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/23)* status: 2 of 5 files reviewed, 5 unresolved discussions (waiting on @efoxepstein and @SanjayVas)

___
*[build/common_jvm_maven.bzl, line 72 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/23#-MgCUgLx0-Zh_VOx7Kvs:-MgGQ_AADX0s9cS2OBsr:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/92dd953c78b183073d0d76d0f1a392cd22c2a621/build/common_jvm_maven.bzl#L72)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The latter gives the most flexibility to the workspace that depends on this one, but would require the grpc-java and grpc-kt repo targets to be called separately. The workspace would also have to make sure to set certain attributes in order for things to work, e.g. we depend on `generate_compat_repositories` being true.

Despite the downsides, I think that's the better approach: expose a function that returns artifacts and a constant merged collection of override targets. Workspaces that depend on this one should be able to make other changes to their Maven setup, e.g. to enable pinning.
</blockquote></details>

Done.
___
*[build/common_jvm_maven.bzl, line 39 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/23#-MgDFQfTCuETcw3nJ86w:-MgGRvzF2Y_354TIDWo9:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/bc573a54b675a6d5e6df6709e9c617af9ed1757c/build/common_jvm_maven.bzl#L39)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Add `_artifacts` to the name please
</blockquote></details>

Done.
___
*[build/common_jvm_maven.bzl, line 46 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/23#-MgDFFmv15Ydkg_2RhdB:-MgGRwYW50Ukxi86gZSy:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/bc573a54b675a6d5e6df6709e9c617af9ed1757c/build/common_jvm_maven.bzl#L46)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

lower_case_please
</blockquote></details>

Done.
___
*[build/common_jvm_maven.bzl, line 74 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/23#-MgDFJ8F2qTFAsG0DnXd:-MgGRyHY-K2PVc0XWriT:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/bc573a54b675a6d5e6df6709e9c617af9ed1757c/build/common_jvm_maven.bzl#L74)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Would it be simpler to just return `return artifacts.dict_to_list(maven_artifacts)` here and not expose `common_jvm_maven_artifacts` below?
</blockquote></details>

Done.
___
*[build/common_jvm_maven.bzl, line 91 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/23#-MgDF7Lp2XLjg3G6I9Ky:-MgGRzByCqcdBZyNOn53:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/bc573a54b675a6d5e6df6709e9c617af9ed1757c/build/common_jvm_maven.bzl#L91)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

These aren't really related to maven, they just need to happen after it. Can they go into the next step? Or are they prerequisites of the next step?
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/23)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/23)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 3 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/23)* status: all files reviewed, 1 unresolved discussion (waiting on @enfreck)

___
*[build/common_jvm_maven.bzl, line 74 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/23#-MgHDgi39-5K3ktPcE0-:-MgHDgi39-5K3ktPcE00:b-ir0nut) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/cc857aa9a51cff1f2db8abb58629638fee73dbfb/build/common_jvm_maven.bzl#L74)):*
> ```
> common_jvm_maven_targets
> ```
This one is actually intended to be a constant and can be CONSTANT_CASE

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 2 of 3 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/23)* status: all files reviewed, 1 unresolved discussion (waiting on @enfreck)

**Review by efoxepstein — APPROVED** [review]
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/23)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @enfreck)

**Pull request merged**
