### PR TITLE
Update SpannerEmulatorDatabaseRule to take in a Liquibase changelog.

### PR DESCRIPTION
**Pull request by SanjayVas**
This also drops the unused wrapper executable around the Spanner emulator.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/107)

https://rally1.rallydev.com/#/?detail=/task/633275093557&fdp=true

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/107)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/spanner/SpannerFlags.kt` line 66 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/107#-N0gtpc55EEtAALNny8t:-N0gtpc55EEtAALNny8u:b-tx6br4) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1c96ca56f8834789e88402ced274796bc202cd36/src/main/kotlin/org/wfanet/measurement/gcloud/spanner/SpannerFlags.kt#L66)):*
> ```Kotlin
>     return SpannerDatabaseConnector(
>       projectName,
>       instanceName,
> ```

Can you add keyword arguments here? It's super confusing that the order gets changed (though I agree with the new order)

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/107)* status: 15 of 16 files reviewed, 1 unresolved discussion (waiting on @efoxepstein)

___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/spanner/SpannerFlags.kt` line 66 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/107#-N0gtpc55EEtAALNny8t:-N0hIwbe0iYrCaw0c-cG:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/1c96ca56f8834789e88402ced274796bc202cd36/src/main/kotlin/org/wfanet/measurement/gcloud/spanner/SpannerFlags.kt#L66)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you add keyword arguments here? It's super confusing that the order gets changed (though I agree with the new order)
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/107)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by efoxepstein — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/107)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/107)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by SanjayVas — COMMENTED** [review]
Switched to using `autoConfigEmulator` from Spanner JDBC rather than initializing emulator instance/database via Spanner API. Improved thread safety of `SpannerEmulatorDatabaseRule` while I was at it.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/107#-:-N1eHFLUEz1Dn0raVmWn:b-v9jnhj)* status: 11 of 16 files reviewed, all discussions resolved (waiting on @efoxepstein and @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 8 of 16 files at r1, 1 of 1 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/107)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 8 of 16 files at r1, 1 of 1 files at r2, 1 of 2 files at r3, 5 of 5 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/107)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
