### PR TITLE
Support multiple hostnames in generate_user_certificate macro.

### PR DESCRIPTION
**Pull request by SanjayVas**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/143)

### CODE REVIEW

**Review by matthewclegg — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/143)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @matthewclegg and @SanjayVas)

___
*[`build/openssl/defs.bzl` line 112 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/143#-N8R283v4E-5m7xgiVlO:-N8R283v4E-5m7xgiVlP:b-jz2uh2) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/a2a5039e1ab1804eda057b290b120dc2fe5b13c6/build/openssl/defs.bzl#L112)):*
> ```Starlark
>         common_name,
>         hostnames,
>         valid_days = 365,
> ```

Perhaps it would be a good idea to change the default value of valid_days to something larger?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/143)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @matthewclegg)

___
*[`build/openssl/defs.bzl` line 112 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/143#-N8R283v4E-5m7xgiVlO:-N8R3Ppm7eWKjTXB00id:b-tgqk8v) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/a2a5039e1ab1804eda057b290b120dc2fe5b13c6/build/openssl/defs.bzl#L112)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

Perhaps it would be a good idea to change the default value of valid_days to something larger?
</blockquote></details>

The default should not be long for a user certificate normally. It only matters when the resulting certificates are under version control.

Bazel rules/macros are really intended to generate things on-the-fly. We just happened to use it for convenience when generating our test certs. I intentionally dropped the documentation for that in world-federation-of-advertisers/cross-media-measurement#643, instead just leaving the recommendation that one can look at how these macros generate certificates using OpenSSL as a reference.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/143)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @matthewclegg and @stevenwarejones)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/143)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
