### PR TITLE
Use TestContainers instead of OpenTable Embedded PostgreSQL.

### PR DESCRIPTION
**Pull request by SanjayVas**
Since Embedded PostgreSQL switched to using a container in v1.0, there's not much benefit to using that custom solution over TestContainers.

From the Embedded PostgreSQL FAQ:
> * Why not just use Testcontainers directly?
>
>   You can, and it should work well for you. The builders, the api compatibility, the wrapping around Flyway - that's the added value. But certainly there's no real reason you can't use TestContainers directly - they have their own Junit4 and Junit5 Rules/Extensions.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/211)

**Review by tristanvuong2021 — APPROVED** [review]
> Reviewed 7 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/211)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @YuhongWang-Amazon)

**Review by YuhongWang-Amazon — COMMENTED** [review]
> Reviewed 5 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/211)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Comment by SanjayVas** [comment]
Going to hold off on merging this until we have a corresponding PR ready in the main repo.

**Pull request merged**
