### PR TITLE
add GcsSubscribingStorageClient

### PR DESCRIPTION
**Pull request by stevenwarejones**
Adds a storage client that CloudEventsFunctions(s) can subscribe to.

This will be used to test the Data Watcher.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/287)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/287)* status: 0 of 9 files reviewed, 4 unresolved discussions (waiting on @Marco-Premier and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/287#-OAYzzLtDGUk9wAK983Z:-OAYzzLtDGUk9wAK983_:b-yv77zd) (no related file):*
Can you give a little more explanation on how this works in tests? This can be covered in the testing section of the related design doc.

I assume this has to do with the fact that the in-memory Cloud Storage emulator only covers the storage APIs and does not interact with Cloud Run Functions. I'm assuming test code would call the `subscribe` function, and that is sufficiently similar to how real subscriptions would work?

___
___
*[`MODULE.bazel` line 208 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/287#-OAYzV6oCA-VujIl8oyu:-OAYzV6oCA-VujIl8oyv:br79i84) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/8bc877b13be707b19f7ea32b5a86f631c65341c6/MODULE.bazel#L208)):*
> ```Starlark
>         "com.google.cloud:google-cloud-spanner",
>         "com.google.cloud:google-cloud-bigquery",
>         "com.google.cloud.functions:functions-framework-api:1.1.0",
> ```

I'm surprised this PR doesn't include/use `com.google.cloud:google-cloud-functions`, which is included in the BOM.
___
*[`MODULE.bazel` line 212 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/287#-OAYxiEbA2kG2nsLMcKd:-OAYxiEbA2kG2nsLMcKe:b-iveail) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/8bc877b13be707b19f7ea32b5a86f631c65341c6/MODULE.bazel#L212)):*
> ```Starlark
> 
>         # Cloud Functions
>         "io.cloudevents:cloudevents-api:4.0.1",
> ```

Use BOMs when available rather than specifying versions of individual artifacts. Add `io.cloudevents:cloudevents-bom:4.0.1` to the `boms` attribute below and drop the versions here.
___
*[`src/main/kotlin/org/wfanet/measurement/storage/testing/GcsSubscribingStorageClient.kt` line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/287#-OAYzA5lDETf7GVODP6l:-OAYzA5lDETf7GVODP6m:b-ypyrw2) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/8bc877b13be707b19f7ea32b5a86f631c65341c6/src/main/kotlin/org/wfanet/measurement/storage/testing/GcsSubscribingStorageClient.kt#L42)):*
> ```Kotlin
>         .withData(dataBuilder.toByteArray())
>         .build()
>     print(event)
> ```

Use Logger

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/287)* status: 0 of 9 files reviewed, 4 unresolved discussions (waiting on @Marco-Premier and @SanjayVas)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/287#-OAYzzLtDGUk9wAK983Z:-OAZ45Ol1z9h_iQ_09Mn:b-i0v1y6) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Can you give a little more explanation on how this works in tests? This can be covered in the testing section of the related design doc.

I assume this has to do with the fact that the in-memory Cloud Storage emulator only covers the storage APIs and does not interact with Cloud Run Functions. I'm assuming test code would call the `subscribe` function, and that is sufficiently similar to how real subscriptions would work?
</blockquote></details>

This is correct. As far as I understand it, there is no existing storage emulator that automatically calls the accept function of a CloudEventsFunction. 

Additionally, the documentation shows subscribing happening via gcloud commands (I assume this can be done with terraform as well). https://cloud.google.com/functions/docs/calling/storage

___
___
*[`MODULE.bazel` line 208 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/287#-OAYzV6oCA-VujIl8oyu:-OAZ6Gd20Pi-uVI_PGiT:bkkf13q) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/8bc877b13be707b19f7ea32b5a86f631c65341c6/MODULE.bazel#L208)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I'm surprised this PR doesn't include/use `com.google.cloud:google-cloud-functions`, which is included in the BOM.
</blockquote></details>

I'm not sure I'm following. Its needed for `com.google.cloud.functions.CloudEventsFunction` - https://mvnrepository.com/artifact/com.google.cloud.functions
___
*[`MODULE.bazel` line 212 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/287#-OAYxiEbA2kG2nsLMcKd:-OAZACLrDeHLbrqgvewG:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/8bc877b13be707b19f7ea32b5a86f631c65341c6/MODULE.bazel#L212)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use BOMs when available rather than specifying versions of individual artifacts. Add `io.cloudevents:cloudevents-bom:4.0.1` to the `boms` attribute below and drop the versions here.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/storage/testing/GcsSubscribingStorageClient.kt` line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/287#-OAYzA5lDETf7GVODP6l:-OAZABhxElkdBAQXKQuO:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/8bc877b13be707b19f7ea32b5a86f631c65341c6/src/main/kotlin/org/wfanet/measurement/storage/testing/GcsSubscribingStorageClient.kt#L42)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use Logger
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
Approved assuming naming comments are fixed.

> Reviewed 4 of 9 files at r1, 1 of 2 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/287#-:-OAZ_n742VNDfgeDXKAj:be3cpkd)* status: all files reviewed, 5 unresolved discussions (waiting on @Marco-Premier and @stevenwarejones)

___
*[`MODULE.bazel` line 208 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/287#-OAYzV6oCA-VujIl8oyu:-OAZOPV33UWJgEEgzv4d:b-c7vt19) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/8bc877b13be707b19f7ea32b5a86f631c65341c6/MODULE.bazel#L208)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I'm not sure I'm following. Its needed for `com.google.cloud.functions.CloudEventsFunction` - https://mvnrepository.com/artifact/com.google.cloud.functions
</blockquote></details>

What I meant was that I'm surprised I don't see `com.google.cloud:google-cloud-functions` in this artifact list. Not an actual issue, I just expected that to be where the functionality would come from.
___
*[`imports/java/com/google/cloud/BUILD.bazel` line 9 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/287#-OAZPZEuC2GIvMBeTEuM:-OAZPZEuC2GIvMBeTEuN:b-c15000) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/c0188ed4cf6f92e35cac8663d5bbc2e8804204c8/imports/java/com/google/cloud/BUILD.bazel#L9)):*
> ```Starlark
> 
> alias(
>     name = "google_cloudevent_types",
> ```

The actual Java package this appears to contain is `com.google.events`, so this should go under `//imports/java/com/google/events`
___
*[`imports/java/io/cloudevents/BUILD.bazel` line 4 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/287#-OAZQAxF192FqADbi325:-OAZQAxF192FqADbi326:b-jc2iry) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/c0188ed4cf6f92e35cac8663d5bbc2e8804204c8/imports/java/io/cloudevents/BUILD.bazel#L4)):*
> ```Starlark
> 
> alias(
>     name = "core",
> ```

This appears to define the entirety of the io.cloudevents.core Java package, so this should be a target named "core" under `//imports/java/io/cloudevents/core`
___
*[`src/test/kotlin/org/wfanet/measurement/storage/testing/GcsSubscribingStorageClientTest.kt` line 42 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/287#-OAZ_OIU24CcWKLR3ITY:-OAZ_OIVAtDFLZ4tJ3zh:b6t4r7l) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/c0188ed4cf6f92e35cac8663d5bbc2e8804204c8/src/test/kotlin/org/wfanet/measurement/storage/testing/GcsSubscribingStorageClientTest.kt#L42)):*
> ```Kotlin
> 
>   @Test
>   fun `subscribe`() = runBlocking {
> ```

nit: more descriptive test method name



_Suggestion:_
```Kotlin
writeBlob publishes finalize event to subscribers
```

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/287)* status: 5 of 10 files reviewed, 4 unresolved discussions (waiting on @Marco-Premier and @SanjayVas)

___
*[`imports/java/com/google/cloud/BUILD.bazel` line 9 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/287#-OAZPZEuC2GIvMBeTEuM:-OAbu0T4BbhU8QMebI1x:bshly2y) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/c0188ed4cf6f92e35cac8663d5bbc2e8804204c8/imports/java/com/google/cloud/BUILD.bazel#L9)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The actual Java package this appears to contain is `com.google.events`, so this should go under `//imports/java/com/google/events`
</blockquote></details>

Thx for the clarification. Hadn't added an import in a while and didn't realize it was based on the import path.
___
*[`imports/java/io/cloudevents/BUILD.bazel` line 4 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/287#-OAZQAxF192FqADbi325:-OAbuHW_6mUglh1qTwEb:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/c0188ed4cf6f92e35cac8663d5bbc2e8804204c8/imports/java/io/cloudevents/BUILD.bazel#L4)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This appears to define the entirety of the io.cloudevents.core Java package, so this should be a target named "core" under `//imports/java/io/cloudevents/core`
</blockquote></details>

Done.

**Review by stevenwarejones — COMMENTED** [review]
> Reviewed 2 of 9 files at r1, 3 of 4 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/287)* status: all files reviewed, 4 unresolved discussions (waiting on @Marco-Premier and @SanjayVas)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/287)* status: all files reviewed, 1 unresolved discussion (waiting on @Marco-Premier and @stevenwarejones)

___
*[`imports/java/com/google/events/BUILD.bazel` line 4 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/287#-OAcdbLA-RWTp1-4cd12:-OAcdbLBCCnHAf4qfShk:b-6trok7) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/af3ebec6199e68be81799544db2293f29f87f6d3/imports/java/com/google/events/BUILD.bazel#L4)):*
> ```Starlark
> 
> alias(
>     name = "google_cloudevent_types",
> ```

Just use the Bazel package name to make this the default target. The only time we use specific names is when a single target doesn't fully define a package.



_Suggestion:_
```Starlark
events
```

**Review by stevenwarejones — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/287)* status: all files reviewed, 1 unresolved discussion (waiting on @Marco-Premier and @SanjayVas)

___
*[`imports/java/com/google/events/BUILD.bazel` line 4 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/287#-OAcdbLA-RWTp1-4cd12:-OAcid2qBAjsEj4tqCF7:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/af3ebec6199e68be81799544db2293f29f87f6d3/imports/java/com/google/events/BUILD.bazel#L4)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Just use the Bazel package name to make this the default target. The only time we use specific names is when a single target doesn't fully define a package.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/287)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Pull request merged**
