### PR TITLE
Add abstract Store class for blob stores.

### PR DESCRIPTION
**Pull request by SanjayVas**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/37)

### CODE REVIEW

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/37)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/storage/Store.kt, line 32 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/37#-MjWG5P13--5L-MUfiFF:-MjWG5P13--5L-MUfiFG:b-y72kp4) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/e7c94b0c9b7be6447fb9395af6677872d2ce69dc/src/main/kotlin/org/wfanet/measurement/storage/Store.kt#L32)):*
> ```
> <T>
> ```
We don't need this type template I think. `prefix/UUID` is enough, no need to have additional information in the path.  Humans don't really need to read the path.
___
*[src/main/kotlin/org/wfanet/measurement/storage/Store.kt, line 64 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/37#-MjWFcLk-SSK4ijGvGj-:-MjWFcLk-SSK4ijGvGj0:bxovirh) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/e7c94b0c9b7be6447fb9395af6677872d2ce69dc/src/main/kotlin/org/wfanet/measurement/storage/Store.kt#L64)):*
> ```
>    * Returns a [Blob] for the computation with the specified blob key, or `null` if the computation
>    * isn't found.
>    */
> ```
Returns a [Blob] with the specified blob key, or `null` if not found.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/37)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/storage/Store.kt, line 32 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/37#-MjWG5P13--5L-MUfiFF:-MjWIMOQ1kf1ixwfayGE:b-fi9h3) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/e7c94b0c9b7be6447fb9395af6677872d2ce69dc/src/main/kotlin/org/wfanet/measurement/storage/Store.kt#L32)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> <T>
> ```
We don't need this type template I think. `prefix/UUID` is enough, no need to have additional information in the path.  Humans don't really need to read the path.


</blockquote></details>

It's useful for other operations. e.g. Duchy operator can manually retrieve all blobs for a given prefix. See https://cloud.google.com/storage/docs/samples/storage-list-files-with-prefix.
___
*[src/main/kotlin/org/wfanet/measurement/storage/Store.kt, line 64 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/37#-MjWFcLk-SSK4ijGvGj-:-MjWIGO2DywCFCDItkwV:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/e7c94b0c9b7be6447fb9395af6677872d2ce69dc/src/main/kotlin/org/wfanet/measurement/storage/Store.kt#L64)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
>    * Returns a [Blob] for the computation with the specified blob key, or `null` if the computation
>    * isn't found.
>    */
> ```
Returns a [Blob] with the specified blob key, or `null` if not found.
</blockquote></details>

Done.

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/37)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/storage/Store.kt, line 32 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/37#-MjWG5P13--5L-MUfiFF:-MjWJJ1WB98zVORO6tH4:b-ulmx3g) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/e7c94b0c9b7be6447fb9395af6677872d2ce69dc/src/main/kotlin/org/wfanet/measurement/storage/Store.kt#L32)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

It's useful for other operations. e.g. Duchy operator can manually retrieve all blobs for a given prefix. See https://cloud.google.com/storage/docs/samples/storage-list-files-with-prefix.
</blockquote></details>

That is not a good example usage. All blobs in duchy will have a TTL like 2d. There is no need to manually retrieve them for any purpose I guess.

If we have multiple Stores with different types, when reading a blob, are we going to parse the prefix to select a Store to use? I'v already refactored the duchy to use a single Store for everything in https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/271

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/37)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/storage/Store.kt, line 32 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/37#-MjWG5P13--5L-MUfiFF:-MjWO53-DuCJirs5rbIN:b-rnw7ty) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/e7c94b0c9b7be6447fb9395af6677872d2ce69dc/src/main/kotlin/org/wfanet/measurement/storage/Store.kt#L32)):*
> That is not a good example usage. All blobs in duchy will have a TTL like 2d. There is no need to manually retrieve them for any purpose I guess.

We can't really predict this. It's really something to help with debugging if need be.

> If we have multiple Stores with different types, when reading a blob, are we going to parse the prefix to select a Store to use?

That would be a somewhat uglier way to do it. Better would be to persist which store to use alongside the blob key if you need to differentiate.

> I'v already refactored the duchy to use a single Store for everything in world-federation-of-advertisers/cross-media-measurement#271

When I made the suggestion that a single store would be viable, I hadn't considered that the stores currently use different context info to generate their blob keys. One option to use the same store would be to have context info that's common across the two items being stored. (We don't necessarily need to be super detailed in our prefix, just enough to be useful.) Another option would be to have a shared interface for the context object that knows how to generate blob keys, and have different impls of that context object.

e.g.

```
interface BlobContext {
  fun generateBlobKey(): String
}

data class ComputationTokenBlobContext(val token: ComputationToken) : BlobContext {
  override fun generateBlobKey() {
    // Same token-based generation code
  }
}
```

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/37)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/storage/Store.kt, line 32 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/37#-MjWG5P13--5L-MUfiFF:-MjWQzRL7b5dWTgbn9Pm:bw5tw4r) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/e7c94b0c9b7be6447fb9395af6677872d2ce69dc/src/main/kotlin/org/wfanet/measurement/storage/Store.kt#L32)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> That is not a good example usage. All blobs in duchy will have a TTL like 2d. There is no need to manually retrieve them for any purpose I guess.

We can't really predict this. It's really something to help with debugging if need be.

> If we have multiple Stores with different types, when reading a blob, are we going to parse the prefix to select a Store to use?

That would be a somewhat uglier way to do it. Better would be to persist which store to use alongside the blob key if you need to differentiate.

> I'v already refactored the duchy to use a single Store for everything in world-federation-of-advertisers/cross-media-measurement#271

When I made the suggestion that a single store would be viable, I hadn't considered that the stores currently use different context info to generate their blob keys. One option to use the same store would be to have context info that's common across the two items being stored. (We don't necessarily need to be super detailed in our prefix, just enough to be useful.) Another option would be to have a shared interface for the context object that knows how to generate blob keys, and have different impls of that context object.

e.g.

```
interface BlobContext {
  fun generateBlobKey(): String
}

data class ComputationTokenBlobContext(val token: ComputationToken) : BlobContext {
  override fun generateBlobKey() {
    // Same token-based generation code
  }
}
```
</blockquote></details>

I don't want to have multiple `Store`s in the duchy since (as you said) we then need to persist which store to use alongside the blob key. It is doable, but just a waste time to refactor the code I feel.

Does this abstract class support typeless Store? If we use a single Store in the duchy, then it won't use any context to generate the blob key.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/37)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/storage/Store.kt, line 32 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/37#-MjWG5P13--5L-MUfiFF:-MjWSnwp4i43hsCEatiB:bogh3w2) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/e7c94b0c9b7be6447fb9395af6677872d2ce69dc/src/main/kotlin/org/wfanet/measurement/storage/Store.kt#L32)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

I don't want to have multiple `Store`s in the duchy since (as you said) we then need to persist which store to use alongside the blob key. It is doable, but just a waste time to refactor the code I feel.

Does this abstract class support typeless Store? If we use a single Store in the duchy, then it won't use any context to generate the blob key.

</blockquote></details>

I'd advocate for still having context into using the last suggestion I mentioned. My thought was that a case like SketchStore in the correctness test would just use String as its context, as that's the equivalent of being able to specify your own blob key.

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/37)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/storage/Store.kt, line 32 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/37#-MjWG5P13--5L-MUfiFF:-MjWTLN538UkHSpV8Kwl:b-9ivp6h) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/e7c94b0c9b7be6447fb9395af6677872d2ce69dc/src/main/kotlin/org/wfanet/measurement/storage/Store.kt#L32)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I'd advocate for still having context into using the last suggestion I mentioned. My thought was that a case like SketchStore in the correctness test would just use String as its context, as that's the equivalent of being able to specify your own blob key.
</blockquote></details>

What context type do you plan to use for requisition blobs?

currently the path is simply "requisitions/UUID". I guess we don't want to use requisitions/{$requisitionId} as blob path in production.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/37)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/storage/Store.kt, line 32 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/37#-MjWG5P13--5L-MUfiFF:-MjWYQGO3_jUTLXwDo_w:b-wo65u4) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/e7c94b0c9b7be6447fb9395af6677872d2ce69dc/src/main/kotlin/org/wfanet/measurement/storage/Store.kt#L32)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

What context type do you plan to use for requisition blobs?

currently the path is simply "requisitions/UUID". I guess we don't want to use requisitions/{$requisitionId} as blob path in production.
</blockquote></details>

Nothing wrong with including requisition ID in production. Could be as simple as`/requisitions/$dataProviderId/$requisitionId/UUID`. Still need to have UUID to avoid collisions in case we had a failed upload without a DB write.

**Review by wangyaopw — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/37)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/storage/Store.kt, line 32 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/37#-MjWG5P13--5L-MUfiFF:-MjWZbVn5nPFVvVSJeRd:b32wwp) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/e7c94b0c9b7be6447fb9395af6677872d2ce69dc/src/main/kotlin/org/wfanet/measurement/storage/Store.kt#L32)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Nothing wrong with including requisition ID in production. Could be as simple as`/requisitions/$dataProviderId/$requisitionId/UUID`. Still need to have UUID to avoid collisions in case we had a failed upload without a DB write.
</blockquote></details>

sg

**Review by wangyaopw — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/37)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/37)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
