### PR TITLE
Fix a bug that delay is not doing anything.

### PR DESCRIPTION
**Pull request by wangyaopw**
It was using a negative value.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/60)

### CODE REVIEW

**Review by efoxepstein — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/60#-:-MoAP9Yn36L4fSYUi4DD:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/60)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/common/throttler/MinimumIntervalThrottler.kt, line 51 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/60#-MoAUTGt5_fRcxSML_Ep:-MoAUTGt5_fRcxSML_Eq:bm25hid) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/98bf6acbfb14fbca821c3af15841b5530f45f81b/src/main/kotlin/org/wfanet/measurement/common/throttler/MinimumIntervalThrottler.kt#L51)):*
> ```Kotlin
>           break
>         }
>         delay(-delta.toMillis())
> ```

this might have been more clear to someone reading through the code if this had been in an else statement of the above `if > 0 ` wdyt?

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/60)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/measurement/common/throttler/MinimumIntervalThrottler.kt, line 51 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/60#-MoAUTGt5_fRcxSML_Ep:-MoAYUlt4kqTwg111azH:b-xkxsqt) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/98bf6acbfb14fbca821c3af15841b5530f45f81b/src/main/kotlin/org/wfanet/measurement/common/throttler/MinimumIntervalThrottler.kt#L51)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

this might have been more clear to someone reading through the code if this had been in an else statement of the above `if > 0 ` wdyt?
</blockquote></details>

sg

Done

**Review by wangyaopw — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/60)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)

**Pull request merged**
