### PR TITLE
refactor: Deprecate Spanner extensions for protobuf values

### PR DESCRIPTION
**Pull request by SanjayVas**
This is now handled by the Spanner client library.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/272)

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/272)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/test/kotlin/org/wfanet/measurement/gcloud/spanner/StatementsTest.kt` line 61 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/272#-O6z3ZW00OmhVKYpmjiL:-O6z3ZW00OmhVKYpmjiM:b-73wadi) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/abd48fb91151c05ec884b19f4c30d510d9064cbc/src/test/kotlin/org/wfanet/measurement/gcloud/spanner/StatementsTest.kt#L61)):*
> ```Kotlin
>         "EnumColumn" to cardinality.number,
>         "ProtoBytesColumn" to field.toGcloudByteArray(),
>         "ProtoJsonColumn" to field.toJson(),
> ```

Always wondered why the ```,``` is added to the last element? Is it a common good practice?



_Code quote:_
```Kotlin
,
```

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/272)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @Marco-Premier)

___
*[`src/test/kotlin/org/wfanet/measurement/gcloud/spanner/StatementsTest.kt` line 61 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/272#-O6z3ZW00OmhVKYpmjiL:-O70UMxeEMXRpD1jPazq:b-5tb8) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/abd48fb91151c05ec884b19f4c30d510d9064cbc/src/test/kotlin/org/wfanet/measurement/gcloud/spanner/StatementsTest.kt#L61)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

Always wondered why the ```,``` is added to the last element? Is it a common good practice?
</blockquote></details>

Yes, you often want to use trailing commas on multiline structures when supported by the language. It helps to avoid merge conflicts when adding items, for example. `ktfmt` ensures we're consistent with trailing comma usage.

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> Dismissed @Marco-Premier from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/272)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/272)* status: 8 of 10 files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/272)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Pull request merged**
