### PR TITLE
Add Statements class for better bind syntax

### PR DESCRIPTION
**Pull request by yunyeng**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/13)

### CODE REVIEW

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/13)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliver-amzn and @stevenwarejones)

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/13)* status: all files reviewed, 1 unresolved discussion (waiting on @oliver-amzn, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/gcloud/spanner/Statements.kt, line 115 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/13#-Mf9587h0vRfEUto7soe:-Mf9587h0vRfEUto7sof:b3vmo7u) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/22c2b9bf992fa9e54ce0a6ae76e943f4765c80a3/src/main/kotlin/org/wfanet/measurement/gcloud/spanner/Statements.kt#L115)):*
> ```
> makeStatement
> ```
nit: Generally for type-safe builders, you just use the name of the type. e.g. just `statement`. That's not a hard-and-fast rule though. For example, I used `buildXXX` for local proto builders to avoid conflicting with official Kotlin DSL.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
can you add some tests?

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/13#-:-MfEX6mr10vAnm8Np3NY:bmlb3sl)* status: all files reviewed, 1 unresolved discussion (waiting on @oliver-amzn and @yunyeng)

**Review by efoxepstein — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/13#-:-MfoI9UuD--Ub6CAEA6v:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @oliver-amzn and @yunyeng)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/13)* status: all files reviewed, 1 unresolved discussion (waiting on @oliver-amzn and @yunyeng)

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/13)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliver-amzn)

**Pull request merged**
