### PR TITLE
Switch from com.nhaarman.mockitokotlin2 to org.mockito.kotlin

### PR DESCRIPTION
**Pull request by tristanvuong2021**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/4)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/4)* status: all files reviewed, 1 unresolved discussion (waiting on @corbantek, @oliver-amzn, @tristanvuong2021, and @zachcwc)

___
*[imports/kotlin/org/mockito/kotlin/BUILD.bazel, line 4 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/4#-MdOAPsJ67MN0zD280iE:-MdOAPsK21cKXrX1zXzY:bshkyem) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/f166b91fe889c9af325aca9a70129e009c5c34ba/imports/kotlin/org/mockito/kotlin/BUILD.bazel#L4)):*
> ```
> mockito_kotlin
> ```
Just name this target `kotlin` to match the package name, since I believe this target gives us everything in the namespace. This allows us to use the short form label (`//imports/kotlin/org/mockito/kotlin`)

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 3 of 5 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/4)* status: all files reviewed, 1 unresolved discussion (waiting on @corbantek, @tristanvuong2021, and @zachcwc)

**Comment by tristanvuong2021** [comment]
___
*[imports/kotlin/org/mockito/kotlin/BUILD.bazel, line 4 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/4#-MdOAPsJ67MN0zD280iE:-MdcBtEdBoFA7EZ02U8r:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/f166b91fe889c9af325aca9a70129e009c5c34ba/imports/kotlin/org/mockito/kotlin/BUILD.bazel#L4)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> mockito_kotlin
> ```
Just name this target `kotlin` to match the package name, since I believe this target gives us everything in the namespace. This allows us to use the short form label (`//imports/kotlin/org/mockito/kotlin`)
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/4)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corbantek and @zachcwc)

**Pull request merged**
