### PR TITLE
Remove unneeded gcloud postgres password flag

### PR DESCRIPTION
**Pull request by tristanvuong2021**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/142)

### CODE REVIEW

**Review by SanjayVas — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/142)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/gcloud/postgres/PostgresConnectionFactories.kt` line 31 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/142#-N80vCQ05ymKkIVQu_3_:-N80vCQ05ymKkIVQu_3a:b-jla897) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/b9aab565c55cd69c58ac680f90da077046869958/src/main/kotlin/org/wfanet/measurement/gcloud/postgres/PostgresConnectionFactories.kt#L31)):*
> ```Kotlin
>         .option(ConnectionFactoryOptions.USER, flags.user)
>         // a non-empty password is required, but the value doesn't matter
>         .option(ConnectionFactoryOptions.PASSWORD, "password")
> ```

nit: maybe used "unused" as the value to make it even clearer



_Code quote:_
```Kotlin
password
```

**Review by duliomatos1 — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/142)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by tristanvuong2021 — COMMENTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/142)* status: 3 of 5 files reviewed, all discussions resolved (waiting on @duliomatos1, @stevenwarejones, and @tristanvuong2021)

**Review by tristanvuong2021 — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/142)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Pull request merged**
