### PR TITLE
Add service config import

### PR DESCRIPTION
**Pull request by jcorilla**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/247)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/247)* status: all files reviewed, 1 unresolved discussion (waiting on @jcorilla and @Marco-Premier)

___
*[`imports/kotlin/io/grpc/service_config/BUILD.bazel` line 9 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/247#-NwMOnkH4F2NRKTEkN6o:-NwMOnkI31D92VjAiCDl:undefined) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/e14165696b22935ee7f6d671c8e2b939c31495de/imports/kotlin/io/grpc/service_config/BUILD.bazel#L9)):*
> ```Starlark
> 
> kt_jvm_proto_library(
>     name = "service_config_kt_jvm_grpc_proto",
> ```





_Suggestion:_
```Starlark
service_config_kt_jvm_proto
```

**Review by jcorilla — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/247)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Marco-Premier and @SanjayVas)

___
*[`imports/kotlin/io/grpc/service_config/BUILD.bazel` line 9 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/247#-NwMOnkH4F2NRKTEkN6o:-NwMPCCC67y8WiUNSI04:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/e14165696b22935ee7f6d671c8e2b939c31495de/imports/kotlin/io/grpc/service_config/BUILD.bazel#L9)):*
> ```Starlark
> 
> kt_jvm_proto_library(
>     name = "service_config_kt_jvm_grpc_proto",
> ```

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/247)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/247)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jcorilla)

**Pull request merged**
