### PR TITLE
Update Bazel version to 5.1.1

### PR DESCRIPTION
**Pull request by iverson52000**
Update Bazel version to 5.1.1 and fix breaking changes from transitive dependencies
image

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/110)

### CODE REVIEW

**Review by stevenwarejones — COMMENTED** [review]
any potential downstream issues with panel-exchange-client or cross-media-measurement to adopt this?

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/110#-:-N1GPfnW1ngb7Z8WU1yP:bk03r4o)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @renjiezh, @SanjayVas, @tristanvuong2021, and @yunyeng)

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/110)* status: all files reviewed, 1 unresolved discussion (waiting on @iverson52000, @renjiezh, @SanjayVas, @tristanvuong2021, and @yunyeng)

___
*[`build/com_github_grpc_grpc/repo.bzl` line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/110#-N1GQ-uy1n--Tbtio9F6:-N1GQ-uy1n--Tbtio9F7:brrxg7o) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/48bef89c2c8a1fb4f0de065b93e1d904fb066922/build/com_github_grpc_grpc/repo.bzl#L26)):*
> ```Starlark
>             name = "com_github_grpc_grpc",
>             sha256 = "8eb9d86649c4d4a7df790226df28f081b97a62bf12c5c5fe9b5d31a29cd6541a",
>             strip_prefix = "grpc-1.36.4",
> ```

is this not compatible with bazel 5?

**Review by renjiezh — COMMENTED** [review]
hint: tuning here (https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/build/repositories.bzl#L25-L30) you can check if cross-media-measurement works with the new common-jvm. You could specify the commit instead of version in `wfa_repo_archive()` so that you test it without creating a new release.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/110#-:-N1GSEtS2tuO3h_dIROe:bqol966)* status: all files reviewed, 1 unresolved discussion (waiting on @iverson52000, @SanjayVas, @tristanvuong2021, and @yunyeng)

**Review by iverson52000 — COMMENTED** [review]
@stevenwarejones Yes panel-exchange-client, cross-media-measurement, and other downstream repos have to be updated too to build with Bazel 5

@renjiezh Yes I have tested all the downstream repos with this new common-jvm and have fixed the breaking changes. I am opening PRs starting from common-jvm and common-cpp

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/110#-:-N1KGn6k2Bfp7Qpw1pIc:b3zxi2r)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas, @stevenwarejones, @tristanvuong2021, and @yunyeng)

___
*[`build/com_github_grpc_grpc/repo.bzl` line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/110#-N1GQ-uy1n--Tbtio9F6:-N1KI_OW7dgy7QTyc-Lf:b558uiz) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/48bef89c2c8a1fb4f0de065b93e1d904fb066922/build/com_github_grpc_grpc/repo.bzl#L26)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

is this not compatible with bazel 5?
</blockquote></details>

No this has to be updated to newer version

**Review by SanjayVas — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/110)* status: all files reviewed, 2 unresolved discussions (waiting on @iverson52000, @stevenwarejones, @tristanvuong2021, and @yunyeng)

___
*[`build/com_github_grpc_grpc/repo.bzl` line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/110#-N1KguCL2XMQZ-WlcgDi:-N1KguCL2XMQZ-WlcgDj:b-xy6589) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/2a6c4565855493f223db39a0e62a2b3f7aa4a1d5/build/com_github_grpc_grpc/repo.bzl#L26)):*
> ```Starlark
>             name = "com_github_grpc_grpc",
>             sha256 = "e18b16f7976aab9a36c14c38180f042bb0fd196b75c9fd6a20a2b5f934876ad6",
>             strip_prefix = "grpc-1.45.2",
> ```

nit: 1.46.0 was released for both this and grpc-java



_Code quote:_
```Starlark
1.45.2
```

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/110)* status: all files reviewed, 1 unresolved discussion (waiting on @iverson52000, @tristanvuong2021, and @yunyeng)

**Comment by SanjayVas** [comment]
I believe this effectively depends on https://github.com/world-federation-of-advertisers/common-jvm/pull/111 to make sure we don't break Spanner integration.

**Review by iverson52000 — COMMENTED** [review]
Correct. I will merge in #111 (Update google-cloud-spanner to 6.23.3.) when it's closed before merging this PR   

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/110#-:-N1eLhkj3KzHYN2XDV1T:b6xey86)* status: all files reviewed, 1 unresolved discussion (waiting on @iverson52000, @tristanvuong2021, and @yunyeng)

**Pull request merged**
