### PR TITLE
Add PublicKey to PemWriter and make it public

### PR DESCRIPTION
**Pull request by yunyeng**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/97)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/97)* status: all files reviewed, 1 unresolved discussion (waiting on @yunyeng)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/97#-MwYTzqzEqEFGsvYPkyq:-MwYTzr-APwXCoVO2__h:bc2kk28) (no related file):*
You'll probably want to split this out into a separate kt_jvm_library rather than having it be part of `signing_key_storage`. This means making everything that's currently `internal` public.

---

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/97)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/97#-MwYTzqzEqEFGsvYPkyq:-Mwc9LTZEkpXTkvD2482:b-896fix) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You'll probably want to split this out into a separate kt_jvm_library rather than having it be part of `signing_key_storage`. This means making everything that's currently `internal` public.
</blockquote></details>

Done.

---

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/97)* status: all files reviewed, 1 unresolved discussion (waiting on @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/BUILD.bazel, line 37 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/97#-MwcNn_y8Qbray7p02Ke:-MwcNn_z7iWlMgVDKzVo:b-qzg11e) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/416c3101f9a231f26c8806b4e4f35f79483daec9/src/main/kotlin/org/wfanet/measurement/common/crypto/BUILD.bazel#L37)):*
> ```Starlark
> 
> kt_jvm_library(
>     name = "signing_key_converter",
> ```

Why this and not `pem_io`? This is generic PEM I/O and not specific to signing keys, It was only internal to the `signing_key_storage` library due to not being needed elsewhere.



_Code quote:_
```Starlark
signing_key_converter
```

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/97)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @duliomatos1 and @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/BUILD.bazel, line 37 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/97#-MwcNn_y8Qbray7p02Ke:-MwcqHL3Eub1kE_8_-ec:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/416c3101f9a231f26c8806b4e4f35f79483daec9/src/main/kotlin/org/wfanet/measurement/common/crypto/BUILD.bazel#L37)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why this and not `pem_io`? This is generic PEM I/O and not specific to signing keys, It was only internal to the `signing_key_storage` library due to not being needed elsewhere.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/97)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1)

**Review by duliomatos1 — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/97)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yunyeng)

**Pull request merged**
