### PR TITLE
Rename COMMON_JVM_MAVEN_TARGETS

### PR DESCRIPTION
**Pull request by enfreck**
Rename COMMON_JVM_MAVEN_TARGETS to COMMON_JVM_MAVEN_OVERRIDE_TARGETS and rename a macro.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/27)

### CODE REVIEW

**Review by SanjayVas — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/27)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @efoxepstein, @matthewclegg, and @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/27)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @enfreck, and @matthewclegg)

___
*[-- commits, line 3 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/27#-MgvpRIh15O2MrBfcv43:-MgvpRIh15O2MrBfcv44:b-kttv3e) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/728d3ea5d46be6cfa718f2f9a8bada37d8c58e7f/-- commits#L3)):*
fix the pr title --- says `COMMON_JVM_MABEN_TARGETS`

**Review by efoxepstein — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/27)* status: all files reviewed, 1 unresolved discussion (waiting on @enfreck and @matthewclegg)

**Review by enfreck — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/27)* status: all files reviewed, 1 unresolved discussion (waiting on @matthewclegg and @stevenwarejones)

___
*[-- commits, line 3 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/27#-MgvpRIh15O2MrBfcv43:-Mgw007t2lsvhpqMOVyX:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/common-jvm/blob/728d3ea5d46be6cfa718f2f9a8bada37d8c58e7f/-- commits#L3)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

fix the pr title --- says `COMMON_JVM_MABEN_TARGETS`
</blockquote></details>

Done.

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/27)* status: all files reviewed, 1 unresolved discussion (waiting on @matthewclegg and @stevenwarejones)

**Review by matthewclegg — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/27)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

**Review by enfreck — COMMENTED** [review]
> Dismissed @stevenwarejones from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/27)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @enfreck)

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/27)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @enfreck)

**Pull request merged**
